### ISSUE TITLE
Make transparent an option per protocol

### ISSUE THREAD

**Issue by yrutschle** [yrutschle/sslh#101]
This doesn't need to be global to all protocols.

**Comment by rexdf** [comment]
Indeed!   I just want to make transparent proxy for web.

**Comment by kaasszje** [comment]
Would really love this feature as well....

**Comment by evert-mouw** [comment]
Duplicated in https://github.com/yrutschle/sslh/issues/243

**Comment by yrutschle** [comment]
Implemented in adb27aa4a391410d278a5590fcce644f32e33e8c
