### ISSUE TITLE
Transparent proxy stopped working

### ISSUE THREAD

**Issue by msrv** [yrutschle/sslh#110]
Hey, 

after a long time of using sslh flawlessly, i moved to a new server and did a clean install of debian 8. I tried my best to do an exact copy of my previous system, but i can't get the transparent proxy to work...

What i've done:

Installed dependencies, libwrap, libcap etc and compiled sslh with libcap support. 
Created unprivileged sslh user 
Did the iptables & route table adjustments 
Did the setcap trick to set the capabilities...

This is my config: /usr/sbin/sslh --pidfile /var/run/sslh.pid -p 0.0.0.0:443 --ssl 192.168.2.12:4433 --openvpn 192.168.2.12:1194 -n --transparent --timeout 20 

I used 0.0.0.0 because i use a dynamic ip via ddclient. 

What happens:

Proxying works fine, but it's not transparent. Every IP is just 192.168.2.12, regardless of the listen ip (0.0.0.0, 192.168.2.12...). 

I tried to run it as root --> same thing, no transparent proxying.

Am i missing out something? Thank you :)

**Comment by msrv** [comment]
Update: Tried with iptables default allow and no other rules than the one specific for sslh. It sill shows 192.168.2.12. 

My Network looks like:  WWW --> Router (Nat) --> Server 192.168.2.12 with ddclient & dynamic ip (Ipv6 is off).

I sill don't know why the machine's own IP is passed to nginx/openvpn...

**Comment by RadarNyan** [comment]
Can you try revert 9cc47a1 and see how it goes? I think that commit might break transparent proxy.

**Comment by msrv** [comment]
RadarNyan, that did the trick. Now the ip is reported correctly and everything works fine. Thank you so much!

**Comment by yrutschle** [comment]
I reverted f02ce3821c018719536971dbb1bc1ed1517530a2 where I accidently commited untested code on transparent proxying that was unrelated to to the commit. Hopefully that'll fix this issue.
