### ISSUE TITLE
Listen on all ports

### ISSUE THREAD

**Issue by kristiandrucker** [yrutschle/sslh#111]
Hi can sslh listen on a domain on all ports and then forward/proxy the packets to an ip on internal network?

**Comment by yrutschle** [comment]
On Tue, Nov 15, 2016 at 02:29:47PM -0800, Kristian Drucker wrote:
> Hi can sslh listen on a domain on all ports and then forward/proxy the packets to an ip on internal network?

Yes, you can specify the listen option several times, so
once per port. I don't know if you'll run into limitations
(I don't think sslh has any, but I don't know if processes
are supposed to open thousands of listening sockets).

It might be more convenient to use netcat in front of sslh
to funnel all the ports to sslh (I understand you can
specify ranges of ports in netcat).

Y.
