### ISSUE TITLE
Name based (SSH, HTTS, etc..) virtual hosts

### ISSUE THREAD

**Issue by sspreitzer** [yrutschle/sslh#112]
Hi

Primarly looking for a SSH multiplexer that forwards to other ssh boxes depending on their fqdn/hostname.
Not quite sure though if SSH protocol sends hostname over.

Thank you very much!

Kind regards
Sascha

**Comment by yrutschle** [comment]
On Thu, Nov 17, 2016 at 09:07:02AM -0800, Sascha Spreitzer wrote:
> Primarly looking for a SSH multiplexer that forwards to other ssh boxes depending on their fqdn/hostname.
> Not quite sure though if SSH protocol sends hostname over.

It doesn't, you just can't do that.

If it's acceptable, you can tunnel ssh through stunnel on
the client side and have sslh do virtual hosting using SNI.
It's not really SSH anymore though :-)

Y.
