### ISSUE TITLE
Feature Request: Release package signing

### ISSUE THREAD

**Issue by g4jc** [yrutschle/sslh#116]
Hello,
There is currently no way to verify the complete integrity of releases. Please consider signing your releases so that package maintainers can verify the sources prior to packaging. (Tagging is a help, but cannot be used in PKGBUILDs)

See here for how-to and complete details:
https://wiki.debian.org/Creating%20signed%20GitHub%20releases

The signatures could also be included on your website.

Thank you

**Comment by yrutschle** [comment]
Sorry, I am confused: sslh tags are already signed (unless I forget about it, but v1.18 at least is signed), and there is no concept of release in git as far as I know, and in fact github.com lists all the tags as releases as well (with .tar.gz and whatnot).

**Comment by g4jc** [comment]
Basically, git tagging is useless when upstream distros are packaging, since they are only downloading your packaged source tarball. It is possible to create official "releases" on github, but since a majority of distros are pulling from your website it will be fine to simply sign the packages there.

Then during compile time the packager will be able to download and verify.

e.g.
wget http://www.rutschle.net/tech/sslh/sslh-v1.18.tar.gz
wget http://www.rutschle.net/tech/sslh/sslh-v1.18.tar.gz.asc (_currently this file is missing_)

gpg --verify sslh-v1.18.tar.gz.asc sslh-v1.18.tar.gz

Otherwise the upstream sources are completely unverified, leading to situations like the Linux Mint hacker earlier this year: https://micahflee.com/2016/02/backdoored-linux-mint-and-the-perils-of-checksums/

**Comment by Tsutsukakushi** [comment]
@yrutschle I don't see any signatures at https://github.com/yrutschle/sslh/releases/tag/v1.18 or https://github.com/yrutschle/sslh/releases/tag/v1.17

**Comment by yrutschle** [comment]
@g4jc : Ok, I've published an ASC file for v1.18 (link on the Web site, and the URL is predictably what you pointed out as missing).

@Tsutsukakushi : The tags actually are signed, but I just now realised Github expected me to push my GPG key and verify related e-mail addresses... so maybe it removes signatures it can't check? I've added my public key and verified my address, and tags now appear as 'verified' to me. Please re-open the issue if that did nothing for you.
