### ISSUE TITLE
Can't build with USELIBCAP=1

### ISSUE THREAD

**Issue by TehMino** [yrutschle/sslh#117]
Hello,
I'm running a Debian 8.6 Jessie server with sslh 1.16-2 from official debian repos.
This version doesn't have the --transparent option that i really need.

So i followed your tutorial README and installed the packages libcap-dev, libcap2-bin, libwrap0-dev and libconfig8-dev.
Then i runned git clone https://github.com/yrutschle/sslh, edited Makefile to set USELIBCAP=1 and the output is :

```
./genver.sh >version.h
cc -Wall -g  -DENABLE_REGEX -DLIBCONFIG -DLIBCAP -c common.c
common.c: In function 'set_capabilities':
common.c:662:9: error: 'transparent' undeclared (first use in this function)
     if (transparent)
         ^
common.c:662:9: note: each undeclared identifier is reported only once for each function it appears in
Makefile:63: recipe for target 'common.o' failed
make: *** [common.o] Error 1
```

Is there anything i'm forgetting or doing wrong ?

**Comment by yrutschle** [comment]
On Fri, Jan 06, 2017 at 04:35:48PM -0800, TehMino wrote:
> common.c:662:9: error: 'transparent' undeclared (first use in this function)
>      if (transparent)

I think this is also linked to to commit f02ce3821c018719536971dbb1bc1ed1517530a2 where I accidently commited untested code. I reverted the commit, it should be OK now.
