### ISSUE TITLE
Transparent mode won't work on FreeBSD

### ISSUE THREAD

**Issue by andrin55** [yrutschle/sslh#118]
Hello 

I'm using FreeBSD 11.0-RELEASE-p2 and SSLH 1.18 (trough official FreeBSD repo). 
I have the following setup:
sslh server                       192.168.0.10 port 444
openvpn server               192.168.0.20 port 443
apache server                  192.168.0.30 port 443

When I use SSLH without "--transparent" everything works flawless. When I enable transparent mode, "curl -v -k https://192.168.0.10:444" just times out.

To test SSLH I use the following command:
sslh-select --listen 192.168.0.10:444 --ssl 192.168.0.30:443 --anyprot 192.168.0.20:443 --transparent -f -v

My rules in /etc/ipfw/sslh.rules are the following:
ipfw add 20000 fwd 192.168.0.10,444 log tcp from 192.168.0.20 443 to any out
ipfw add 20010 fwd 192.168.0.10,444 log tcp from 192.168.0.30 443 to any out

The firewall is enabled in /etc/rc.conf and the rules get listed when I do "ipfw list".

This is the output from curl:
`curl -v -k https://192.168.0.10:444
About to connect() to 192.168.0.10 port 444 (#0)
Trying 192.168.0.10...
Connected to 192.168.0.10 (192.168.0.10) port 444 (#0)
Initializing NSS with certpath: sql:/etc/pki/nssdb
NSS error -5938 (PR_END_OF_FILE_ERROR)
Encountered end of file
Closing connection 0
curl: (35) Encountered end of file`

This is the output from sslh:
`sslh-select 1.18 started
selecting... max_fd=4 num_probing=0
accepted fd 4 on slot 0
selecting... max_fd=5 num_probing=1
processing fd0 slot 0
**** writing deferred on fd -1
probing for ssl
connecting to 192.168.0.30:https family 2 len 16
forward to ssl failed:connect: Operation timed out
closing fd 4`

Is there something wrong with my rules?

Thank you for your help

**Comment by andrin55** [comment]
Nobody?

**Comment by yrutschle** [comment]
On Mon, Jan 23, 2017 at 09:23:42AM -0800, andrin55 wrote:
> `sslh-select 1.18 started
> selecting... max_fd=4 num_probing=0
> accepted fd 4 on slot 0
> selecting... max_fd=5 num_probing=1
> processing fd0 slot 0
> **** writing deferred on fd -1
> probing for ssl
> connecting to 192.168.0.30:https family 2 len 16
> forward to ssl failed:connect: Operation timed out
> closing fd 4
> selecting... max_fd=5 num_probing=0`

This suggests that the sslh connection packets get
"somewhere" (otherwise sslh would fail connecting) but that
packets aren't being routed properly back to sslh to finish
the connection.

Sorry, I barely understand how the iptables solution works,
I can't help on BSD's firewall :/

Y.

**Comment by andrin55** [comment]
Well I'm pretty new to FreeBSD...
Do you know anybody who could help me?

**Comment by andrin55** [comment]
To my understandig it works like that:
![image](https://cloud.githubusercontent.com/assets/2856476/22582720/c1172c40-e9e8-11e6-981f-4d3e28f171fd.png)

So I have to point any outgoing traffic from the HTTPS server back to the listening port from SSLH?

**Comment by andrin55** [comment]
If the HTTP server (192.168.0.20) in this example would have the following firewall rule:
ipfw add 301 fwd 192.168.0.10,443 log tcp from 192.168.0.20 444 to any out

It should redirect all outgoing traffic back to the SSLH server instead of the client. Sadly this isn't the case.
The IPFW documentation (https://www.freebsd.org/cgi/man.cgi?query=ipfw&sektion=8&manpath=freebsd-release-ports) states, that it only will change the next hop of the packet:
![image](https://cloud.githubusercontent.com/assets/2856476/22585393/e90a4cbe-e9f7-11e6-9e28-98816666e9ce.png)

So the firewall on the SSLH server must be configured to accept this packets. If the firewall on the SSLH host would be an netfilter/iptables firewall, would you been able to help me with the rules?

I tried to understand the documented IPTable rules for SSLH and came to the following result:
--------------------------------------------------------------------------------
#-t (table) mangle for package alterations
#-a output for altering packets before they leave the system/get routed
# protocol is tcp and this applies to packets going out from eth0
#--sport is the source port 
#--jump describes what to do if the rule macthes (redirect to chain sslh)

#create new user defined chain "SSLH"
iptables -t mangle -N SSLH 

#if outgoing packet (from locally running server) matches rule redirect it to SSLH chain 
iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 22 --jump SSLH
iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 4443 --jump SSLH

#If packet arrives in SSLH chain, mark the package with some number, so its identifiable later 
iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
--------------------------------------------------------------------------------

These rules are only working if the SSH or HTTPS server is running on the same host. But I need to get incoming packets (from a different) to get redirected back to SSLH.

**Comment by fuzzyTew** [comment]
Hey, I'm dealing with this error in a different situation, and I'm finding that the cause is SSL disconnecting clients that are too slow to initiate a handshake immedately after connection, likely to prevent DoS.  SSH doesn't seem to send the connection confirmation back to the client until it gets one from the server, so too much latency can create an EOF on connection.  Not sure if this is your issue, but it appears to be mine.

**Comment by yrutschle** [comment]
Please see if this https://github.com/yrutschle/sslh/discussions/454 helps, something similar might work on freebsd. Otherwise, feel free to create a new discussion
