### ISSUE TITLE
Different behavior between cfg and command line

### ISSUE THREAD

**Issue by GonzaloAlvarez** [yrutschle/sslh#121]
I'm not sure if it is an issue, but I'm unable to find an explanation. Maybe something wrong with my configuration, but not trivial.

I have an sslh.cfg file that looks like this:
```
listen:
  (
    { host: "0.0.0.0"; port: "443" }
  );
 
  # List of protocols
  protocols:
 (
    { name: "openvpn", service: "openvpn@server",  host: "localhost", port: "1194"},
    { name: "ssh", service: "ssh",  host: "localhost", port: "22"}
 );
```

and I launch sslh with this configuration like this:
```shell
$ sudo /usr/sbin/sslh -F /etc/sslh.cfg
```

But it refuses communication with the second service I put in the protocols entry, either SSH or OpenVPN, depending on the order I put them.

On the other hand, if I simply use the following command, and ignore the configuration altogether, it works.

```shell
$ sudo /usr/sbin/sslh --timeout 10 --openvpn localhost:1194 --ssh localhost:22 --foreground -p 0.0.0.0:443
```

What is the difference? What am I doing wrong?

Thanks!

**Comment by yrutschle** [comment]
On Thu, Mar 16, 2017 at 04:38:49PM -0700, Gonzalo Alvarez wrote:
> I'm not sure if it is an issue, but I'm unable to find an explanation. Maybe something wrong with my configuration, but not trivial.

Well actually... :-)

> $ sudo /usr/sbin/sslh -F /etc/sslh.cfg
                          ^
                    No space here!

IIRC sslh thinks you request the use of a configuration
file, which is not specified, so goes to pick one in
/etc/sslh/sslh.cfg.                    

If that doesn't help, add -v and verbose: 1 and see what
happens.

Y.

**Comment by GonzaloAlvarez** [comment]
Mmm, that actually was a typo when I wrote it here in github, but I think I actually did it right in the console. Here is a copy of a test with debug enabled that I just did

This is the one that works when I try to connect to the 'second' protocol (openvpn), with all the attributes via cmd line:

```
$ sudo /usr/sbin/sslh -p 0.0.0.0:443 --ssh localhost:22 --openvpn localhost:1194 --foreground -v
ssh addr: localhost:ssh. libwrap service: sshd family 2 2
openvpn addr: localhost:openvpn. libwrap service: (null) family 2 2
listening on:
        0.0.0.0:https
timeout: 2
on-timeout: ssh
listening to 1 addresses
sslh-fork 1.16-2 started
capabilities: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
accepted fd 4
**** writing deferred on fd -1
probing for ssh
probing for openvpn
connecting to localhost:openvpn family 2 len 16
connection from <remotebox>.amazonaws.com:42694 to <localbox>.compute.internal:https forwarded from localhost:49385 to localhost:openvpn
flushing deferred data to fd 3
```

And the one that doesn't work (again, using openvpn on the client), using the cfg file:

```
$ sudo /usr/sbin/sslh -F/etc/sslh.cfg -v --foreground
ssh addr: localhost:ssh. libwrap service: ssh family 2 2
openvpn addr: localhost:openvpn. libwrap service: openvpn family 2 2
listening on:
        0.0.0.0:https
timeout: 2
on-timeout: ssh
listening to 1 addresses
sslh-fork 1.16-2 started
capabilities: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
accepted fd 4
**** writing deferred on fd -1
all probes failed, connecting to first protocol: ssh
connecting to localhost:ssh family 2 len 16
connection from <remote>.amazonaws.com:42699 to <localbox>.internal:https forwarded from localhost:60872 to localhost:ssh
flushing deferred data to fd 3
client socket closed
connection closed down
```

I modified the endpoint boxes for security reasons, but it was basically displaying the fqdn for the local box and the remote. Now, it is interesting to see that the instance with the cfg in the cmd line doesn't actually probe the protocols, even though they are 'initialized'. Does that make sense?

Here is the config file for consistency:
```
listen:
(
   { host: "0.0.0.0"; port: "443" }
);

# List of protocols
protocols:
(
   { name: "ssh", service: "ssh",  host: "localhost", port: "22"},
   { name: "openvpn", service: "openvpn",  host: "localhost", port: "1194"}
);
```

Any help would be more than thankful!

**Comment by GonzaloAlvarez** [comment]
Also, I noticed that in the example above where it works, the verbose output said this:

```
openvpn addr: localhost:openvpn. libwrap service: (null) family 2 2
```

where as in the example that doesn't work, the output was:

```
openvpn addr: localhost:openvpn. libwrap service: openvpn family 2 2
```

so I figured it may be related to the fact that the 'service' was not picked up properly via cmdline, so I tried to replicate that using the config by removing the 'service' part in the openvpn line like this:

```
{ name: "openvpn", host: "localhost", port: "1194"}
```

That gave me the exact same output using the configuration (unless I missed something), but still didn't work:

```
$ sudo /usr/sbin/sslh -F/etc/sslh.cfg -v --foreground
ssh addr: localhost:ssh. libwrap service: ssh family 2 2
openvpn addr: localhost:openvpn. libwrap service: (null) family 2 2
listening on:
        0.0.0.0:https
timeout: 2
on-timeout: ssh
listening to 1 addresses
sslh-fork 1.16-2 started
capabilities: = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,37+ep
accepted fd 4
**** writing deferred on fd -1
all probes failed, connecting to first protocol: ssh
connecting to localhost:ssh family 2 len 16
connection from <remote>.amazonaws.com:42838 to <localbox>.internal:https forwarded from localhost:60873 to localhost:ssh
flushing deferred data to fd 3
server socket closed
connection closed down
```

Again, if there is anything else I could try, I'd be more than happy to do so.

**Comment by yrutschle** [comment]
On Sat, Mar 18, 2017 at 11:48:21PM -0700, Gonzalo Alvarez wrote:
> Mmm, that actually was a typo when I wrote it here in github, but I think I actually did it right in the console.

Shame, I liked the easy fix :-)

> And the one that doesn't work (again, using openvpn on the client), using the cfg file:
> 
> ```
> $ sudo /usr/sbin/sslh -F/etc/sslh.cfg -v --foreground
> ssh addr: localhost:ssh. libwrap service: ssh family 2 2
> openvpn addr: localhost:openvpn. libwrap service: openvpn family 2 2
[...]
> **** writing deferred on fd -1
> all probes failed, connecting to first protocol: ssh

That's odd, it should list the probes it tries between the
"deferred" and the "all probe failed", and the list of
probes at startup is right.

Your config file works as expected for me:

    [...]
    processing fd0 slot 0
    **** writing deferred on fd -1
    probing for ssh
    connecting to localhost:ssh family 10 len 28


Can you try the attached patch? It'll dump the configuration right after the
"deferred" and before actually starting to probe.
(The compilation of the test servers will fail but that's fine, it'll compile
sslh-fork and sslh-select)

Cheers,
Y.

**Comment by nikksno** [comment]
Hi! Any news on this? I have the exact same issue: command line works but sslh.cfg doesn't. I installed on ubuntu 16 with apt and have always had this `/etc/default/sslh`:

```
RUN=yes

DAEMON=/usr/sbin/sslh

DAEMON_OPTS="--user sslh -p <public_ipv4>:443 -p <public_ipv6>:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:443 --xmpp 127.0.0.1:5223 --pidfile /var/run/sslh/sslh.pid"
```

Now I've tried switching over to using the `/etc/sslh/sslh.cfg` file by changing the last line of `/etc/default/sslh` to `DAEMON_OPTS="-F /etc/sslh/sslh.cfg"` and inserting the basic config inside `/etc/sslh/sslh.cfg` and changing the hostname.

Now my `/etc/default/sslh` looks like this:

```
RUN=yes

DAEMON=/usr/sbin/sslh

DAEMON_OPTS="-F /etc/sslh/sslh.cfg"
```

Now my `/etc/sslh/sslh.cfg` file looks like this:

```
verbose: false;
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh.pid";

listen:
(
     { host: "<hostname>";           port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; },
     { name: "xmpp"; host: "localhost"; port: "5222"; },
     { name: "http"; host: "localhost"; port: "80"; },
     { name: "ssl"; host: "localhost"; port: "443"; log_level: 0; }
);
```

As you can see, `transparent` is set to `false`. Also, I've tried using my IPv4 and IPv6 [both separately and simultaneously inside `listen` and that's not the issue. I've run all tests after a `service sslh stop` with `sudo /usr/sbin/sslh -F/etc/sslh/sslh.cfg -v --foreground`.

Everything except for the first service always fails in both IPv4 and IPv6 with:

```
**** writing deferred on fd -1
all probes failed, connecting to first protocol: ssh
getnameinfo(NI_NAMEREQD):Name or service not known
connecting to localhost:22 family 10 len 28
connection from <client_IP>:44035 to <hostname>:https forwarded from localhost:40178 to localhost:22
flushing deferred data to fd 3
client socket closed
connection closed down
```

I've tried everything I found in other posts.

Thanks!

**Comment by nikksno** [comment]
Update: I fixed this following this suggestion: https://github.com/yrutschle/sslh/issues/88 and adding `probe: "builtin";` to every probe except for `timeout`. I've now updated to v1.18 by compiling it directly on the machine and things work without `probe: "builtin";`, as @yrutschle said in the linked thread. Thanks and sorry for the noise!

**Comment by yrutschle** [comment]
Closing because it's closed. (arf).
