### ISSUE TITLE
How to Script install

### ISSUE THREAD

**Issue by ArifADS** [yrutschle/sslh#122]
I want to use sslh in a Raspberry and make unattended/script install, but It ask about standalone or the other sslh version, is there a way to skip that so I cant make the installation unattended?

**Comment by yrutschle** [comment]
On Thu, Mar 23, 2017 at 08:04:23PM -0700, ArifADS wrote:
> I want to use sslh in a Raspberry and make unattended/script install, but It ask about standalone or the other sslh version, is there a way to skip that so I cant make the installation unattended? 

I have no idea what you're talking about, I can only
imagine that's linked to the distribution you use -- please
take it up with your distribution's packagers.


Y.
