### ISSUE TITLE
Feature to disable IP_FREEBIND

### ISSUE THREAD

**Issue by eimann** [yrutschle/sslh#123]
I'm trying to run sslh on SmartOS which provides a lx zones (Linux emulation).
Is there a way to disable IP_FREEBIND as this is not supported by the emulation?

sslh[87268]: 0.0.0.0:https:setsockopt(IP_FREEBIND): Protocol not available

**Comment by eimann** [comment]
I compiled sslh with IP_FREEBIND removed and it works fine in lx zones on SmartOS.

**Comment by yrutschle** [comment]
Sooo it defines IP_FREEBIND to some non-zero value but then
doesn't implement it? (if the symbol isn't defined, sslh
should define it to 0 and then not perform the setsockopt
call).

That feels like a lx zones bug to me, it shouldn't advertise
features it doesn't implement. Alternatively, how is one
supposed to know if it's available?

**Comment by eimann** [comment]
I think it is defined non-zero by

$ grep IP_FREEBIND /usr/include/x86_64-linux-gnu/bits/in.h
#define IP_FREEBIND        15

because it's just a standard Ubuntu 16.04, except the kernel:

$ uname -a
Linux 4feb1c6c-f0cb-4f92-bd7f-b7a3f2ddea88 4.3.0 BrandZ virtual linux x86_64 x86_64 x86_64 GNU/Linux

$ /native/usr/bin/uname -a
SunOS 4feb1c6c-f0cb-4f92-bd7f-b7a3f2ddea88 5.11 joyent_20170202T040152Z i86pc i386 i86pc

I agree it's a corner case, but having the possibility to override the behaviour in the configuration would be nice. I can submit a PR if this would make things easier for you.

**Comment by yrutschle** [comment]
On Wed, Mar 29, 2017 at 11:14:54AM -0700, Dominik Bay wrote:
> I agree it's a corner case, but having the possibility to override the behaviour in the configuration would be nice. I can submit a PR if this would make things easier for you. 

I am not too fond of adding configuration for small details
like this (that'd make compilation complicated for little
gain).

I suppose sslh doesn't need to *die* if the
setsockopt(IP_FREEBIND) fails. IIRC it's used for some
routers where IP address appear after sslh was started: if
sslh just keeps running then that case would fail one
statement later when calling bind(), but it would have
failed anyway. And in your case when IP addresses exist and
IP_FREEBIND is not required, the setsockopt() would fail and
continue to bind() successfully.

I'll think about it some more and see if I didn't forget
something, but I think changing the check_res_dumpdie() into
a simple warning would be fine.

Y.

**Comment by eimann** [comment]
Indeed, you're right. That's another good possibility.

**Comment by yrutschle** [comment]
Fixed in 078827ad3fedb640e45e079a5d34e2771e04a36f

**Comment by yrutschle** [comment]
Actually fixed in b0f4e24ce016310b8cf7f4995632f5e282fa63ee, please pretend that other one has never existed.
