### ISSUE TITLE
pppoe (only) address already in use

### ISSUE THREAD

**Issue by adrhc** [yrutschle/sslh#124]
I have ppp0 over eth0 and I get this:
`sslh-select 1.17-2 started
bind:98:Address already in use
bind_peer:98:Address already in use`
with this setup:
`sslh-select --foreground --transparent --timeout 2 --numeric --user sslh --listen ${wan_ip}:80 --ssh ${wan_ip}:1022 --http ${wan_ip}:1080 --pidfile /var/run/sslh/sslh.pid`
and iptables configured accordingly.
When using the same setup on lan_ip (behind a router connected with pppoe to internet) sslh works just fine.
Of course there's nothing using 80 and nginx is listening on 1080 while ssh on 22 and 1022.
Besides, after this test I start nginx on wan_ip:80 and it works; I stop it in order to free 80 and sslh gives the same result.
The same problem I have with sshttp where I get:
sshttp:: loop::NS_Socket::bind_local::bind:Address already in use

I use ubuntu 16.04 with ufw with default configuration + ports 22, 80, 443 allowed.

**Comment by adrhc** [comment]
I found that eth1 is disturbing ppp0 only when setting eth1 on Automatic (DHCP) otherwise (manual ip setup option) is ok.

**Comment by yrutschle** [comment]
How do you know nothing listening on 80?
`netstat -lpten` (or something like that) should show you all the processes that have listening socket, which should help you find what's hogging your ports.

**Comment by yrutschle** [comment]
Closing due to lack of response
