### ISSUE TITLE
Is it possible to split http/https traffic base on host name?

### ISSUE THREAD

**Issue by RadarNyan** [yrutschle/sslh#127]
I'd like to host some sites on different server programs:

eg:  
```text
(listen) 443 -> ssh -> localhost:22 (sshd)
(listen) 443 -> ssl -> "siteA.com" -> localhost:4431 (httpd)  
(listen) 443 -> ssl -> "siteB.com" -> localhost:4432 (apache)  
(listen) 443 -> ssl -> (any site doesn't match above) -> localhost:4430 (nginx)

(everything is transparent proxy, i.e. server program sees real IP)
```

Can I use sslh as a universal switch as described above, so I don't have to use nginx as a reverse proxy? I'd like to avoid doing that so I don't have to deal with ip address problem one by one.

**Comment by yrutschle** [comment]
Yes, with the 'ssh', 'sni' and 'anyprot' probe (or the very
new 'sni' with pattern matching which may or may not work
for your case :-) ).

**Comment by RadarNyan** [comment]
I managed to get it work using ```tls``` and ```sni_hostnames``` :) thank you.

However, I failed to compile the latest version myself, had to download and install .deb from debian.
This is what I did:
- I cloned the repo, edited ```Makefile``` set ```USELIBCAP=1``` save the file
- Then I installed all the depencies and run ```make```, copied ```sslh-fork``` to ```/usr/sbin/sslh```
- After that I used ```setcap``` and confirmed with ```getcap``` on  ```/usr/sbin/sslh```

Yet it only works with root. If I use ```--user sslh``` then I'll get ```setsockopt: Operation not permitted```
I know it's not related to this issue but what did I do wrong? (Ubuntu 16.04.2 LTS)

**Comment by Yasston** [comment]
I've got the exact same question, but with version 1.17 where I can't seem to be able to use tls and sni_hostnames options. I use sslh coming from a compiled version for Synology NAS. It hasn't been upgraded and is still on v 1.17. I asked SynoCommunity for an upgrade, but in the meantime, can you help ? As I understand it, I need to use the "probe" option in the protocol line, but what should I put in there ? Can I use a regex for specifying two different subdomains ?
Thank you very much for your guidance, if I must open another issue, please let me know.

**Comment by yrutschle** [comment]
On Tue, Oct 24, 2017 at 08:16:52AM -0700, Yasston wrote:
> I've got the exact same question, but with version 1.17 where I can't seem to be able to use tls and sni_hostnames options. I use sslh coming from a compiled version for Synology NAS. It hasn't been upgraded and is still on v 1.17. I asked SynoCommunity for an upgrade, but in the meantime, can you help ? As I understand it, I need to use the "probe" option in the protocol line, but what should I put in there ? Can I use a regex for specifying two different subdomains ?

Maybe the regex can work, I don't really know what the data
looks like. You can try and check it out with tcpdump
(something like `tcpdump -s0 -X tcp port 443`).

> Thank you very much for your guidance, if I must open another issue, please let me know.

It's really more of a Synology issue than an sslh issue, the
SNI probe works really well and is done exactly for that
purpose...
