### ISSUE TITLE
Segfault if no target host

### ISSUE THREAD

**Issue by rdebath** [yrutschle/sslh#129]
If the target host and port are omitted the 'verbose' flag is turned on `sslh` segfaults on startup.

I would expect omitting the "host" and "port" items to cause any connection that matches the current rule to be immediately closed ie: rejected.

**Comment by yrutschle** [comment]
I would expect omitting the host to cause startup to fail as it makes no sense.
I added the appropriate test and helpful message. Thanks for reporting!

**Comment by rdebath** [comment]
Of course it makes sense, if you give the connection nowhere to go it goes nowhere.

As to WHY you'd want to do it; I'm using the PCRE style regex below to send all SSLv2, SSLv3 and TLS connections that don't have the correct SNI names (previously matched) to nowhere. Well almost nowhere `sslh` complains that it can't connect and I can't tell it that that's what I want.

```
    # All TLS and SSL connections to fail.
    { name: "regex"; host: "localhost"; port: "1"; regex_patterns: [
        "^\x16\x03[^\x10-\xFF]..\x01\\x00..[\x03\x04]",
        "^[\x80-\x8f].\x01[\\x00\x03][^\x0F-\xFF]"
    ]; },
```

**Comment by yrutschle** [comment]
Oh right, sounds like a reasonable use case indeed :-)

I guess currently you could just target anything that has no
server behind it, but sslh will log errors.

I'd think the right way to do that would be to add an
explicit "drop" target somehow. Or do what you said and drop
connections with no targets silently. I'll think about it.
