### ISSUE TITLE
SSLH HTTP openssh protocol mismatch

### ISSUE THREAD

**Issue by NerdOfLinux** [yrutschle/sslh#131]
I have sslh listening on port 80 for OpenVPN, SSH, and HTTP. Whenever I go to load my site, I sometimes receive an error saying OpenSSH protocol mismatch.

**Comment by yrutschle** [comment]
On Fri, Jul 07, 2017 at 03:06:40AM +0000, NerdOfLinux wrote:
> I have sslh listening on port 80 for openvpn, ssh, and http. Whenever I go to load my site, I sometimes receive an error saying OpenSSH protocol mismatch.

We're going to need a wee bit more information, at least run
sslh with verbose and post an instance of that happening.
Ideally with a tcpdump of the corresponding traffic.

Meanwhile maybe try to increase the timeout in case your
browser is slow to send its request?

Y.

**Comment by NerdOfLinux** [comment]
I know it has been a while, but I fixed the issue from compiling the latest version, instead of the one provided by

```shell
sudo apt install sslh
```
