### ISSUE TITLE
Configuration option for syslog

### ISSUE THREAD

**Issue by rdebath** [yrutschle/sslh#132]
I would like the logging messages from sslh to go into the same "facility" (eg: local5) as some other messages so that the timing and sequence are correctly recorded to one syslog file.

Please can you add a configuration option for this.

**Comment by yrutschle** [comment]
I just pushed that.
Took me about 20 minutes to write the code, 2 days to figure out that rsyslog isn't working on my server, 10 minutes to test on another (identical) system, and the code was right first time. Now I have to find why I get no logs on some services on my server.

**Comment by yrutschle** [comment]
Hmmm it started logging again, and I don't know why. I have full confidence in my logs :/

**Comment by rdebath** [comment]
Humm, I wonder why it's working too, it shouldn't be ...

``` diff
--- sslh-1.18.orig/common.c
+++ sslh-1.18/common.c
@@ -654,7 +654,10 @@ void setup_syslog(const char* bin_name)
         exit(1);
     }

-    openlog(name2, LOG_CONS, fn);
+    if (verbose)
+        fprintf(stderr, "Facility %s is number %d\n", facility, fn);
+
+    openlog(name2, LOG_CONS, facilitynames[fn].c_val);
     free(name1);
     /* Don't free name2, as openlog(3) uses it (at least in glibc) */

```

**Comment by yrutschle** [comment]
On Sat, Jul 22, 2017 at 08:25:02AM +0000, rdebath wrote:
> Humm, I wonder why it's working too, it shouldn't be ...
> +    openlog(name2, LOG_CONS, facilitynames[fn].c_val);

Right, I guess I stopped at "oh, it logs somewhere else than
auth.log" and just got lucky the one I tested with had the
same c_val as index :-)

I pushed the fix, thanks for the quick feedback!

By "it's working", I meant rsyslogd started logging again
(it wasn't logging anything anywhere yesterday).
