### ISSUE TITLE
Transparent proxy only working for either IPv6 or IPv4

### ISSUE THREAD

**Issue by janh** [yrutschle/sslh#141]
I have been using sslh with the following configuration (and the corresponding iptables rules as described in the documentation) for some time now:
`--user sslh --transparent --listen :::443 --ssl ::1:4443 --openvpn ::1:1194`

This has been working for both IPv6 and IPv4 connection on Linux kernel 3.13, but after upgrading to 4.4, IPv4 connections no longer work. The output with option `-v` is:
```
accepted fd 4
**** writing deferred on fd -1
probing for ssl
connecting to localhost:4443 family 10 len 28
forward to ssl failed:connect: Address family not supported by protocol
connect: Address family not supported by protocol
```

It seems that sslh tries to connect with a IPv4-mapped IPv6 as source address, which no longer works on Linux since https://github.com/torvalds/linux/commit/ec5e3b0a1d41fbda0cc33a45bc9e54e91d9d12c7 (which is a reasonable check, my configuration should have never worked).

I looked again at the sslh documentation, and it says to use a name that resolves to an IPv4 and an IPv6 address to support both, so I added entries in /etc/hosts and changed the options to
`--user sslh --transparent --listen :::443 --ssl localaddr-sslh:4443 --openvpn localaddr-sslh:1194`

However, sslh still tries to connect to the the target service via IPv6 for incoming IPv4 connections. If I change the listen address to `0.0.0.0:443`, IPv4 connections work. Configuring sslh to listen both on `0.0.0.0:443` and `:::443` works when setting `net.ipv6.bindv6only=1`, but that would break the configuration of other services.

**Comment by pali** [comment]
Hi! Can you check if this patch https://github.com/yrutschle/sslh/pull/161 fixes your problem?

**Comment by janh** [comment]
Yes, with this patch I can configure sslh to listen to both IPv6 and IPv4 and everything works.

**Comment by yrutschle** [comment]
Patch merged, thanks to reporters and fixers.
