### ISSUE TITLE
Don't output 'set up keepalive' unless --verbose is used.

### ISSUE THREAD

**Issue by alainwolf** [yrutschle/sslh#152]
I use sslh with systemd.
`sslh.cfg` has set "`verbose: false;`" and "`foreground: true;`"
All listening ports and protocols are set to '`keepalive: true`'
This spams my syslog and systemd journal with 5 to 10 messages per second, which contain no usable information at all.
I managed to filter out the messages from syslog by routing them to `/var/log/sslh.log` and discarding them afterwards in rsyslogd configuration, but only to realize that they come from systemd to rsyslogd and not the other way round. I found no way to configure systemd to discard messages.
sslh should still be able to output meaningful information in case of problems,

Current workaround:
My systemd now starts a shell script instead of the binary which contains: 
`/usr/sbin/sslh -F /etc/sslh.cfg | /bin/grep --invert-match 'set up keepalive'`

**Comment by yrutschle** [comment]
Indeed -- these are really  debug messages left-over from during development, I don't think they are of any use. 6ca1ee7bfdc45cd96dca3f89b37f36870514de43 removes the messages.
