### ISSUE TITLE
How to forward client IP from sslh to nginx?

### ISSUE THREAD

**Issue by bynov** [yrutschle/sslh#155]
Hi,
When I use sslh for openvpn and ssl connection, I see local ip addresses in nginx access.log instead of real client IP. Is there any sslh config that allow forwarding client IP to nginx?

**Comment by Xiretza** [comment]
Yes, this is what the "transparent proxy" configuration is for. I personally haven't managed to get it to work yet, but you should try your luck anyway - instructions are in README.md

**Comment by kaasszje** [comment]
Perhaps some more info would be nice. Are sslh and nginx on the same server ?
(transparent proxy-ing only works on same host)

**Comment by yrutschle** [comment]
Closing this because of lack of answers on something that works for many.
