### ISSUE TITLE
webDAV support

### ISSUE THREAD

**Issue by Madgui** [yrutschle/sslh#156]
Hello guys,
I struggle to make a rule to manage webDAV connections, cold you help me ?
Thanks.

**Comment by yrutschle** [comment]
WebDAV is HTTP, just set up a HTTP connection and it should work. Or better, a TLS connection, otherwise your passwords will go unprotected over the Internet.

**Comment by Madgui** [comment]
Hi, thank you for your response !
I should have been more clear : I want to separate :
- https from 'regular' web server, and
- https from webdav server

**Comment by yrutschle** [comment]
On Mon, Dec 18, 2017 at 09:20:03AM +0000, Madgui wrote:
> - https from 'regular' web server, and
> - https from webdav server

I don't think there is any sane way to do that, most of the
time your WebDav application will expect normal HTTP to be
also available at the same address.
For example a concurrent file editor might follow a pattern
like this:
- HTTP GET the index
- HTTP GET the file
- User wants to edit
- HTTP/WebDAV LOCK the file
- [edit]
- HTTP PUT the file
- HTTP/WebDAV UNLOCK the file

I'm not completely sure this is right, but that's the idea:
WebDAV is not another protocol, it's really a larger
vocabulary to talk to a server about the same resources. So
splitting WebDAV from HTTP would effectively break the Web
application.

Something that would works is to have an HTTPS Web site on
one hand, and for example Owncloud (which works on HTTPS +
WebDAV) on the other hand, and separate using SNI, meaning
they have different URLs: https://www.example.net and
https://cloud.example.net (for example).

Hosting several Web applications that way works really well.

Y.

**Comment by Madgui** [comment]
Thank you, I will try to play a little more with the server that serve the webDav.

**Comment by Madgui** [comment]
I manage to build a workaround with a reverse proxy. Thanks a lot guys for your support !
