### ISSUE TITLE
systemd/systemd-sslh-generator: how to enable at boot?

### ISSUE THREAD

**Issue by X-dark** [yrutschle/sslh#171]
Maybe I am missing something about how systemd generators works but I cannot manage to make the generated sslh.socket unit start at boot. However it works fine when started manually.

**Comment by ChaosKid42** [comment]
Same problem here.

**Comment by Eeems** [comment]
https://unix.stackexchange.com/a/332797
It looks like you should be able to add a manual link to `/run/systemd/generator/sslh.socket` to a `*.target.wants` folder to get it to start on boot.

**Comment by X-dark** [comment]
Thank you. Indeed this works:

```bash
ln -s /run/systemd/generator/sslh.socket /etc/systemd/system/multi-user.target.wants/
```

**Comment by Eeems** [comment]
@X-dark Thanks for validating it, I've set it up on my server but I haven't had a chance to reboot to test.
