### ISSUE TITLE
Not working at all! Connections refused, no logging.

### ISSUE THREAD

**Issue by marcushat** [yrutschle/sslh#174]
So I'm running Ubuntu 14.04 on an EC2 micro instance and SSLH isn't accepting any connections. They all get refused and I see nothing about the failed incoming connections with verbose set to true. Here's my config:

```# This is a basic configuration file that should provide
# sensible values for "standard" setup.

verbose: true;
foreground: true;
inetd: false;
numeric: false;
transparent: false;
timeout: 5;
user: "root";
pidfile: "/var/run/sslh.pid";
chroot: "/var/empty";


# Change hostname with your external address name.
listen:
(
    { host: "PUBLIC_IP_HERE"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; keepalive: true; fork: true; probe: "builtin"; log_level: 1; },
     { name: "openvpn"; host: "localhost"; port: "1194"; probe: "builtin"; log_level: 1; },
     { name: "http"; host: "localhost"; port: "80"; probe: "builtin"; log_level: 1; },
     { name: "ssl"; host: "localhost"; port: "443"; probe: "builtin"; log_level: 1; },
     { name: "anyprot"; host: "localhost"; port: "443"; probe: "builtin"; log_level: 1; },
     { name: "regex"; host: "localhost"; port: "22"; regex_patterns: [ "" ]; log_level: 1; }
);

```

Here's how I installed it. 
```
#First I updated ports for ssh, apache, openvpn an verified they are listening. then...
apt-get -y install libwrap0-dev libconfig8-dev libpcre3-dev; cd /tmp; wget http://www.rutschle.net/tech/sslh/sslh-v1.19c.tar.gz; tar xvzf sslh-v1.19c.tar.gz; cd sslh-v1.19c; make install; cp sslh-fork /sbin/sslh; cp basic.cfg /etc/sslh.cfg; cp scripts/etc.init.d.sslh /etc/init.d/sslh; update-rc.d sslh defaults; chmod 777 /etc/sslh.cfg;
```

What am I doing wrong?

**Comment by yrutschle** [comment]
On Sun, May 20, 2018 at 12:20:08AM +0000, Marcus Leath wrote:
> What am I doing wrong?

You're not pasting the output of sslh when you run it :-)

**Comment by marcushat** [comment]
I get no errors, it just says it's running as normal but it just doesn't work. When I run it as verbose & foreground it doesn't output anything as I try to make connections. I also checked that the firewall wasn't blocking it and that all the other services are listening correctly on their respective ports.

**Comment by yrutschle** [comment]
Clearly it's not running "as normal". PLEASE DO paste:

- The output of sslh (all of it, not just what you think is
  "normal" or "error")

- The command you're using to test it, preferably with
  telnet or netcat running from the same machine

**Comment by yrutschle** [comment]
Closing this for lack information
