### ISSUE TITLE
Systemd service file wrong path

### ISSUE THREAD

**Issue by andrin55** [yrutschle/sslh#176]
Hello

The systemd service file had the wrong path for version 1.19c on Centos 7:
May 26 14:20:02 systemd[620]: Failed at step EXEC spawning /usr/bin/sslh: No such file or directory

[root@xx ~]# cat /usr/lib/systemd/system/sslh.service
[Unit]
Description=SSL/SSH multiplexer
Documentation=man:sslh(8)
After=network.target

[Service]
EnvironmentFile=/etc/sysconfig/sslh
ExecStart=/usr/bin/sslh $DAEMON_OPTS
KillMode=process
#Hardening
PrivateTmp=true
CapabilityBoundingSet=CAP_SETGID CAP_SETUID CAP_NET_BIND_SERVICE CAP_NET_ADMIN
ProtectSystem=full
ProtectHome=true
PrivateDevices=true

[Install]
WantedBy=multi-user.target

[root@xx ~]# /usr/bin/sslh
-bash: /usr/bin/sslh: No such file or directory

[root@xx ~]# whereis sslh
sslh: /usr/sbin/sslh /etc/sslh.cfg /usr/share/man/man8/sslh.8.gz

**Comment by yrutschle** [comment]
Agreed, this seems inconsistent with the `make install` setting of `/usr/sbin` which seems righter to me. Fixed in b8e63a4d9da061b90336a85f5936e8ceba09d5b2.
