### ISSUE TITLE
memory leak in bind_peer

### ISSUE THREAD

**Issue by lefturgen** [yrutschle/sslh#178]
You forgot to call freeifaddrs(ifaddrs_p); before "return" and after "if"

**Comment by yrutschle** [comment]
On Sun, May 27, 2018 at 02:56:04PM -0700, lefturgen wrote:
> You forgot to call freeifaddrs(ifaddrs_p); before "return" and after "if"

And after the for() loop. I need to see if this function can
be refactored cleanly, it's getting really ugly.

**Comment by yrutschle** [comment]
Here you go: 7acf9627ee138914393e2185ad9289619de3e0d1
This is refactored and I can't easily test it, please let me know if I broke something...
