### ISSUE TITLE
Support Telegram MTPRoto proxy

### ISSUE THREAD

**Issue by iShift** [yrutschle/sslh#179]
Hi it plz  add support for https://github.com/TelegramMessenger/MTProxy / https://hub.docker.com/r/telegrammessenger/proxy/ as protocol in  sslh, now in can works as other...

**Comment by yrutschle** [comment]
I had a quick look around and can't seem to see where/if the protocol is documented... do you know if it is described somewhere else than in the source code?

**Comment by yrutschle** [comment]
okay, looks complicated: my understanding is that you need to de-obfuscate first, then you could match on the auth_key_id if you specified it (e.g. in the configuration file), but then it means the proxy would only work with flows carrying your ID (I am not clear on whether that's a problem or not, as I don't know the architecture of Telegram)

**Comment by iShift** [comment]
All what need to do - if 2 or more packets have same first 8 bytes - it is telegram, if you make test version - i can test it

**Comment by yrutschle** [comment]
That's not what I take from the Susanka article:

> I've extracted my own auth_key_id and I expected to see it amongst the sniffed data. However, the whole traffic seemed random and therefore likely encrypted, and no sign of the expected structure was present.

**Comment by iShift** [comment]
it is not full true, i get article but it is in russian =( http://telegra.ph/telegram-blocks-wtf-05-26

I would be very aprisiate if you can install telegram with proxy and with wireshark dump them, also i can do it by myself and send you TCP dump

**Comment by yrutschle** [comment]
sure, you can send me a dump

**Comment by iShift** [comment]
Here it is, i use rule 
`host qvwpn.tgproxy.network` in wireshark 
qvwpn.tgproxy.network - it is one of MTRoto Proxy.

Plz say after you download dump, i want to remove them (or edit my message and delete file) 
(because of privacy)

[telegram_proxy_damp.pcapng.zip](https://github.com/yrutschle/sslh/files/2057710/telegram_proxy_damp.pcapng.zip)

**Comment by yrutschle** [comment]
'tis downloaded, edit away!

**Comment by iShift** [comment]
removed =) thank you!

**Comment by yrutschle** [comment]
ok, unless I'm mistaken I don't see tcp frames starting with the same number.

One way this might work is simply to specify your telegram proxy as the 'default' target for sslh (you can still use ssh and TLS as both have explicit probes).

**Comment by iShift** [comment]
default - is what i do for now, but i want native support, you don't want to see telegram in the service list of your app ?)

**Comment by yrutschle** [comment]
rather, I don't see an easy way to guess from an encrypted byte stream :-) I agree with the article you posted, they'd probably have been better using TLS with SNI or ALPN...

**Comment by iShift** [comment]
but why not to think, if packet is encrypted and have same first bytes as previous - it is telegram? 
so if you have telegram support turn on, sslh should:
look at packages and save first bytes to RAM (in table: IP:BYTES) if you have the same first bytes in new packet - it is telegram. Also clear cache table every N mins for performance...

**Comment by yrutschle** [comment]
because it does *not* have the same first bytes as previous -- that's what I see in the trace you sent me, anyway. Port 49472 connects to 8443 then sends something that starts with 0x7342 (sequence 7), then next frame starts with 0x81a0 (sequence 25): and even then, the server is sending a lot of data to the client, so we need to have connected the client to the server after the first frame (sequence 7).

Also, the beginning of the second connection (from port 49471) does not start with the same bytes either. I really think we'd need to run the entire un-obfuscation thingy to see anything.

**Comment by iShift** [comment]
Same first bytes, it is 1,2,10,42 packets (all in one session have same first bytes) i talk about where distention is telegram
![2018-05-31 23 33 35](https://user-images.githubusercontent.com/426427/40806755-1c589e2c-652b-11e8-899d-4941495e5038.png)
![2018-05-31 23 33 26](https://user-images.githubusercontent.com/426427/40806756-1c772676-652b-11e8-9bc4-8496f91449a9.png)
![2018-05-31 23 33 19](https://user-images.githubusercontent.com/426427/40806757-1c95dddc-652b-11e8-9dbc-15ced8c1dcfc.png)
![2018-05-31 23 33 13](https://user-images.githubusercontent.com/426427/40806758-1cb7b52e-652b-11e8-9e20-93b92b659ce1.png)

**Comment by iShift** [comment]
also if you think that it is hard to implement telegram proxy support - we can close issue 
Because i don't know C --> i can't make PR =)

**Comment by yrutschle** [comment]
Dude, that's the MAC address of your network interface :)
To see the data part of the frame, you need to select that 'Data' field in the middle window of Wireshark (not all frames have data as some only acknowledge previous data).

**Comment by iShift** [comment]
ahh, sorry 
![image](https://user-images.githubusercontent.com/426427/40808497-fa349918-652f-11e8-9de8-9ccda2487e58.png)

**Comment by lefturgen** [comment]
the main purpose of mtproto proxy is to obfuscate traffic and bypass DPI, if everything was so simple, then it would not make sense

**Comment by dm3ch** [comment]
Now telegram MTProxy had Fake TLS mode.

Currently as far as I know they provides `google.com` via SNI. So currently as I understood could be used simple SNI routing.
