### ISSUE TITLE
undefined reference to `CHECK_ALLOC'

### ISSUE THREAD

**Issue by candrews** [yrutschle/sslh#188]
With current master 108a9780 I'm getting this compilation error:
```
x86_64-pc-linux-gnu-gcc -O2 -march=native -pipe -fuse-linker-plugin -flto -std=gnu99 -Wl,-O1 -Wl,--as-needed -flto -o echosrv echosrv.o probe.o common.o tls.o  -lpcreposix -lconfig -lcap -lsystemd
/var/tmp/portage/net-misc/sslh-9999/temp/ccngimUp.ltrans0.ltrans.o: In function `resolve_listen':
<artificial>:(.text+0x34): undefined reference to `CHECK_ALLOC'
/var/tmp/portage/net-misc/sslh-9999/temp/ccngimUp.ltrans0.ltrans.o: In function `main':
<artificial>:(.text.startup+0xe5): undefined reference to `CHECK_ALLOC'
<artificial>:(.text.startup+0x1dd): undefined reference to `CHECK_ALLOC'
<artificial>:(.text.startup+0x25d): undefined reference to `CHECK_ALLOC'
collect2: error: ld returned 1 exit status
make: *** [Makefile:84: systemd-sslh-generator] Error 1
make: *** Waiting for unfinished jobs....
sslh-main.c: In function ‘setup_sni_alpn_list.isra.0’:
sslh-main.c:266:25: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     sni_hostname_list = calloc(num_probes + 1, ++max_server_name_len);
                         ^
/usr/include/stdlib.h:541:14: note: in a call to allocation function ‘calloc’ declared here
 extern void *calloc (size_t __nmemb, size_t __size)
              ^
#strip sslh-select
sslh-main.c: In function ‘setup_sni_alpn_list.isra.0’:
sslh-main.c:266:25: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
     sni_hostname_list = calloc(num_probes + 1, ++max_server_name_len);
                         ^
/usr/include/stdlib.h:541:14: note: in a call to allocation function ‘calloc’ declared here
 extern void *calloc (size_t __nmemb, size_t __size)
              ^
#strip sslh-fork

```

**Comment by yrutschle** [comment]
On Mon, Jun 18, 2018 at 09:29:53AM -0700, Craig Andrews wrote:
> <artificial>:(.text+0x34): undefined reference to `CHECK_ALLOC'

It's a macro defined in common.h, just like CHECK_RES_DIE
and some others that are used throughout the code... 
You shouldn't see it in the symbols of the object:
$ nm sslh-main.o
=> list of symbols, should not contain CHECK_ALLOC.

> sslh-main.c: In function ‘setup_sni_alpn_list.isra.0’:
> sslh-main.c:266:25: warning: argument 1 range [18446744071562067969, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
>      sni_hostname_list = calloc(num_probes + 1, ++max_server_name_len);

I'm curious as to which compiler is giving you this kind of
warning. Is it computing the parameters through static
analysis?

**Comment by candrews** [comment]
> I'm curious as to which compiler is giving you this kind of warning. Is it computing the parameters through static analysis?

I don't think it's anything exciting... I'm on Gentoo using `gcc (Gentoo 8.1.0-r3 p1.3) 8.1.0`

**Comment by kensington** [comment]
Is it caused by LTO?

**Comment by candrews** [comment]
I figured out the problem and submitted a PR fixing it: https://github.com/yrutschle/sslh/pull/192
