### ISSUE TITLE
Probes that require more data are blocking other probes until enough data is received

### ISSUE THREAD

**Issue by shadowlmd** [yrutschle/sslh#194]
Today I've found an issue where probes that require more data and returning PROBE_AGAIN are blocking subsequent probes from even trying to do the job. I couldn't find a good way to fix this so I did it a hackish way in my fork: https://github.com/shadowlmd/sslh/commit/b4d7465f7749927dd0e3578c91149ccad8d9bee0. Not suggesting to port it here, but it may give some idea on how to fix this properly.

It is easy to reproduce the bug. Just add socks5 probe before http or tls and then socks5 client offering only 1 auth method (i.e. Telegram) will not be able to connect at all.

**Comment by shadowlmd** [comment]
I fixed remaining bugs in my own "fix" for this issue, final version is https://github.com/shadowlmd/sslh/commit/a8bd131f71efd4659b73b81ddbae378f6bc65493. It turned out that I was always probing last protocol starting from second iteration of `probe_client_protocol()`. So I had to add more ugly code to stop that from happening. Still this is all very bad and I believe whole thing needs to be rewritten to work properly. Best approach would be to rebuild probe chain removing probes that returned PROBE_NEXT, so only probes that returned PROBE_AGAIN are tried on next iteration.

**Comment by yrutschle** [comment]
Yes, the logic seems wrong indeed, we need to try all probes even if some return PROBE_AGAIN (other probes might match). I'm not sure why you're treating the timeout and anyprot protocols separately in your patch?

**Comment by shadowlmd** [comment]
I am treating them separately because they always return PROBE_MATCH, and since we skipping all probes that returned PROBE_AGAIN instead of breaking the loop, like it was done originally, anyprot or timeout probes will match on the first go and there will never be second chance for probes that returned PROBE_AGAIN.

But I guess this ugly code can be optimized now that I added `again` var, I'll probably do that, thanks for the hint. :)

**Comment by yrutschle** [comment]
Yes, I understood that while watering the garden -- sorry, I should always water the garden before asking questions :)

**Comment by yrutschle** [comment]
should be fixed in 677e385fec445987e76da9270a982bdf3d909a92, too.

**Comment by shadowlmd** [comment]
Hello,

I did some quick testing and it looks very good. Thank you very much.

The only issue I've just though about is that regex probe can fail for some people after these changes. It fails after the first attempt to match anything, so now it will fail on the first byte because all other probes will allow regex to actually probe the data. I believe the only proper way to resolve this is to add some additional parameters to regex probe like "min_bytes" and "max_bytes" so it would return PROBE_AGAIN when too few bytes was read or pattern didn't match and PROBE_NEXT when more than max_bytes was read.

**Comment by yrutschle** [comment]
On Mon, Aug 13, 2018 at 05:58:00PM -0700, Vasya Pupkin wrote:
> The only issue I've just though about is that regex probe
> can fail for some people after these changes. It fails
> after the first attempt to match anything, so now it will
> fail on the first byte because all other probes will allow
> regex to actually probe the data.

Yes, we'll have that problem for all probes that don't have
a clear notion of first message size, e.g. http: an http
request could range from 10 bytes to kilobytes, with the
protocol marker actually at the *end* of that...


> I believe the only proper way to resolve this is to add
> some additional parameters to regex probe like "min_bytes"
> and "max_bytes" so it would return PROBE_AGAIN when too
> few bytes was read or pattern didn't match and PROBE_NEXT
> when more than max_bytes was read.

That might be the solution I was missing, it'd work for HTTP
as well (where a specific site administrator would have an
idea of the request size, based on domain name length and
path lengths...). I'll think about it some more :-)

**Comment by shadowlmd** [comment]
Did you notice the update part of my reply?

**Comment by yrutschle** [comment]
No -- github apparently doesn't send e-mails on edits of past posts.

I'm fixing the uninitialised variable differently. I can't remember why this line is here, I don't think the `probe` field is ever supposed to be empty.

As for the managing the errors for `read`, thanks -- I had a vague feeling there was something wrong there, and this sort of issues can take a long time to be found. I've added a test for errno == EAGAIN which is a legitimate error that doesn't mean the connection is down.

**Comment by shadowlmd** [comment]
Thanks a lot, now everything is perfect. I believe, this issue may be closed but I'll leave it up to you.

**Comment by yrutschle** [comment]
Ok closing this and opening a new one for the option feature request (https://github.com/yrutschle/sslh/issues/198)

**Comment by yrutschle** [comment]
@shadowlmd FYI I've just pushed code for a `minlength` option; no `maxlength` option for reasons explained [here](https://github.com/yrutschle/sslh/issues/198)
