### ISSUE TITLE
Can you give instruction for windows?

### ISSUE THREAD

**Issue by ghost** [yrutschle/sslh#196]

**Comment by yrutschle** [comment]
Not really, I don't know much about Windows.

 It's been done before using Cygwin, and you can download those versions from the download page (http://rutschle.net/tech/sslh/download.html). You can also ask the question on the mailing list, where the person who compiled for Windows may or may not answer. I think compiling on Cygwin is pretty similar to compiling on GNU/Linux, the only caveat is to use sslh-select rather than sslh-fork (Unix and Windows have a very different approach to multi-processing so sslh-fork works but has horrible performance on Windows).

Either way, I'm happy to integrate instructions to the README, should you manage to build it :-)

**Comment by GooG2e** [comment]
@JessePinkman2802 have you compiled windows version?
I have tried to use existing version but fork and select give the same result and have a lot cpu usage

**Comment by CE1CECL** [comment]
> Not really, I don't know much about Windows.
> 
> It's been done before using Cygwin, and you can download those versions from the download page (http://rutschle.net/tech/sslh/download.html). You can also ask the question on the mailing list, where the person who compiled for Windows may or may not answer. I think compiling on Cygwin is pretty similar to compiling on GNU/Linux, the only caveat is to use sslh-select rather than sslh-fork (Unix and Windows have a very different approach to multi-processing so sslh-fork works but has horrible performance on Windows).
> 
> Either way, I'm happy to integrate instructions to the README, should you manage to build it :-)

I managed to build it using CygWin, how do I add it to your instructions?

**Comment by lerenardo** [comment]
Hello, me too. I even scripted it !
How to add the files ?

**Comment by CE1CECL** [comment]
> Hello, me too. I even scripted it ! How to add the files ?

I'll make a PR to use the version of Cygwin I used, for down to Vista x86, but I had to use the tarball, I couldn't use the Git version. I'll also share my binaries sometime

**Comment by lerenardo** [comment]
Here is what i've done.
The script downloads the latest cygwin, the latest version of sslh, and then compiles and copies the binaries with dependancies to an output folder.

It may be needed to correct it from time to time, but it works. I use it in a virtual machine.
Just retrieve WGET.EXE from [https://eternallybored.org/misc/wget/](url) or git binaries.

Copy the 3 files

	GO.cmd
	wget.exe
	compile.sh
	
to C root folder, then execute **GO.cmd** with administrative rights.

with **GO.cmd**

	@ECHO OFF
	CD /D "%~dp0"
	
	NET SESSION >NUL 2>&1
	IF %ERRORLEVEL% NEQ 0 (
	    ECHO Permission denied. This script must be run as an Administrator.
	    ECHO:
	    GOTO FIN
	) ELSE (
	    ECHO Running as Administrator.
	    TIMEOUT /T 2 >NUL
		wget --no-check-certificate https://www.cygwin.com/setup-x86_64.exe
		IF NOT EXIST setup-x86_64.exe GOTO FIN
		MKDIR C:\Z
		setup-x86_64.exe -l C:\Z -s ftp://ftp.funet.fi/pub/mirrors/sourceware.org/pub/cygwin/ -q -P make -P git -P gcc-g++ -P autoconf -P automake -P libtool -P libpcre-devel -P libpcre2-devel -P bison -P libev-devel
		MKDIR C:\cygwin64\home\user
	COPY COMPILE.SH C:\cygwin64\home\user
			START C:\cygwin64\bin\mintty.exe /bin/bash --login -i ~/compile.sh
		START EXPLORER C:\zzSORTIE
	)
	:FIN
	PAUSE
	EXIT


and **compile.sh**

	# SAVE FILE TO UNIX FORMAT
	# COPY IT IN C cygwin64 home user
	git clone https://github.com/hyperrealm/libconfig.git
	cd libconfig
	autoreconf -fi
	./configure
	make
	make install
	cd ..
	cp /usr/local/lib/libconfig.* /usr/lib
	git clone https://github.com/yrutschle/sslh.git
	cd sslh
	make
	cd ..
	mkdir /cygdrive/c/zzSORTIE
	cp ./sslh/sslh*.exe /cygdrive/c/zzSORTIE
	cp /usr/local/bin/cygconfig-11.dll /cygdrive/c/zzSORTIE
	cp /cygdrive/c/cygwin64/bin/cygwin1.dll /cygdrive/c/zzSORTIE
	cp /cygdrive/c/cygwin64/bin/cygpcreposix-0.dll /cygdrive/c/zzSORTIE
	cp /cygdrive/c/cygwin64/bin/cygpcre-1.dll /cygdrive/c/zzSORTIE
	cp /cygdrive/c/cygwin64/bin/cygev-4.dll /cygdrive/c/zzSORTIE
	cp /cygdrive/c/cygwin64/bin/cygpcre2-8-0.dll /cygdrive/c/zzSORTIE

Hope it will help some people using Windows !

**Comment by nono303** [comment]
Many Thx @lerenardo

I've just added it into my build chain https://github.com/nono303/win-build-scripts/commit/e47a7388589559d4b720fdabe9811173f9a11040

And as I used to provided Windows Cygwin binaries by mail, I've just created a repo https://github.com/nono303/sslh were I'll tag release for an easiest download (...like I do it for Memcached https://www.apachelounge.com/viewtopic.php?t=7919)
@yrutschle  you can reference my repo if you want on https://github.com/yrutschle/sslh/blob/master/doc/INSTALL.md and https://www.rutschle.net/tech/sslh/download.html.
And don't hesitate to make PR on https://github.com/nono303/sslh/blob/main/README.md if you want to add some instructions about specific Windows consideration (like which is the better version to use)

Arnaud

**Comment by yrutschle** [comment]
This is all excellent, thanks to all involved :-)
@nono303 it used to be sslh-select was better (the forking model really doesn't sit well with Windows), can you confirm sslh-ev works as well? In that case, I guess that would be the prefered solution, as it's supposed to make better use of the native OS mechanisms.

**Comment by nono303** [comment]
U're welcome! 
I used to run the select version with 1.2x but switched to ev since 2.x and it's still working like a charm.
If you have some tips or tests to qualify performance and reliability, just tell me, I’ll do the job.

**Comment by yrutschle** [comment]
@lerenardo 's instructions and @nono303 's repository now commented in 90a55b6f9dba84e7345c707b7563c428d79139de. I consider this closed, but please re-open if I forgot something! :)
