### ISSUE TITLE
Add 'min_bytes' and 'max_bytes' options to probes that don't know how much data they need

### ISSUE THREAD

**Issue by yrutschle** [yrutschle/sslh#198]
add some additional parameters to regex probe like "min_bytes" and "max_bytes" so it would return PROBE_AGAIN when too few bytes was read or pattern didn't match and PROBE_NEXT when more than max_bytes was read

(related to https://github.com/yrutschle/sslh/issues/194)

**Comment by yrutschle** [comment]
Considering there seems to be a need for more abstract option support, I'll see about refactoring the whole option system (we have generic options that are always available e.g. `fork` and `keepalive` and probe-specific options e.g. upcoming `min_bytes`, `sni_hostnames`)

**Comment by yrutschle** [comment]
Added `minlength` in a7b4462c6e60f03ea020c3f8ad273cdef6caf1fe.
`maxlength` turns out to be a bad idea, as it'll match unpredictably depending on the underlying network traffic, e.g. if a regex is set to match `^foo` with `maxlength: 8` and I received `foo1234567`, the probe will fail, but if there was network lag and I only received `foo12` so far, it'll match.

**Comment by shadowlmd** [comment]
Thanks! Regarding maxlength, I suggested it to work a bit different. It should return PROBE_NEXT only if maxlenght bytes were read AND didn't match the pattern. The fact that more bytes were read should never trigger probe as failed. Without maxlength probe would keep returning PROBE_AGAIN with every new chunk of incoming data which may lead to 100% CPU usage in some scenarios. So the idead was to try matching until we have enough data (maxlength), i.e. we want 8 bytes, we read 12 bytes, we try matching and return either PROBE_MATCH (if it matched the pattern) or PROBE_NEXT.
