### ISSUE TITLE
core dump in is_tls_protocol

### ISSUE THREAD

**Issue by candrews** [yrutschle/sslh#202]
Stack trace:
```
Stack trace of thread 2216:
#0  0x000055cb91b50e94 is_tls_protocol (sslh-fork)
#1  0x000055cb91b52a99 probe_client_protocol (sslh-fork)
#2  0x000055cb91b5302a start_shoveler (sslh-fork)
#3  0x000055cb91b50231 main (sslh-fork)
#4  0x00007f2e414b146b __libc_start_main (libc.so.6)
#5  0x000055cb91b5085a _start (sslh-fork)
```

This new crash does not occur with e8f0d3ea530c3c9718992b4aac0075aef9db603c and does occur with 6431bb7e35087ea2012738062b224d1631c5f44e

**Comment by yrutschle** [comment]
On Mon, Sep 24, 2018 at 03:48:47PM +0000, Craig Andrews wrote:
> #0  0x000055cb91b50e94 is_tls_protocol (sslh-fork)

The only pointer derefence there is on `proto`, which I
didn't think I changed... Could you post your configuration
file?

That's assuming the crash happens every time which suggests
an issue with the configuration code. It's not intermittent,
is it?

**Comment by candrews** [comment]
It happens every time - it is not intermittent. Here's /etc/sslh/sslh.cfg:
```
# This is a basic configuration file that should provide
# sensible values for "standard" setup.

verbose: false;
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh.pid";

# Change hostname with your external address name.
listen:
(
    { host: "localhost"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; },
     { name: "xmpp"; host: "localhost"; port: "5222"; },
     { name: "http"; host: "localhost"; port: "80"; },
     { name: "ssl"; host: "localhost"; port: "8443"; log_level: 0; },
);
```

**Comment by yrutschle** [comment]
On Tue, Sep 25, 2018 at 02:12:09PM +0000, Craig Andrews wrote:
>      { name: "ssl"; host: "localhost"; port: "8443"; log_level: 0; },

How about `name: "tls"` ?

I  might very well have broken that one, and there is no
automated test for it... I'm torn between adding a wart to
turn it to "tls" or just make it obsolete. Either way, it
should produce a proper error message, not a core dump, so
that's my bad...

**Comment by candrews** [comment]
Using `name: "tls"` instead of `name: "ssl"` causes sslh to work and not core dump. Thanks!

**Comment by yrutschle** [comment]
Ok, we're now turning 'ssl' to 'tls' and warn the user that the 'ssl' setting will disappear later.
