### ISSUE TITLE
Port 443 appears as closed

### ISSUE THREAD

**Issue by herrwusel** [yrutschle/sslh#204]
Hi,
I'm trying to following [this guide](https://wiki.debian.org/InstallingProsody#XMPP_over_HTTPS) and it's not working for me.
It seems that the port 443 is closed. So I thought it is the router's fault (there is a forwarding rule but you never know) but when I checked inside the network, I got this:

> nmap 192.168.178.101 -p443
>
>Starting Nmap 7.60 ( https://nmap.org ) at 2018-10-09 09:18 CEST
>Nmap scan report for pihole (192.168.178.101)
>Host is up (0.026s latency).
>
>PORT    STATE  SERVICE
>443/tcp closed https
>
>Nmap done: 1 IP address (1 host up) scanned in 0.23 seconds

Should the port be reachable? I'm not saying that in my set up it is sslh that is causing problems - I just want to figure out what I did wrong.

**Comment by yrutschle** [comment]
Yes the port should be reachable. Either you have a firewall
between your client (running nmap) and your server that
blocks 443 entirely, or you don't in fact have a server
listening on 443 (i.e. sslh wasn't started).

You can see what processes are listening with:

 netstat -ltp

(as root), which on my server returns:

 tcp        0      0 hood.rutschle.net:https 0.0.0.0:* LISTEN      5212/./sslh-select

=> sslh-select is listening on port 443 as PID 5212.

**Comment by herrwusel** [comment]
I forgot to provide this info:

> netstat -tuplen
> tcp        0      0 >outsideIP>:443      0.0.0.0:*               LISTEN      0          1239986    15395/sslh

So it is listening. Nmap on the host itself tells me 443 is open. Might be still my router than.

**Comment by yrutschle** [comment]
Yes, if you're on a typical home setup with a home ADSL
router, you need to set it up to open the port and forward
it to the appropriate IP inside your home network.

**Comment by herrwusel** [comment]
All of these forwardings are working - only 443 is not reachable. Is a router blocking ports inside of home network as well? 
![screenshot_20181009_100422](https://user-images.githubusercontent.com/8242787/46655173-18293500-cbab-11e8-9cc3-92a40ec3dec7.png)

**Comment by herrwusel** [comment]
I think it sslh which is not properly configured. I did stop sslh, brought back the old nginx config and nmap is showing that 443 is open now.

**Comment by herrwusel** [comment]
I think I figured it out:
I set host to my domain which sets sslh listen to the external IP. Setting sslh to listen to the system's local IP made it working. Correct me if I'm wrong but setting host to a domain is only applicable if your system isn't in a home network.
