### ISSUE TITLE
sslh 1.19c does not start 

### ISSUE THREAD

**Issue by fvalenduc** [yrutschle/sslh#208]
sslh 1.19c does not start. It fails within this error:

 sslh[4655]: common.c:764:setgid : Operation not permitted

I am using gentoo. Any idea on what's happening? I downgraded to version 1.18 and it is working again.

**Comment by yrutschle** [comment]
I would guess you are running sslh as a non-root user but
asking to change to another user, which it cannot do.

**Comment by fvalenduc** [comment]
I start sslh via systemd. The options passed at startup are:
-p 0.0.0.0:443 --timeout 5  --ssh 127.0.0.1:22  --ssl 127.0.0.1:2443 --openvpn 127.0.0.1:1194 --user nobody

With version 1.18 it works, with 1.19c, it does not.

**Comment by yrutschle** [comment]
Does this work if you run it from the console as root?

If systemd starts sslh as a restricted user or with limited
capabilities, setgid() might fail.

**Comment by yrutschle** [comment]
Quite a bit has changed in the privilege dropping code; I can't see why it would affect your specific issue, but that was a long time ago.

I don't know much about systemd, but your solution worries me a bit: does it mean sslh is running as root at the end? Or does sslh still change to another user afterwards?

**Comment by fvalenduc** [comment]
sslh runs as user nobody. Here an extract of ps |aux:
nobody    9964  0.0  0.0  40812  3012 ?        Ss   15:23   0:00 /usr/sbin/sslh --foreground -p 0.0.0.0 443 --timeout 5 --ssh 127.0.0.1 22 --ssl 127.0.0.1 2443 --openvpn 127.0.0.1 1194 --user nobody
nobody    9965  0.0  0.0  40812   308 ?        S    15:23   0:00 /usr/sbin/sslh --foreground -p 0.0.0.0 443 --timeout 5 --ssh 127.0.0.1 22 --ssl 127.0.0.1 2443 --openvpn 127.0.0.1 1194 --user nobody

**Comment by yrutschle** [comment]
Oh, reading through the discussion again that's what's happening: you asked systemd to start sslh as root, then sslh to change as nobody. This is fine, but not the only possible setup: system can start sslh as nobody with cap_netadmin, and sslh then doesn't need to change user (simply by not specifying it)

**Comment by yrutschle** [comment]
ah, the systemd.sslh.service file actually already specifies CAP_NET_BIND_SERVICE which should be fine. Can you not simply add:
```
User=nobody
```
to the systemd script?

**Comment by fvalenduc** [comment]
Indeed it works, but it seems to be needed, at least in gentoo. I don't know with which user it tries to start otherwise, but it doens't want to change to nobody.

**Comment by yrutschle** [comment]
As I understand it, that may be specified somewhere in /etc/systemd:
```
find /etc/systemd -type f | xarg grep "^User"
```
(I don't see anything like this on Debian)

**Comment by WPettersson** [comment]
I had this issue today. The Gentoo package includes a sample /etc/conf.d/sslh file which essentially contains just command line options for sslh. This example includes "--user nobody", even for sslh versions 1.19c and above, so anyone who uses the Gentoo example config, and systemd, will have this issue. The quick fix is to remove "--user nobody" from /etc/conf.d/sslh.

In short, though, I'm confident this is purely a Gentoo issue, and I'll try to get the example config file that Gentoo ships to include sample options specifically for systemd.

**Comment by yrutschle** [comment]
I'm happy to integrate submission scripts, but it might be worth taking it up with the Gentoo maintainer as well. Thanks for the feedback, anyhow.
