### ISSUE TITLE
[Q] multiple sslh instances

### ISSUE THREAD

**Issue by kcris** [yrutschle/sslh#212]
Hi,
is it possible to run multiple instances of sslh at the same time? Listening on different ports?
what is the syntax for this?
thanks

**Comment by yrutschle** [comment]
That's not even a challenge, just run two instances with their own configuration:
./sslh-select -Fconf1.cfg
./sslh-select -Fconf2.cfg

and voilà!

**Comment by kcris** [comment]
I was sure there is a way, I wasn't sure if I can do it in the same config or not :)
thanks a lot

**Comment by yrutschle** [comment]
I was thinking just a few days ago that the new configuration scheme would make it pretty easy to do 2 independant configs in the same configuration file... I don't think there is much point though, we'd get slightly more complex code, no improvement of performance, maybe a slightly smaller memory usage, and arguably lower security in the case of sslh-select (as all configurations would share the same address space... unless you fork for each configuration, but that's pretty much the same as running two entirely different instances).
