### ISSUE TITLE
"make" doesn't work

### ISSUE THREAD

**Issue by Shark201** [yrutschle/sslh#214]
Centos 7 and Ubuntu 16.04 X86 64
"make install" doesn't work  :(

`-bash-4.2# make
./genver.sh >version.h
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
make: cc: Command not found
make: *** [sslh-conf.o] Error 127
`

**Comment by yrutschle** [comment]
Maybe you'll prefer to install the pre-packaged versions... Make does not find a C compiler, so you need one (and, you'll need a variety of headers, libraries and other things if you want to compile from source)
