### ISSUE TITLE
transparent mode work when run as root, but failed when run as sslh-(common.c:229:setsockopt: Operation not permitted)

### ISSUE THREAD

**Issue by whiledone** [yrutschle/sslh#217]
[root@xxx~]# getcap /usr/sbin/sslh
/usr/sbin/sslh = cap_net_bind_service,cap_net_admin+ep

[root@xxxx~]# /usr/sbin/sslh -F /etc/sslh.cfg
verbose: 0
foreground: 1
inetd: 0
numeric: [0](url)
transparent: 1
timeout: 10
user: sslh
pidfile: /var/run/sslh.pid
chroot: /var/empty
syslog_facility: auth
on_timeout: ssh
listen [1]:
    host: 10.21.211.79
    port: 18443
    keepalive: 0
protocols [2]:
    name: http
    host: 10.21.211.79
    port: 80
    service: (null)
    fork: 0
    log_level: 0
    keepalive: 0
    sni_hostnames [0]:
    alpn_protocols [0]:
    regex_patterns [0]:
    name: ssl
    host: 10.21.211.79
    port: 443
    service: (null)
    fork: 0
    log_level: 0
    keepalive: 0
    sni_hostnames [0]:
    alpn_protocols [0]:
    regex_patterns [0]:
sslh-fork head-2019-01-19 started
common.c:229:common.c:229:setsockopt: Operation not permitted
setsockopt: Operation not permitted
common.c:229:setsockopt: Operation not permitted

**Comment by yrutschle** [comment]
Can you run it with verbose: 1 and report the output? (I'd wonder if the capabilities got passed properly)

**Comment by whiledone** [comment]
verbose: 1
foreground: 1
inetd: 0
numeric: 0
transparent: 1
timeout: 10
user: sslh
pidfile: /var/run/sslh.pid
chroot: /var/empty1
syslog_facility: auth
on_timeout: ssh
listen [1]:
    host: 10.21.211.79
    port: 18443
    keepalive: 0
protocols [2]:
    name: http
    host: 10.21.211.79
    port: 80
    service: (null)
    fork: 0
    log_level: 0
    keepalive: 0
    sni_hostnames [0]:
    alpn_protocols [0]:
    regex_patterns [0]:
    name: ssl
    host: 10.21.211.79
    port: 443
    service: (null)
    fork: 0
    log_level: 0
    keepalive: 0
    sni_hostnames [0]:
    alpn_protocols [0]:
    regex_patterns [0]:
http addr: SZX1000440980:http. libwrap service: (null) log_level: 0 family 2 2 [] []
ssl addr: SZX1000440980:https. libwrap service: (null) log_level: 0 family 2 2 [] []
listening on:
        SZX1000440980:18443     []
timeout: 10
on-timeout: http
listening to 1 addresses
sslh-fork head-2019-01-19 started
turning into sslh
chrooting into /var/empty1
accepted fd 4
accepted fd 4
**** writing deferred on fd -1
probing for http
probed for http: PROBE_NEXT
probing for ssl
probed for ssl: PROBE_MATCH
connecting to 10.21.211.79:443 family 2 len 16
common.c:229:setsockopt: Operation not permitted
**** writing deferred on fd -1
probing for http
probed for http: PROBE_NEXT
probing for ssl
probed for ssl: PROBE_MATCH
connecting to 10.21.211.79:443 family 2 len 16
common.c:229:setsockopt: Operation not permitted
accepted fd 4
**** writing deferred on fd -1
probing for http
probed for http: PROBE_NEXT
probing for ssl
probed for ssl: PROBE_MATCH
connecting to 10.21.211.79:443 family 2 len 16
common.c:229:setsockopt: Operation not permitted

**Comment by yrutschle** [comment]
`sslh` does not print the capabilities it has, which it should, which suggest you didn't compile with LIBCONFIG=1.

**Comment by whiledone** [comment]
# Configuration

VERSION=$(shell ./genver.sh -r)
ENABLE_REGEX=1  # Enable regex probes
USELIBCONFIG=1  # Use libconfig? (necessary to use configuration files)
USELIBPCRE=1    # Use libpcre? (needed for regex on musl)
USELIBWRAP?=    # Use libwrap?
USELIBCAP=      # Use libcap?
USESYSTEMD=     # Make use of systemd socket activation
COV_TEST=       # Perform test coverage?
PREFIX?=/usr
BINDIR?=$(PREFIX)/sbin
MANDIR?=$(PREFIX)/share/man/man8

this is my makefile, Doe you mean I should delete USELIBCONFIG=1 ?

**Comment by yrutschle** [comment]
Sorry, I meant USELIBCAP!

**Comment by yrutschle** [comment]
Closing due to lack of response. Reopen if the suggested fix didn't work.
