### ISSUE TITLE
raspberry pi segmentation fault

### ISSUE THREAD

**Issue by epilsits** [yrutschle/sslh#220]
Building from 7baf7f724c2ef689af4bdf864293a36536f49686 on raspberry pi results in a partially working binary. I can run commands such as `sslh -h` to get command help, and `make test` runs to completion, but when trying to run the app for real, the following example command line results in a segmentation fault.

`sslh -f -t 5 --ssh 127.0.0.1:22 --listen 127.0.0.1:23456`

I ran with verbose output as well but did not get any more helpful output.

I successfully compiled and ran the last release version 1.20 from 4ae2e62d25b9faf984a303c4bdf2b7675f4988b9 .

**Comment by yrutschle** [comment]
I think that has nothing to do with rapberry pi, but there was a bug in conf2struct if no configuration file was specified. Should be fixed in 5a213c96506e79acace9eaeee736945dc00bab3d
