### ISSUE TITLE
Error when forwarding TLS traffic

### ISSUE THREAD

**Issue by epilsits** [yrutschle/sslh#222]
@yrutschle thank you for helping on #220, I can successfully compile now. However there is some other error when forwarding TLS traffic, ie stunnel. This is the most I can log with a verbose level of 99.

```
probing for ssh
probed for ssh: PROBE_NEXT
probing for tls
probed for tls: PROBE_MATCH
connecting to 0.0.0.1:48686 family 2 len 16
forward to tls failed:connect: Invalid argument
sslh-fork.c:110:connect: Invalid argument
```

I think there is something wrong with the address/port binding. My command line (not using config file) has `--tls 127.0.0.1:48686`, but the startup log shows
```
name: tls
    host: 1
    port: 48686
    service: (null)
    fork: 0
    log_level: 1
    keepalive: 0
    sni_hostnames [0]:
    alpn_protocols [0]:
    regex_patterns [0]:
    minlength: 0
```

and finally `tls addr: 0.0.0.1:48686. libwrap service: (null) log_level: 1 family 2 2 [] []`

The log from v1.20 looks more like this.
```
tls addr: localhost:48686. libwrap service: (null) log_level: 1 family 2 2 [] []
...
probing for ssh: PROBE_NEXT
probing for openvpn: PROBE_NEXT
probing for tls: PROBE_MATCH
connecting to localhost:48686 family 2 len 16
tls:connection from <src> to <dest> forwarded from localhost:34612 to localhost:48686
```

Let me know what else you need.

**Comment by epilsits** [comment]
The latest commit for the regex matching seems to have fixed the issue. Thank you!

**Comment by yrutschle** [comment]
Excellent :)
