### ISSUE TITLE
"--listen [::]:443: Illegal argument"

### ISSUE THREAD

**Issue by candrews** [yrutschle/sslh#223]
Using current master:
```
# sslh -p [::]:443 -p 0.0.0.0:443 --tls 127.0.0.1:8443 --ssh 127.0.0.1:22
--listen [::]:443: Illegal argument
```
This same command works fine on 1.20.

**Comment by yrutschle** [comment]
Yes... e528f519bc51916615c47f6f9fcbedae36922b08 should do it. I'm surprised no-one has complained earlier, `localhost` is about the only useful thing that would work...
