### ISSUE TITLE
 Does it work with Wireguard ?

### ISSUE THREAD

**Issue by BedoM** [yrutschle/sslh#226]
Hello

 Does it work with Wireguard ?

Do you have a config for ? 

thank's !

**Comment by yrutschle** [comment]
My understanding is that Wireguard's transport is UDP, so no, that can't work.

**Comment by maddes-b** [comment]
Can the new v1.22 with UDP support now support Wireguard?

**Comment by yrutschle** [comment]
My understanding from [this](https://www.wireguard.com/protocol/#first-message-initiator-to-responder) is that a regex like this:
```
\x01\x00\x00\x00
```
should work -- message type 1, reserved zero over three bytes.
