### ISSUE TITLE
Don't output `Transport endpoint is not connected` unless Verbose is used

### ISSUE THREAD

**Issue by licaon-kter** [yrutschle/sslh#227]
sslh-fork v1.20-30-g5684959

Full message outputted to both syslog and daemon.log hundred times/second even for `Verbose: 0`:
`common.c:431:read:107:Transport endpoint is not connected`

Triggered by:
* set up an endpoint without a listener or
* kill listeners before sslh (eg. stop nginx; stop sslh -> a sslh process still lives, `systemctl stop sslh` does nothing-> storage gets filled)

**Comment by yrutschle** [comment]
That may sound naive, but what do you mean by "set up an endpoint without a listener"?
To me, the transport layer correspond to ports, which either have a process listening or not.

(A quick Internet search on the error message was not very helpful, i'll need to dig further in to find out what that means)

**Comment by licaon-kter** [comment]
I've said "endpoint" to map my description on the error message, yes the daemon that listened there was stopped.

The error message is not from sslh?

**Comment by yrutschle** [comment]
Ok so you:
- Start nginx
- Start sslh
- Start a connection to nginx through sslh
- Stop nginx
?

Yes the message is emitted by sslh, but it's really just the error message returned by read() on the socket, and it's conveniently not documented in the man page.

**Comment by licaon-kter** [comment]
Ok so this will trigger it instantly:
* have nginx running (but no connections), listen on 8443
* have sslh running with an entry to a port where nginx listens _eg. sslh:443->upload->:8443_
* stop nginx
* everything is ok
* `wget upload:443`
* see the `syslog` & `daemon.log` instantly filled with >100 entries/second of `common.c:431:read:107:Transport endpoint is not connected`
* `systemctl stop sslh` will not stop it
* `pkill sslh` will stop it

**Comment by yrutschle** [comment]
Ok, I re-read the code and did find an issue (unrelated to verbose :) ): upon connection closure, the `fd2fd` function would return -1 as error when it was supposed to return 0. The last commit should fix this.

**Comment by licaon-kter** [comment]
Fixed, thanks
