### ISSUE TITLE
Error 'Unknown type boolean' when regenerating sshl-conf.[ch] with conf2struct

### ISSUE THREAD

**Issue by gubraun** [yrutschle/sslh#230]
I'm working on adding support for a proprietary protocol (used by Coverity). So I've modified sslhconf.cfg. When conf2struct is invoked through the Makefile, it gives an error

Unknown boolean type

which results in faulty ssh-conf.[ch] files.

I just pulled the latest conf2struct from the repo.

Reproduce with 
git clone https://github.com/yrutschle/sslh
git clone https://github.com/yrutschle/conf2struct

export PATH=$PATH:`pwd`/conf2struct
cd sslh
touch sslhconf.cfg
make

**Comment by yrutschle** [comment]
I need to change `sslh` build so it uses a specific version of `conf2struct`... I'm working on `conf2struct` and it is no longer doing what `sslh` expects. You can try rolling back to 10ea3356b65e712fb000f4d37f00e1dc09c1e722 which I think should work.

I'm hoping to get `conf2struct` to a stable place fairly soon, at which point I'll re-synchronise `sslh`.
Sorry for the inconvenience...

**Comment by SaschaZorn** [comment]
Can you please add a comment to doc/INSTALL.md with the git hash of conf2struct that is working with sshl! I just tried "confcheck" and a few minutes of pointless debugging of conf2struct until I found this comment of yours.

**Comment by yrutschle** [comment]
Fair enough -- done.

**Comment by yrutschle** [comment]
@candrews : question for a distribution packager: to simplify installation and dependencies, I'm thinking of adding a make target to retrieve the appropriate version of conf2struct, e.g.:

```
make dep-get
```

which would clone the correct version of c2s under `sslh/`, but then it means the make target for `sslh-conf.c` would need to directly use `conf2struct/conf2struct` (using relative path to what we cloned), which I suspect you won't like (I guess you're packaging c2s separately and handling the version dependency through the packaging system?).

Do you have suggestions as to how this is usually handled? Or should I just leave it at specifying the version in INSTALL.md?

**Comment by candrews** [comment]
For distro packaging, you're right - the `make dep-get` approach isn't well liked (it's basically a bundled dependency at that point) :-)
Documenting it in the README is always nice.
Another nice thing would be to use semantic versioning for c2s, then you can say in sslh that it requires c2s 2.x, allowing users to know that c2s 1.x or 3.x won't work with that version of sslh.

**Comment by yrutschle** [comment]
All done.
