### ISSUE TITLE
Compilation issues on Debian 8 arm

### ISSUE THREAD

**Issue by Tassleh0ff** [yrutschle/sslh#238]
Hello, I have some issue during compilation from sources on a Debian 8 arm board (Banana PI).

I installed libconfig8-dev and libwrap0-dev packages but if I try to make it I always get the same error, here some details:

> root@banana:/usr/src# dpkg -l | grep -E "libwrap0-dev|libconfig8-dev"
ii  libconfig8-dev                         1.4.9-2                              armhf        Transitional package for libconfig-dev
ii  libwrap0-dev:armhf                     7.6.q-25                             armhf        Wietse Venema's TCP wrappers library, development files
root@banana:/usr/src#
root@banana:/usr/src# uname -a
Linux banana 3.4.113-bananian #9 SMP PREEMPT Sat May 6 12:20:11 UTC 2017 armv7l GNU/Linux
root@banana:/usr/src#
root@banana:/usr/src# cat /etc/debian_version
8.11
root@banana:/usr/src#
root@banana:/usr/src# git clone https://github.com/yrutschle/sslh.git
Cloning into 'sslh'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 1258 (delta 3), reused 5 (delta 2), pack-reused 1246
Receiving objects: 100% (1258/1258), 569.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (784/784), done.
Checking connectivity... done.
root@banana:/usr/src#
root@banana:/usr/src# cd sslh
root@banana:/usr/src/sslh# make
./genver.sh >version.h
conf2struct sslhconf.cfg
make: conf2struct: Command not found
Makefile:76: recipe for target 'sslh-conf.c' failed
make: *** [sslh-conf.c] Error 127
root@banana:/usr/src/sslh#

Do you have any idea?

Thanks

Tas

**Comment by licaon-kter** [comment]
Compile & install https://github.com/yrutschle/conf2struct first.

**Comment by yrutschle** [comment]
This should be fine now with conf2struct v1.0.
