### ISSUE TITLE
Change displayed process name to identify connection

### ISSUE THREAD

**Issue by niobos** [yrutschle/sslh#239]
Hi,

First of all: thank you for the time and effort you put in to this very useful project. I mean it!

I have an idea for enhancing the usage of sslh in forking-mode, but would like to bounce it here first before I spend the time to code up a Pull Request. I would like the sslh-sub-process to rename itself to include the connection it is currently handling, similar to how Dovecot does it. To be more concrete:

Currently, in forking mode, my `ps` output looks like this:
```
sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 \_ sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 |   \_ sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 |   \_ sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 |   \_ sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 \_ sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
```

Dovecot looks like this:
```
/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf
 \_ dovecot/anvil [11 connections]
 \_ dovecot/log
 \_ dovecot/config
 \_ dovecot/stats [21 connections]
 \_ dovecot/imap-login [192.0.2.1 TLS proxy]
 \_ dovecot/imap [someone@example.org 192.0.2.1 IDLE]
 \_ dovecot/imap-login [192.0.2.1 TLS proxy]
 \_ dovecot/imap [someone@example.org 192.0.2.1 IDLE]
 \_ dovecot/imap-login [192.0.2.1 TLS proxy]
 \_ dovecot/imap [someone@example.org 192.0.2.1 IDLE]
 \_ dovecot/auth [0 wait, 0 passdb, 0 userdb]
```

It would be nice if sslh could look something like:
```
sslh -p 0.0.0.0 443 -p [::] 443 --ssh 127.0.0.1 22 --tls 127.0.0.1 1443 --openvpn 127.0.0.1 1194
 \_ sslh [HTTPS 192.0.2.7:12345 -> 127.0.0.1:1443]
 \_ sslh [SSH 192.0.2.7:6789 -> 127.0.0.1:22]
```

This way, it is also possible to specifically kill a connection without needing to tie together `netstat`, `lsof` or `ss` output.

Technically, this seams to be possible with `prctl()` and/or `pthread_setname_np()`.

Would you be open to such a pull request?

**Comment by yrutschle** [comment]
Yes, this sounds useful and a fairly small add: just build the string and set it as process name in `start_shoveler()` before running `shovel()`.
Try the `prctl()` route, we don't link to pthread.
