### ISSUE TITLE
Transparent connection only for some variants

### ISSUE THREAD

**Issue by GooG2e** [yrutschle/sslh#243]
Hello!
Can I use transparent connection only for some connections&
For example - http with transparent connection and ssh without

**Comment by yrutschle** [comment]
That's not currently possible, but I think it's theoritically not very complicated. I have a vague recollection that that's one of the features that prompted me to overhaul the configuration system some time ago.

I'll keep this open as something to implement in the future.

**Comment by evert-mouw** [comment]
+1 for this feature request. Currently I'm connecting both to a www server on another host _and_ to a squid server on the same host. I can't get the connections with squid working in transparent mode.

**Comment by yrutschle** [comment]
Here you go, I just pushed something that should do the job

**Comment by yrutschle** [comment]
Fixed in adb27aa4a391410d278a5590fcce644f32e33e8c
