### ISSUE TITLE
CentOS 8 0.0.0.0:https:bind: Address already in use

### ISSUE THREAD

**Issue by sblantipodi** [yrutschle/sslh#249]
Hi,
using Centos 8 here.

If I start apache httpd before sslh I get this error when starting sslh 

0.0.0.0:https:bind: Address already in use

Any idea ? It seems an sslh problem.

**Comment by licaon-kter** [comment]
`sudo netstat -tupan|grep LISTEN` ?

**Comment by sblantipodi** [comment]
> netstat -tupan|grep LISTEN

yes apache is listening on 8443

the output of the command is
tcp        0      0 myip:49999    0.0.0.0:*               LISTEN      
tcp6       0      0 :::8443                 :::*                    LISTEN      
tcp6       0      0 myip:49999 :::*                    LISTEN      
tcp6       0      0 :::80                   :::*                    LISTEN

**Comment by sblantipodi** [comment]
neither ssh works ok. if I shutdown apache, sslh turns on but then I can't login to ssh using 443 port.
ssh is listening on port 49999

**Comment by licaon-kter** [comment]
Try a local IP, not 0000

**Comment by sblantipodi** [comment]
> Try a local IP, not 0000

@licaon-kter no luck even with 127.0.0.1 or with internal/public ip

**Comment by licaon-kter** [comment]
What does this do exactly, loop? `{ name: "anyprot"; host: "localhost"; port: "443"; }`

**Comment by sblantipodi** [comment]
changed ssh to listen on all interfaces and now it works, thaks man great project!
