### ISSUE TITLE
https://www.rutschle.net/tech/sslh/README.html is not resolved

### ISSUE THREAD

**Issue by sachincool** [yrutschle/sslh#257]
![image](https://user-images.githubusercontent.com/25671488/75819908-73bc1a00-5dc1-11ea-8d6f-83beb4f82a33.png)

**Comment by yrutschle** [comment]
A server upgrade gone weirdly wrong. Should be fine now, with Buster installed hopefully for the next 2 years :)

**Comment by yrutschle** [comment]
Argh, apparently there is an issue left on HTTPS; it works fine on port 80. I'll have a look later today.

Buster as in Debian 10. The site is generated by Jekyll. I'd never heard of "Buster Static Site Generator for Ghost", nor of "Ghost ...? dunno what it is" before, but it seems pretty similar, in spirit at least :)

**Comment by yrutschle** [comment]
Ok, this problem about my Web site is fixed, but uncovers another real problem with `sslh`, for which I open #258 .

**Comment by yrutschle** [comment]
(I am now using `sslh-fork` while figuring out why the LXC won't start, and why `sslh` hangs. Why does nothing ever work as expected, and what would I do with my time if it did? :))
