### ISSUE TITLE
can I use it with ssl and rdp

### ISSUE THREAD

**Issue by wo4wangle** [yrutschle/sslh#259]
I want to remote control windows, so I want to use RDP
and I have seen "any other protocol that can be tested using a regular expression, can be recognised"
so can I apply it on RDP, thks.

**Comment by yrutschle** [comment]
I went down in a rabbit hole of specifications... namely:
- [RDP](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPBCGR/%5bMS-RDPBCGR%5d.pdf) which I understand is built on top of:
- [MCS T.125](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.125-199802-I!!PDF-E&type=items), which I understand is all encoded in ASN.1 BER (chapter 9) with PDUs that all start with a channel ID that is a 16-bits integer (chapter 7)
- [ASN.1 encoding of integers](https://docs.microsoft.com/fr-fr/windows/win32/seccertenroll/about-integer?redirectedfrom=MSDN) makes me expect the first bytes to be 0x02 ('integer') 0x02 ('on 16 bits')

So, if ALL of this is right, something like:
```
^\x02\x02
```
should work. Now, I would not be surprised if other protocols are based on MCS, or ASN.1, so it may not be quite discriminatory enough. Or, I may have missed entirely some other level of encoding :-)

Let me know if that works. Looking at several connection traces (with `tcpdump` or Wireshark) would help, too.

**Comment by iamdoubz** [comment]
For me, it did not work...

```
{ name: "regex"; host: "192.168.1.3"; port: "3389"; regex_patterns: [ "^\x02\x02" ]; keepalive: true; log_level: 1 },
```

I saved a Wireshark dump, but am 100% sure I have no idea what I'm looking for.

**Comment by ondrejvaroscak** [comment]
I use a workaround. Having the SSL/SSH and OpenVPN configured accordingly, I use "--anyprot" to forward anything else including RDP to the destination.

**Comment by utoni** [comment]
> I went down in a rabbit hole of specifications... namely:
> 
>     * [RDP](https://winprotocoldoc.blob.core.windows.net/productionwindowsarchives/MS-RDPBCGR/%5bMS-RDPBCGR%5d.pdf) which I understand is built on top of:
> 
>     * [MCS T.125](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.125-199802-I!!PDF-E&type=items), which I understand is all encoded in ASN.1 BER (chapter 9) with PDUs that all start with a channel ID that is a 16-bits integer (chapter 7)
> 
>     * [ASN.1 encoding of integers](https://docs.microsoft.com/fr-fr/windows/win32/seccertenroll/about-integer?redirectedfrom=MSDN) makes me expect the first bytes to be 0x02 ('integer') 0x02 ('on 16 bits')

Recent Windows versions will most likely use RDP over TLS.

**Comment by yrutschle** [comment]
I assume you found some way to solve this problem, please reopen otherwise.
