### ISSUE TITLE
Reverse SSH Tunnel possible?

### ISSUE THREAD

**Issue by winkmichael** [yrutschle/sslh#260]
Very cool project! I was wonder if it is possible to use this for a reverse ssh tunnel. I've google and experimented without luck. 

Thank you very much!

**Comment by yrutschle** [comment]
I don't see why that wouldn't work...

4 avr. 2020 22:28:21 winkmichael <notifications@github.com>:

**Comment by darkfader** [comment]
I'm trying this as well in combination with sslh. Somehow the listen port stays open when client disconnects though, resulting in:
`ssh: Remote TCP forward request failed (port 65000 -> localhost:22)`
To make it more secure, use something like `restrict,port-forwarding,permitlisten="localhost:65000" ssh-rsa ....`
Good luck!

**Comment by winkmichael** [comment]
Darkfadar, I used StreamLocalBindUnlink yes to resolve the issue you describe.
