### ISSUE TITLE
Implement TLS 1.3 random record padding to improve security

### ISSUE THREAD

**Issue by candrews** [yrutschle/sslh#262]
The TLS specification (RFC 8446) section 5.4 defines optional Record Padding: https://tools.ietf.org/html/rfc8446#section-5.4

As a security improvement, I suggest that sslh implement random record padding.

Random record padding would mitigate the BREACH attack (and other similar) vulnerabilities.

In OpenSSL, this is done using SSL_CTX_set_record_padding_callback: https://www.openssl.org/docs/man1.1.1/man3/SSL_set_block_padding.html

**Comment by yrutschle** [comment]
I am a bit confused as to what you're expecting sslh to do. We do not use OpenSSL, and we barely parse TLS (just the options in the first packet, to extract ALPN and SNI fields).

**Comment by candrews** [comment]
Oops. Totally my mistake, I forgot how sslh worked (I mistakenly thought it decrypted then re-encrypted MITM style).

Apologies for the trouble!

**Comment by yrutschle** [comment]
No worries :)
