### ISSUE TITLE
I do not see logging sslh

### ISSUE THREAD

**Issue by f1h0** [yrutschle/sslh#264]
I do connect via ssh port 443
see in the log file server IP, how do I see the user ip?
Why are developers so increasingly complex and we have to write tickets for the developer?
Many Linux program has separate parameters for logging

I just do not see a log file auth.log ```sslh``` process only ```sshd```

**Comment by licaon-kter** [comment]
Look up docs on "transparent proxy" s.

**Comment by f1h0** [comment]
@licaon-kter 
in the comments, many have written that there is a problem with security or the error?

**Comment by licaon-kter** [comment]
Sorry, but I half understand what you write.

**Comment by f1h0** [comment]
@licaon-kter 
users in other matters, wrote that there are problems with the included transparent proxy mode
I added this parameter is ```transparent: true;```
and I can no longer connect via ssh

**my config**
```
verbose: true;
foreground: true;
timeout: 5;
user: "sslh";
syslog_facility: "auth";
pidfile: "/var/run/sslh/sslh.pid";

listen:
(
   { host: "IP_SERVER"; port: "443"; }
);

protocols:
(
    { name: "ssh";     host: "127.0.0.1"; port: "22";     probe: "builtin"; fork: true; log_level: "1"},
    { name: "tls";     host: "127.0.0.1"; port: "443";    probe: "builtin"; log_level: "1" },
    { name: "openvpn"; host: "127.0.0.1"; port: "636"; probe: "builtin"; },
    { name: "anyprot"; host: "127.0.0.1"; port: "443";   probe: "builtin"; }
);

on-timeout: "tls";

```

**Comment by f1h0** [comment]
@licaon-kter 
I ask for help how to turn logs
I fell down the whole system, fail2ban blocked himself.
Because a log file auth.log see only 1 server IP if connect on port 443

URGENT PLEASE HEAR ME work I

**Comment by yrutschle** [comment]
Developers use whatever the heck they want. There is a mailing list to ask questions, if you prefer that to opening tickets (there are pros and cons on both sides: tickets don't get lost, but the interface isn't as nice as e-mail).

`sslh` doesn' t log when in foreground, instead it prints to `stderr`. That's a questionnable choice indeed and I guess you could argue that it should log regardless of whether it prints or not.

And then you'll probably have an easier time setting up fail2ban with `sslh` logs, than getting transparent proxying working. It works for some, but I sometimes feel like no one really knows how or why it works (I personally have no idea -- I understand the C side of things, but not the kernel routing that goes around it).

**Comment by f1h0** [comment]
@licaon-kter 
I conducted an analysis and found that the reports would be written to a log file ```sslh```
to syslog is also no mention of any single line ```sslh```
that not so I do?

**Comment by f1h0** [comment]
@licaon-kter 
if I shove command manually ```sslh -F sslh.conf```
I see logging of all actions, and now I have to move it to a log file sslh.log
how to do step by step please show

**Comment by licaon-kter** [comment]
You did read https://github.com/yrutschle/sslh/blob/master/doc/config.md#transparent-proxy-support and saw https://github.com/yrutschle/sslh/tree/master/scripts/fail2ban already?

**Comment by yrutschle** [comment]
and remove foreground so logs actually go to logs instead of stderr, already? (I'll go change this, I guess it really is a bad decision anyway)

**Comment by f1h0** [comment]
@yrutschle 
more information please, I have to do.
Google transliteration stupid like a duck, bad translate what you write

**Comment by f1h0** [comment]
@yrutschle 
that's what I see when I type the command  ``` systemctl status sslh.service```
```
● sslh.service - SSL/SSH multiplexer
   Loaded: loaded (/lib/systemd/system/sslh.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/sslh.service.d
           └─10-restart-failure.conf
   Active: active (running) since Thu 2020-05-28 10:35:49 UTC; 2h 30min ago
     Docs: man:sslh(8)
 Main PID: 16777 (sslh)
    Tasks: 2
   Memory: 240.0K
      CPU: 22ms
   CGroup: /system.slice/sslh.service
           ├─16777 /usr/sbin/sslh --foreground -F /etc/sslh.cfg
           └─16779 /usr/sbin/sslh --foreground -F /etc/sslh.cfg

May 28 10:35:49 std systemd[1]: Started SSL/SSH multiplexer.
```
and must have the correct entry in the log ```systemd[1]``` ?

**Comment by yrutschle** [comment]
Yesterday, I pushed a commit to send all message to syslog even if `sslh` is running with `--foreground`. If you pull that commit, you should see messages in `/var/log/auth.log` (probably).

**Comment by yrutschle** [comment]
Assuming this is fixed.
