### ISSUE TITLE
Help Configuring multiple ports on SSLH

### ISSUE THREAD

**Issue by RealTitanGod** [yrutschle/sslh#265]
Hello, I am running a Minecraft server from home and I’m using AWS to have like a proxy sit between my home network and people connecting to server. This way they don’t know what my IP address is. It uses sslh to make the connection. I was wondering if it's possible to have it listen to more then one port. This is the default setup on the sslh file which is working but I’d like to be able to add more ports:
DAEMON_OPTS="–user sslh --listen 0.0.0.0:25565 --anyprot your_ip_address:25565 --pidfile /var/run/sslh/sslh.pid"

The original guide I used: https://www.howtogeek.com/440752/protect-your-home-minecraft-server-from-ddos-attacks-with-aws/

**Comment by yrutschle** [comment]
As mentionned in the documentation: "This can be specified several times to bind B<sslh> to
several addresses.".
Just specify `--listen` once for each port you want to listen to.

**Comment by RealTitanGod** [comment]
Hi, thanks for the reply. This doesn't seem to do what I hoped for then. I was able to open all the ports I needed but they seemed to all then lead into the port on `--anyprot your_ip_address:25565` Is there a way to make then lead to their respected port on my end and not just that single port?
