### ISSUE TITLE
sslh & Nginx - Nginx error client timed out (110: Connection timed out) while SSL handshaking

### ISSUE THREAD

**Issue by tomeras1** [yrutschle/sslh#267]
Hi,

I'm using sslh with the command - "sslh -u sslh --listen server_address:443 --openvpn server_address:1194 --tls server_address:4433 --anyprot server_address:4433 -f -v"
I'm also running a nginx server which listens to port 443.

Unfortunately I can't connect to the server (using a browser, https for ssl).
I almost get no logs in the sslh output (except "probing for tls: PROBE_MATCH... timed out, connecting to tls...") 
In the Nginx error logs I get the error "client timed out (110: Connection timed out) while SSL handshaking, client: server_address, server: 0.0.0.0:4433" 
Instead of server_address I use the ip address of the server.

If I use Nginx alone on 443 without sslh, it works good (I do need sslh in order to run openvpn as well so both will be accessed using 443).

Do you have an idea what can cause this issue?

Thanks,
Tomer

**Comment by yrutschle** [comment]
Not really; you should get more messages than that, at least try to add a -v argument (-v 3 for example).

**Comment by tomeras1** [comment]
I used the command with "-v" but I"ll try "-v 3", thanks!

**Comment by yrutschle** [comment]
Closing due to lack of response
