### ISSUE TITLE
Garbage is logged to syslog

### ISSUE THREAD

**Issue by shadowlmd** [yrutschle/sslh#268]
I noticed garbage being logged to syslog, for example:
```
Jun 11 21:17:50 vpsoc sslh-fork[11969]: (null):connection from  to 188.170.81.111:2555 forwarded from (null) to (null)
Jun 11 21:17:50 vpsoc sslh-fork[11969]: (null):connection from  to 188.170.81.111:53611 forwarded from (null) to (null)
Jun 11 21:17:51 vpsoc sslh-fork[11969]: (null):connection from  to 188.170.81.111:57003 forwarded from (null) to (null)
Jun 11 21:17:51 vpsoc sslh-fork[11969]: (null):connection from  to 188.170.81.111:19764 forwarded from (null) to (null)
```
At the same time proper messages are logged to console:
```
Jun 11 21:17:50 vpsoc sslh-fork[15808]: tls:connection from 188.170.81.111:2555 to 10.0.0.2:443 forwarded from 127.0.0.1:41260 to 127.0.0.1:1234
Jun 11 21:17:50 vpsoc sslh-fork[15809]: tls:connection from 188.170.81.111:53611 to 10.0.0.2:443 forwarded from 127.0.0.1:41264 to 127.0.0.1:1234
Jun 11 21:17:51 vpsoc sslh-fork[15827]: tls:connection from 188.170.81.111:57003 to 10.0.0.2:443 forwarded from 127.0.0.1:41268 to 127.0.0.1:1234
Jun 11 21:17:51 vpsoc sslh-fork[15828]: tls:connection from 188.170.81.111:19764 to 10.0.0.2:443 forwarded from 127.0.0.1:41272 to 127.0.0.1:1234
```

**Comment by shadowlmd** [comment]
There is also this weird message on startup:
```
Jun 11 21:24:25 vpsoc.bsrealm.net systemd[1]: Started SSL/SSH multiplexer.
Jun 11 21:24:25 vpsoc.bsrealm.net sslh-fork[20672]: (null) @( started
Jun 11 21:24:25 vpsoc.bsrealm.net sslh-fork[20672]: sslh-fork v1.20-78-gc595aad started
```

**Comment by shadowlmd** [comment]
This is occurring on Ubuntu 20.04.

**Comment by shadowlmd** [comment]
It is started via systemd service:
```
[Unit]
Description=SSL/SSH multiplexer
After=network.target

[Service]
ExecStart=/opt/sslh/sbin/sslh-fork -F/opt/sslh/etc/sslh.cfg
KillMode=process
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```

**Comment by shadowlmd** [comment]
Also, I don't see a point in syslog logging at all when running via systemd. But I didn't find a way to disable syslog logging.

**Comment by yrutschle** [comment]
Ah, maybe that was why there was an alternative between syslog or stderr but not both.

The bug is most odd, as what's passed to syslog and what's passed to stderr are all the same parameters (in common.c:log_message).

**Comment by shadowlmd** [comment]
But is there a way to disable syslog logging? I couldn't find it.

**Comment by shadowlmd** [comment]
Regarding the bug, looking at PID, messages to stderr are generated by child processes while syslog messages are coming from master process.

**Comment by shadowlmd** [comment]
Reverting commit c595aadb4d0d9c72ba1a6ab10d13c444ca58ca69 fixed everything.

**Comment by yrutschle** [comment]
oh but of course. The va_list was consumed by vfprintf, so I need to 'rewind' it.

**Comment by yrutschle** [comment]
fixed in 408c5741f8f8298ada6cf28a7a0c2cdecd0d1d2e

**Comment by yrutschle** [comment]
and c5b0932bad5e32d658ed171cf009c0f8c4f6ba58 lets you disable syslog using fake facility 'none'.

**Comment by yrutschle** [comment]
thank you for the report and the time you spent investigating this!

**Comment by shadowlmd** [comment]
Great, thank you! :)
