### ISSUE TITLE
sslh 1.21c without libconfig segfaults

### ISSUE THREAD

**Issue by kirchwitz** [yrutschle/sslh#274]
At first, big thanks to make sslh 1.21c compile without libconfig again. Compilation works great!

Unfortunately, now maybe something with the initialization goes wrong because sslh segfaults immediately after start. Seems to be at a very early stage, even with verbose=2 there's no output.

             PID: 7345 (sslh)
             UID: 0 (root)
             GID: 0 (root)
          Signal: 11 (SEGV)
       Timestamp: Fri 2020-07-31 13:03:51 CEST (2min 59s ago)
    Command Line: /usr/local/sbin/sslh -f --verbose 2 --user nobody --pidfile /tmp/sslh.pid --listen 127.0.0.1:12345 --tls 127.0.0.1:443 --ssh 127.0.0.1:22 --numeric
      Executable: /usr/local/sbin/sslh
         Storage: /var/lib/systemd/coredump/core.sslh.0.(...).lz4
         Message: Process 7345 (sslh) of user 0 dumped core.

                Stack trace of thread 7345:
                #0  0x0000000000404978 sslhcfg_cl_parse (sslh + 0x4978)
                #1  0x00000000004076de main (sslh + 0x76de)
                #2  0x00007f2746d46042 __libc_start_main (libc.so.6 + 0x27042)
                #3  0x000000000040255e _start (sslh + 0x255e)**

If I run the same command line but with a binary of sslh that has libconfig support compiled in (my outdated libconfig 1.4.9 plus adding "#define config_setting_lookup config_lookup_from" to sslh-conf.c) - but without actually using libconfig features - then everything seems to work fine. Binary starts without segmentation fault, I see some nice verbose output, and also seems to run fine on my server (both, connections with SSH and HTTPS work as expected).

Maybe some essential initialization is missing if compiled without libconfig support? Just a wild guess, I'm no expert here. Please let me know if you need additional information. I'm happy to help.

**Comment by yrutschle** [comment]
Yes, that was shameful. I don't even know how it got in, I was certain I'd tested actually not having libconfig...

Say, I heard you on supporting libconfig 1.4.9; just to check: do you add the #define after the headers? (i.e. around line 50, after the 'this gets included in the output .c file' comment)? I'm willing to add the 3 lines to support it, but testing will be on you ;)

**Comment by yrutschle** [comment]
libconfig 1.4.9 support in #275

**Comment by yrutschle** [comment]
@kirchwitz for some reason I can't reference you in #275 -- I've posted code I expect should work, would you mind trying it?
