### ISSUE TITLE
Support libconfig 1.4.9

### ISSUE THREAD

**Issue by yrutschle** [yrutschle/sslh#275]
As mentionned (here)[https://github.com/yrutschle/sslh/issues/256), libconfig 1.4.9 is installed on many servers.

**Comment by yrutschle** [comment]
Ok, here's what I'd like to add, which I think does what is needed, only for libconfig 1.4.9:
```
diff --git a/sslh-conf.c b/sslh-conf.c
index eb616ec..630bdea 100644
--- a/sslh-conf.c
+++ b/sslh-conf.c
@@ -47,6 +47,14 @@
 
 /* This gets included in the output .c file */
 
+#if LIBCONFIG_VER_MAJOR == 1
+#if LIBCONFIG_VER_MINOR == 4
+#if LIBCONFIG_VER_REVISION == 9
+#define config_setting_lookup config_lookup_from
+#endif
+#endif
+#endif
+
 
 /* config_type, lookup_fns, type2str are related, keep them together */
 typedef enum {
```

**Comment by kirchwitz** [comment]
On RHEL/CentOS 7 (which is stuck with libconfig 1.4.9 unfortunately) the patch applies fine and the source now compiles without troubles. Running the binary for over a week now, and no problems so far. Thanks a lot, this makes life a little easier until the majority has switched to RHEL/CentOS 8.

**Comment by yrutschle** [comment]
Oh, there was no need to run for a week: reading the configuration file either works or it doesn't :-)

Thanks, I'll commit this now.
