### ISSUE TITLE
OpenVPN not working

### ISSUE THREAD

**Issue by AmazedWolf900** [yrutschle/sslh#277]
Hello, I have a problem connecting to the OpenVPN server through sslh.

Here are the configuration files:

**sslh**
`Run=yes
DAEMON=/usr/sbin/sslh
DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --openvpn 127.0.0.1:1149 --ssl 127.0.0.1:4443 --ssh 127.0.0.1:22 --timeout 20 --pidfile /var/run/sslh/sslh.pid"`

**OpenVPN server**
local x.x.x.x
port 1194
proto tcp
dev tun
ca ca.crt
cert server.crt
key server.key
dh dh.pem
auth SHA512
tls-crypt tc.key
topology subnet
server 10.8.0.0 255.255.255.0
server-ipv6 fddd:1194:1194:1194::/64
push "redirect-gateway def1 ipv6 bypass-dhcp"
ifconfig-pool-persist ipp.txt
push "dhcp-option DNS x.x.x.x"
push "dhcp-option DNS x.x.x.x"
keepalive 10 120
cipher AES-256-CBC
user nobody
group nogroup
persist-key
persist-tun
status openvpn-status.log
verb 3
crl-verify crl.pem

**OpenVPN client**
client
dev tun
proto tcp
remote x.x.x.x 443
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
auth SHA512
cipher AES-256-CBC
ignore-unknown-option block-outside-dns
block-outside-dns
verb 3

**This is the log of the vpn client:**
Tue Sep  8 14:01:38 2020 Unrecognized option or missing or extra parameter(s) in vpn.ovpn:13: block-outside-dns (2.4.7)
Tue Sep  8 14:01:38 2020 OpenVPN 2.4.7 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Sep  5 2019
Tue Sep  8 14:01:38 2020 library versions: OpenSSL 1.1.1f  31 Mar 2020, LZO 2.10
Tue Sep  8 14:01:38 2020 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Sep  8 14:01:38 2020 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Sep  8 14:01:38 2020 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
Tue Sep  8 14:01:38 2020 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
Tue Sep  8 14:01:38 2020 TCP/UDP: Preserving recently used remote address: [AF_INET]185.119.98.171:443
Tue Sep  8 14:01:38 2020 Socket Buffers: R=[131072->131072] S=[16384->16384]
Tue Sep  8 14:01:38 2020 Attempting to establish TCP connection with [AF_INET]185.119.98.171:443 [nonblock]
Tue Sep  8 14:01:39 2020 TCP connection established with [AF_INET]185.119.98.171:443
Tue Sep  8 14:01:39 2020 TCP_CLIENT link local: (not bound)
Tue Sep  8 14:01:39 2020 TCP_CLIENT link remote: [AF_INET]185.119.98.171:443
Tue Sep  8 14:01:39 2020 Connection reset, restarting [0]
Tue Sep  8 14:01:39 2020 SIGUSR1[soft,connection-reset] received, process restarting
Tue Sep  8 14:01:39 2020 Restart pause, 5 second(s)

I can connect to the SSH or SSL but I can't connect to the vpn. Already tried remove --ssl and --ssh options from sslh config and add --anyprot 127.0.0.1:1149.

OpenVPN server and client version: 2.4.7
sslh version: sslh-fork 1.20-1

**Comment by vespino** [comment]
Seems I have the same problem when running openvpn on the same server. It does seem to work when I’m using openvpn on another server though.

**Comment by yrutschle** [comment]
Censoring configuration files doesn't help. What's:
```
 local x.x.x.x
```

sslh tries to connect to 127.0.0.1
```
--openvpn 127.0.0.1:1149
```
so if x.x.x.x is not 127.0.0.1 or unspecified, then OpenVPN is not listening to where sslh is connecting.

Is sslh complaining it can't connect?

**Comment by yrutschle** [comment]
Closing due to lack of response
