### ISSUE TITLE
Can sslh be use for redirect WebDav from port 443?

### ISSUE THREAD

**Issue by stephane-archer** [yrutschle/sslh#281]
Is it something supported?
Is it considered as an HTTP or TLS/SSL connection?

Thanks in advance.

**Comment by licaon-kter** [comment]
Maybe you can setup it on a specific subdomain and use that to filter?

**Comment by stephane-archer** [comment]
The new subdomain can be filter? Will I just see requests to the same server IP address? 
There is two type of traffic for my server, openVPN and WebDav. Can I do: everything is redirect here except when openVPN request are detected?

**Comment by yrutschle** [comment]
Yes of course, that's trivial: use the openvpn probe to send to OpenVPN, and the TLS probe to send to the WebDav server.
If you *also* need to serve a Web site, then Licaon's suggestion is the simplest: move the Webdav server to its own URL (e.g. dav.example.org) and use the SNI option of the TLS probe.
IIRC DAV is the same as TLS so there is no way to tell them apart except based on URL

**Comment by stephane-archer** [comment]
Thanks you so much guys, you're the best! ☺️
