### ISSUE TITLE
Dependency on conf2struct is back

### ISSUE THREAD

**Issue by shadowlmd** [yrutschle/sslh#283]
Hi!

It was great when dependency on conf2struct was removed, but now it's back:
```
$ make
./genver.sh >version.h
conf2struct sslhconf.cfg
make: conf2struct: Command not found
make: *** [Makefile:84: sslh-conf.c] Error 127
```
Can we please make it buildable again without having to install loads of perl modules from CPAN? :)

**Comment by yrutschle** [comment]
I don't think so: the files produced by conf2struct are checked in the Git. OTOH they are removed by `make distclean`, so if you did that, you need to reset them from Git:
```
git checkout -- .
```
Unless of course I got something wrong...

**Comment by shadowlmd** [comment]
This is weird. I didn't ever run make distclean. Only make clean. Also, git checkout -- . didn't help. But cloning whole repo from scratch wrked.

**Comment by yrutschle** [comment]
How is that possible? I understand `git checkout -- . ` recreates the files from the index, which would be the same as cloning.

I blame either Git, or my own ignorance of it...

**Comment by shadowlmd** [comment]
I don't think Git is a problem here. I just deleted and restored sslhconf.cfg and the problem is back:
```
shadowlmd@home:~/git/sslh$ rm sslhconf.cfg
shadowlmd@home:~/git/sslh$ make
./genver.sh >version.h
make: *** No rule to make target 'sslhconf.cfg', needed by 'sslh-conf.c'.  Stop.
shadowlmd@home:~/git/sslh$ git checkout -- .
shadowlmd@home:~/git/sslh$ ll sslhconf.cfg
-rw-rw-r-- 1 shadowlmd shadowlmd 9026 Dec  1 11:36 sslhconf.cfg
shadowlmd@home:~/git/sslh$ mk
shadowlmd@home:~/git/sslh$ make
conf2struct sslhconf.cfg
make: conf2struct: Command not found
make: *** [Makefile:84: sslh-conf.c] Error 127
```

**Comment by shadowlmd** [comment]
I guess it somehow depends on timestamps of sslh-conf.c and sslh-conf.cfg, but git doesn't update timestamps if contents wasn't changed. So most probably every time you change only one of these files, make will try to run conf2struct.

**Comment by shadowlmd** [comment]
This proves it:
```
shadowlmd@home:~/git/sslh$ touch sslhconf.cfg sslh-conf.c
shadowlmd@home:~/git/sslh$ make
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-conf.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c common.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-main.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c probe.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c tls.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c argtable3.c
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-fork.c
cc -Wall -g   -o sslh-fork sslh-fork.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
#strip sslh-fork
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c sslh-select.c
cc -Wall -g   -o sslh-select sslh-select.o sslh-conf.o common.o sslh-main.o probe.o tls.o argtable3.o  -lpcreposix -lconfig
#strip sslh-select
pod2man --section=8 --release=v1.21c-15-g41e3b0c --center=" " sslh.pod | gzip -9 - > sslh.8.gz
cc -Wall -g  -DENABLE_REGEX -DLIBPCRE -DLIBCONFIG -c echosrv.c
cc -Wall -g   -o echosrv echosrv.o sslh-conf.o probe.o common.o tls.o argtable3.o  -lpcreposix -lconfig
```

**Comment by yrutschle** [comment]
oh, but of course!

Apparently Git creates the files with local time (which sounds reasonnable) instead of the time of checkin (which would be weird, even if it would help here).

So I guess what happens is that *sometimes*, if the pull ends up pulling sslh-conf.c before sslhconf.cfg, make thinks "sslh-conf.c is an old version, I need to regenerate it from sslhconf.cfg because that one is more recent".  And I guess I have no way to tell Git in what order to pull the files.
An alternative I guess would be to `touch sslh-conf.[ch]` after each pull, which would force-mark them as more recent than sslhconf.cfg. That feels relatively dirty. When I get a chance I'll have a look if Git provides help with this.

**Comment by AntonOfTheWoods** [comment]
This is quite a time consumer when someone wants to start and compile this for the first time... It would be great to have this documented in the install docs at least. Would you accept a warnings section PR for the install docs?
