### ISSUE TITLE
Subdomains

### ISSUE THREAD

**Issue by wunderf1tz** [yrutschle/sslh#286]
Dear all,

this is my sslh.cfg at the moment.

How can I get subdomains to be routed from sslh to Apache and then to the right subdomain/subfolder?
Is this done here already or in the Apache config? 

```
verbose: 0;
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh.pid";
syslog_facility: "auth";

# Change hostname with your external address name. Note: It should not be resolving to 127.0.0.1
listen:
(
    { host: "wunderfitzig.net"; port: "443"; }
);

protocols:
(
     #{ name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; keepalive: true; fork: true; },
     { name: "http"; host: "localhost"; port: "443"; log_level: 0;},

     # just match ALPN
     { name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 1;},
     { name: "tls"; host: "localhost"; port: "443"; alpn_protocols: [ "h2", "http/1.1", "spdy/1", "spdy/2", "spdy/3" ]; log_level: 0; },

     # just match SNI
     { name: "tls"; host: "localhost"; port: "5223"; probe: "builtin"; sni_hostnames: [ "wunderfitzig.net" ]; log_level: 1;},
     { name: "tls"; host: "localhost"; port: "443"; probe: "builtin"; sni_hostnames: [ "wunderfitzig.net" ]; log_level: 0; },

     # catch anything else TLS
     { name: "tls"; host: "localhost"; port: "443"; log_level: 0;},

     # Jabber
     { name: "regex"; host: "localhost"; port: "5222"; regex_patterns: [ "jabber" ]; log_level: 1;},
     { name: "regex"; host: "localhost"; port: "443"; regex_patterns: [ "jabber" ]; log_level: 0;},

     # Catch-all
     { name: "regex"; host: "localhost"; port: "443"; regex_patterns: [ "" ]; log_level: 0;},
);

on-timeout: "timeout";
```

**Comment by licaon-kter** [comment]
Just make rules for "subdomain.domain.tld".

The endpoint should be able to deal with the connection.

**Comment by wunderf1tz** [comment]
Thanks a lot for your response :)
With endpoint I guess you mean Apache?

so e.g. for wiki.wunderfitzig.org that would be like this?:
(
    { host: "wunderfitzig.net"; port: "443"; },
    { host: "wiki.wunderfitzig.net"; port: "443"; }
);

protocols:
(
     #{ name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; keepalive: true; fork: true; },
     { name: "http"; host: "localhost"; port: "443"; log_level: 0;},

     # just match ALPN
     { name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 1;},
     { name: "tls"; host: "localhost"; port: "443"; alpn_protocols: [ "h2", "http/1.1", "spdy/1", "spdy/2", "spdy/3" ]; log_level: 0; },

     # just match SNI
     { name: "tls"; host: "localhost"; port: "5223"; probe: "builtin"; sni_hostnames: [ "wunderfitzig.net" ]; log_level: 1;},
     { name: "tls"; host: "localhost"; port: "443"; probe: "builtin"; sni_hostnames: [ "wunderfitzig.net" ]; log_level: 0; },
     { name: "tls"; host: "localhost"; port: "443"; probe: "builtin"; sni_hostnames: [ "wiki.wunderfitzig.net" ]; log_level: 0; },

     # catch anything else TLS
     { name: "tls"; host: "localhost"; port: "443"; log_level: 0;},

     # Jabber
     { name: "regex"; host: "localhost"; port: "5222"; regex_patterns: [ "jabber" ]; log_level: 1;},
     { name: "regex"; host: "localhost"; port: "443"; regex_patterns: [ "jabber" ]; log_level: 0;},

     # Catch-all
     { name: "regex"; host: "localhost"; port: "443"; regex_patterns: [ "" ]; log_level: 0;},
);

on-timeout: "timeout";

**Comment by yrutschle** [comment]
If I understand your question right, it needs to be done in both: SNI in sslh to forward where required, and VirtualHost in Apache to serve the appropriate domain
