### ISSUE TITLE
Transparent to OpenVPN on router and nginx on another host; almost working 

### ISSUE THREAD

**Issue by Bengt-M** [yrutschle/sslh#288]
I use asuswrt-merlin with sslh from entware. There I have an already working OpenVPN. On a NUC I have fedora with a working tls Nginx.
Followed Sean’s tutorial proxy.md
Things I struggled with:
It was tricky to load the socket module.
The NUC didn’t have a routing table 100 so I created one.
Tried long to do the sysctl stuff in config.md but it was not necessary.

It works. Yeay. OpenVPN is on and nginx sees the real client ip.

But its not 100%
When I do my trial-and-horror, sometimes nothing happens. Nothing in any log. Run in foreground but still nothing. Made me try a different way for no reason.
Then after a while its working.
Maybe you need to do some flushing to clear queues?

And when I try again its not working.
Maybe you need to check you'r in sync with the protocols?

**Comment by yrutschle** [comment]
Hmmm there was an off-by-one error that we corrected not that long ago, that led to very confusing behaviour similar to what you describe.
I assume that's what happened, please create a new issue if it still misbehaves in the last versions
