### ISSUE TITLE
Error in Readme configuration section

### ISSUE THREAD

**Issue by dacacioa** [yrutschle/sslh#29]
If you follow the instructions of the configuration section sslh doesn't start. You have to copy the basic.cfg or example.cfg file as /etc/default/sslh and modify the "listen" section with your settings (for example IP address).

**Comment by yrutschle** [comment]
Indeed, that section was quite outdated. I updated the documentation and startup scripts to use the configuration file instead: 88af6ebaeee9772d6ce2f947e2d2f66da7d5d739.
