### ISSUE TITLE
Config files do not work when compiled with libconfig-1.7.3

### ISSUE THREAD

**Issue by ravenexp** [yrutschle/sslh#292]
After upgrading system libconfig to 1.7.3 in Arch Linux the config file contents is completely ignored by sslh:

```
$ /usr/bin/sslh-fork -f -v 5 --config /etc/sslh.cfg
verbose: 5
foreground: 1
inetd: 0
numeric: 0
transparent: 0
timeout: 5
user: (null) <unset>
pidfile: (null) <unset>
chroot: (null) <unset>
syslog_facility: auth
on_timeout: ssh
listen [0]:
protocols [0]:
At least one target protocol must be specified.
```

**Comment by yrutschle** [comment]
Did it work with 1.7.2?

**Comment by ravenexp** [comment]
Yes, it broke when Arch Linux upgraded libconfig from 1.7.2 to 1.7.3.

**Comment by yrutschle** [comment]
When you change a lightbulb in an otherwise working car, and the new lightbulb doesn't work, do you assume the car is broken? :-)

This would rather sound like libconfig broke its API. The release notes talks about a change in `config_setting_lookup`. I'll have a look.

**Comment by yrutschle** [comment]
Ok, I can "sort of" reproduce, although in my case 1.7.3 segfaults.

**Comment by yrutschle** [comment]
`config_lookup()` no longer seem to work.

**Comment by yrutschle** [comment]
This looks like a libconfig issue, I reported it [here](https://github.com/hyperrealm/libconfig/issues/196)

**Comment by yrutschle** [comment]
thanks for reporting!
