### ISSUE TITLE
"At least one target protocol must be specified"

### ISSUE THREAD

**Issue by LaserEyess** [yrutschle/sslh#293]
Running into a very weird issue that suddenly appeared after I rebooted a long time running server. It appears `sslh-fork` can no longer read its configuration file properly, and I don't know why. This could be unrelated to sslh and be a distro/kernel issue, but I can't really tell given how confusing this is. 

I'm on Arch Linux using sslh 1.21c-1, with libconfig 1.7.3. 

To start, I usually run `sslh-fork` with a systemd service, the one that ships with sslh, but even running it directly on the command line does not help. Here's the service file but again it should not be relevant: https://0x0.st/-pxW.txt. Here is what happens when I run `sslh-fork --config /etc/sslh-fork.service --foreground --verbose=10` in a shell:
```
% sslh-fork  -F /etc/sslh.cfg --foreground --verbose=10                
verbose: 10
foreground: 1
inetd: 0
numeric: 0
transparent: 0
timeout: 5
user: (null) <unset>
pidfile: (null) <unset>
chroot: (null) <unset>
syslog_facility: auth
on_timeout: ssh
listen [0]:
protocols [0]:
At least one target protocol must be specified.
```
It really seems to not read the config at all, and when running with strace: https://0x0.st/-pxt.txt
```
openat(AT_FDCWD, "/etc/sslh.cfg", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=468, ...}, AT_EMPTY_PATH) = 0
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=468, ...}, AT_EMPTY_PATH) = 0
read(3, "# Default Arch configuration\n# Y"..., 8192) = 468
read(3, "", 4096)                       = 0
read(3, "", 8192)                       = 0
close(3)
```
It's reading the file, I guess? But then it just doesn't use any of the information?

Here's my config (IPs edited): https://0x0.st/-pxx.cfg

**Comment by LaserEyess** [comment]
Changing my systemd service to include
```
ExecStart=
ExecStart=/usr/bin/sslh-fork --transparent -t2 -f -n --ssh 1.2.3.4:223 --tls 1.2.3.4:4443 --openvpn 1.2.3.4:1194 -p 1.2.3.4:443
```
Worked. Transparent proxying works and everything.

**Comment by yrutschle** [comment]
Arch Linux probably upgraded libconfig to 1.7.3 in your back, which changed its API: this is reported here: https://github.com/yrutschle/sslh/issues/292 and solved in the last commit.

Please re-open if by bad luck that was not the case :-)

**Comment by LaserEyess** [comment]
Could have sworn I searched the exact string "At least one target protocol must be specified" before submitting this issue, yet the answer to my problem is right on the first page. 

I compiled from master and ran it with the config and confirmed it correctly reads it now. Sorry for the noise, I'll report this to Arch.
