### ISSUE TITLE
getpeername Transport endpoint is not connected

### ISSUE THREAD

**Issue by greggailly** [yrutschle/sslh#298]
Hi,
When trying to connect by ssh over https we get the following error: `kex_exchange_identification: read: Connection reset by peer`.
When looking at sslh logs it seems that it is coming from getpeername: `common.c:611:getpeername:107:Transport endpoint is not connected`
This error happens for one specific "client" server, we have other servers which manage to connect but we can't seem to figure out why this one doesn't.
Any hints would be much appreciated !
Cheers

**Comment by yrutschle** [comment]
what version are you using? there is no getpeername at line 611 on HEAD :-)
I would guess:
- the connection drops off for some other reason, and sslh finds out when calling getpeername
- You're using libwrap, and it's failing for some reason.
The error message directs to the first idea. Is the connection reliable with that same client and same server in a direct connection without sslh?

**Comment by greggailly** [comment]
We are using the docker image found here: https://hub.docker.com/r/riftbit/sslh/ which seems a little far back.
That is probably why there is a difference in the line number.

We tried to make a direct ssh connection and doesn't seem to work either so you are probably right about the connection drop off.
So far we are guessing the problem might be caused by the corporate firewall on the client side so we will find another way to communicate between the two servers.

I'll close this issue and thanks for the tips.

**Comment by yrutschle** [comment]
It's possible the firewall observes the contents of the connection, determines it's not HTTPS and breaks it. You can further encapsulate ssh in TLS with proxytunnel / stunnel, described [here](https://github.com/yrutschle/sslh/blob/master/doc/config.md#using-proxytunnel-with-sslh)
