### ISSUE TITLE
Segmentation fault (core dumped) in 64 bits

### ISSUE THREAD

**Issue by dacacioa** [yrutschle/sslh#30]
When you start the program in CentOS 6.5 64 bits crashes with a "Segmentation fault". It doesn't happen in CentOS 6.5 32 bits.
I found that the problem is located in the timeout parameter of config file. If I put it in this way:
- timeout = 2;

It crashes, but if I put:
- timeout = "2";

It works.
The both options works in CentOS 6.5 32 bits.
It seems to be a bug in the 64 bits version of libconfig. Maybe you can modify the .cfg files with the quotes in the timeout parameter.

**Comment by yrutschle** [comment]
Thanks for the report, fixed in 43d2db9123dc4210a76cf053e034305ef595f10e.

**Comment by TrueXakeP** [comment]
Broken again in 1814bcb

**Comment by yrutschle** [comment]
grrr I guess I'll have to re-dive into the docs of libconfig and pick the actual right one and report a bug to libconfig... Or I'll just keep flip-flopping between the two, forgetting each time why it is the way it is :)

**Comment by licaon-kter** [comment]
Seeing the same on Centos 6.10 64bit w/ libconfig 1.3.2

**Comment by yrutschle** [comment]
Still  on timeout setting? Do you have any other integer setting, e.g. verbose? If not, can you try to add one (e.g. verbose: 1)? Finally, can you provide a backtrace:

```
gdb --args sslh --foreground -F myconfig.cfg
gdb> run
<crash, hopefully>
gdb> bt
```

(The questions might seem weird, I'd like to work out if it's something libconfig related or sslh-related. If it's libconfig related, I'll want to build a minimum crashing example to report the bug to libconfig. But I have a hard time believing integers wouldn't work).

**Comment by yrutschle** [comment]
Assuming this is gone with the libconfig evolutions. Re-open otherwise.
