### ISSUE TITLE
Can't listen for TCP and UDP simultaneously

### ISSUE THREAD

**Issue by 44lr** [yrutschle/sslh#301]
`listen:
(
        { host: "0.0.0.0"; port: "27015" },
        { host: "0.0.0.0"; port: "27005" },
        { host: "0.0.0.0"; is_udp: true; port: "27015" }
);
`
This configuration results in the following error:
`
0.0.0.0:27015:bind: Address already in use
`
This works when not defining the "is_udp" one, but I need both TCP and UDP for connections to work properly.
Similar usage can be seen in example.cfg for the port 443 @ lines 27 and 29 (which I'm assuming it worked then)
Is this the result of a new update or am I doing something wrong?

**Comment by iamdoubz** [comment]
I have seen this happen before when you try to stop the service (but it doesn't actually kill the service...). You should check if it is running as yrutschle said using `sudo netstat -peanut | grep :27015` and I also like to use `sudo htop` and filter for "sslh".

**Comment by 44lr** [comment]
> I have seen this happen before when you try to stop the service (but it doesn't actually kill the service...). You should check if it is running as yrutschle said using `sudo netstat -peanut | grep :27015` and I also like to use `sudo htop` and filter for "sslh".

Yep, that solved it! Thanks!
