### ISSUE TITLE
sslh prints to stderr in inetd mode

### ISSUE THREAD

**Issue by qouoq** [yrutschle/sslh#303]
I've been using the following configuration for a while, 5 months if I recall correctly (at that time I started to use an `sslh.cfg` file after discovering the `log_level` option):

_/etc/stunnel.conf_
````dosini
[sslh]
accept   = 443
exec     = /usr/bin/sslh
execArgs = sslh -i -F/etc/sslh.cfg
````

_/etc/sslh.cfg_
````cfg
timeout: 2;

listen:
(
    { host: "0.0.0.0"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "22"; probe: "builtin"; log_level: 0; },
     { name: "http"; host: "localhost"; port: "80"; probe: "builtin"; log_level: 0; }
);
````

It works with sslh 1.21c, but not with 1.22.b.

With 1.22.b, I receive strange messages with a browser, such as:

    Unknown settings:
    /protocols[0]/probe:builtin
    /protocols[1]/probe:builtin
    
    HTTP/1.1 200 OK

followed by the rest of the http headers and the html.
`curl -v` won't display the headers, I assume it can't parse them, so it just says:

    curl: (1) Received HTTP/0.9 when not allowed

I didn't manage to get more details from sslh, I tried different combinations of switches (`--verbose=1` and `--verbose=3` in `stunnel.conf`, `verbose: True` at header and `log_level: 3` by protocol in `sslh.cfg`), but I only get the standard log lines:

    sslh[9438]: http:connection from localhost.localdomain:55729 to localhost.localdomain:50139 forwarded from localhost.localdomain:42294 to localhost.localdomain:http

**Comment by yrutschle** [comment]
You're saying that this:
```
Unknown settings:
/protocols[0]/probe:builtin
/protocols[1]/probe:builtin
```

displays... in the browser?

**Comment by yrutschle** [comment]
those messages are printed on stderr, afaik inetd should only use stdout as output of the process... otherwise, there is much to change as stderr gets a lot of messages...

**Comment by qouoq** [comment]
Yes it does :D

So I just realized that the `probe: "builtin"` part is not referenced in the sample configs anymore, and that it must have hanged in my local config (as comments kept for reference) for years possibly (I tried to use a cfg through stunnel quite a long time ago before getting it to work a few months ago).
I removed these bits, and now it's working with 1.22.b.

Interestingly, it first failed with the browser displaying

    Unknown settings:
    /verbose:[true]

presumably due to my putting an incorrect `Verbose: true` in sslh.cfg. Changing it `Verbose: 0` fixed it.

So it seems to me that somehow a change was done between 1.21c and 1.22.b that leads to sslh sending the part of the config it cannot parse, when called by stunnel with a config file?

At any rate, the problem is solved.

**Comment by qouoq** [comment]
Got it. I actually was debugging my stunnel `execArgs` command line through my browser just before, so it makes sense..

**Comment by yrutschle** [comment]
actually I think it's a terrible decision on inetd's part: it means errors might be directed towards attacker. I suppose the behaviour was originally decided to make it easier to get the services to work (you get errors in your browser until it works), but it means on border cases an attacker will get information they shouldn't, much like Web applications should not dump queries and databases and such on the Web connection when something goes wrong.

Nevermind: I have wanted to review `sslh`'s logging strategy and verbose levels for a while now, so I'll make it silent on stderr as a side effect I suppose.
