### ISSUE TITLE
HTTPS Behind a VPN

### ISSUE THREAD

**Issue by andrewfer000** [yrutschle/sslh#304]
Hi.
I am trying to host a HTTPS server behind this proxy on a host connected via a VPN. Here is what it looks like.

Laptop (webhost, connects to VPS over the VPN) -> VPS (running VPN server and SSLH) -> User

I tried using SoftEtherVPN and WireGuard as the VPN platforms.

I followed the instructions from https://github.com/yrutschle/sslh/blob/master/doc/tproxy.md (ignored the stunnel and ssh stuff).

site1.mydomain.club (on the same server as proxy) works fine. However site2 (remote) does not.  here is the error:
```
Sep 02 19:11:34 mydomain.club sslh[43755]: forward to tls failed:connect: Connection timed out
Sep 02 19:11:34 mydomain.club sslh[43755]: sslh-fork.c:115:connect: Connection timed out
Sep 02 19:11:34 mydomain.club sslh[43755]: forward to tls failed:connect: Connection timed out
```
Here is my SSLH config file
```
#verbose: true;
foreground: true;
inetd: false;
numeric: true;
transparent: true;
timeout: 2;
user: "sslh";
pidfile: "/var/run/sslh.pid";
#chroot: "/var/empty";

listen:
(
{ host: "158.6x.xxx.xxx"; port: "443"; }
);

# sslh demultiplexes based on the Protocol and Hostname
protocols:
(
{ name: "tls"; sni_hostnames: [ "site1.mydomain.club" ]; host: "172.18.0.1"; port: "4434"; log_level: 1; },
{ name: "tls"; sni_hostnames: [ "site2.mydomain.club" ]; host: "172.18.0.2"; port: "4434"; log_level: 1; }
);
```
Iptables rules on the remote system (aka my laptop)
```
iptables -t mangle -N SSLHSSL
iptables -t mangle -A OUTPUT -o wg0 -p tcp -m multiport --sport 4434 -j SSLHSSL
iptables -t mangle -A SSLHSSL --jump MARK --set-mark 0x1
iptables -t mangle -A SSLHSSL --jump ACCEPT
ip rule add fwmark 0x1 lookup 100
ip route add default via 172.18.0.1 table 100
ip route flush cache
```

I am using the latest code as of 3 days ago.

**Comment by andrewfer000** [comment]
Tried removing Timeout. Did not work.

**Comment by andrewfer000** [comment]
Fixed it by removing transparent. So transparent does not work for some reason? Anyone got a solution.

**Comment by yrutschle** [comment]
oh, I'm just thinking of this: it's unclear to me how transparent proxy should even work in case of VPN connections, and it probably would affect the iptables rules. I personally don't understand the iptable stuff enough to have opinions on that.
