### ISSUE TITLE
SSH won't work with Transparent enabled.

### ISSUE THREAD

**Issue by andrewfer000** [yrutschle/sslh#305]
Followed https://github.com/yrutschle/sslh/blob/master/doc/tproxy.md

TLS works fine on the same host while SSH does not work unless Transparent is off. Using the latest compiled code. Also tested the version in the Ubuntu 20.04 repository with the same results.

**Comment by yrutschle** [comment]
There is a different setup described [here](https://github.com/yrutschle/sslh/blob/master/doc/config.md#transparent-proxy-support)
Note the warning:

> Note that getting this to work is very tricky and detail-dependant: depending on whether the target server and sslh are on the same machine, different machines, or different dockers, and tool versions, all seem to change the required network configuration somewhat. If it doesn't work, it's almost certain that the problem is not linked to sslh but to the network setup that surrounds it.

I do need to clarify the documentation on what's been tested and reported to work. In your case, I can't think how it would work to TLS and not SSH, if both end servers are "similar" (both located on the same host).

**Comment by andrewfer000** [comment]
Yeah sorry I got it to work. I forgot to put port 22 with the other ports in the iptables rules. All is good now!
