### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by andrewfer000** [yrutschle/sslh#306]
I have a few short questions?

Does HTTP only work with one host? Or does it allow hostnames  like TLS? I know "regex" works for http but I was wondering if I can use the "http" one since it makes more sense. Maybe this is something that can be implemented?

Does OpenVPN support sni_hostnames? I added the "sni_hostnames:" option to the "OpenVPN" service and SSLH didn't spit any errors. But I was curious if that did anything? At the moment I cannot test myself. I do not want to use time if It will not work. Would there be a way to do it with regex?

Does SOCKS5 also work with ShadowSOCKS?

**Comment by andrewfer000** [comment]
For the ShadowSOCKS question, I tested it and it works. 
That's epic! SSLH is such an underrated tool! A must have for all Linux servers!

**Comment by yrutschle** [comment]
* the HTTP probe forwards to only one host. The FAQ shows how to do what you want with regex. I'm not too keen to implement that, 
* `sni_hostname`  is a TLS extension, so no, it won't work with anything else (`sslh` should probably warn if you're using it with another probe, but that's... complicated)
* Great. I don't know what ShadowSOCKS is :-)

**Comment by yrutschle** [comment]
I'm creating issue #307 for the second point, you're not the first one to be confused by that (at least the documentation should be clear, otherwise only TLS experts will understand why it doesn't work)

**Comment by andrewfer000** [comment]
ShadowSOCKS is basicly An encrypted SOCKS5 tunnel with UDP support xD. It's a pretty neat VPN alternative.

Also would it be possible to have multiple openvpn servers using somthing like regex in the same manner http works? I see in some of your older examples you use regex for OpenVPN so I was curious if there was a way to extract the hostname like in http.

**Comment by yrutschle** [comment]
If I recall properly, OpenVPN is all encrypted, and/or doesn't include host names, so no, you really can't do virtual hosting with it.

**Comment by yrutschle** [comment]
please re-open (or re-post as individual posts) if some questions are still alive
