### ISSUE TITLE
Forwarding non-ssh traffic to ssh server

### ISSUE THREAD

**Issue by SGNoc** [yrutschle/sslh#309]
I am seeing logs from my ssh server where the sslh is forwarding traffic that the ssh server does not identify as valid SSH traffic. I am using v 1.21. I have the sslh running on the web server and forwarding ssh traffic to another server handling ssh. 

I was originally receiving a large amount more of non-ssh traffic being forwarded to the ssh server, but I moved the tls protocol in the config file to the top, so it would match first. That seemed to fix the majority, but it still occurs less frequently. I have not been able to identify the specific traffic that causes the mismatch other than from the auth.log file below showing "bad protocol version identification".

Here are the protocols in the config:

> protocols:
(
     { name: "tls"; service: "https"; host: "10.10.33.2"; port: "4443"; fork: true; transparent: true; },
     { name: "ssh"; service: "ssh"; host: "10.10.5.101"; port: "222"; fork: true; transparent: false; },
     { name: "openvpn"; service: "openvpn"; host: "10.10.33.1"; port: "1194"; fork: true; transparent: false; }
);

Here is what I am seeing on the ssh server's log file:

> auth.log:Oct  3 20:14:54 sshd[14704]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44518
auth.log:Oct  3 20:20:29 sshd[14872]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44520
auth.log:Oct  3 20:20:50 sshd[14876]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44522
auth.log:Oct  3 20:21:14 sshd[14879]: Did not receive identification string from XX.XX.XX.X port 44524
auth.log:Oct  3 20:21:16 sshd[14891]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44526
auth.log:Oct  3 20:21:20 sshd[14894]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44528
auth.log:Oct  3 20:21:52 sshd[14899]: Did not receive identification string from XX.XX.XX.X port 44530
auth.log:Oct  3 20:21:54 sshd[14903]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44532
auth.log:Oct  3 20:21:58 sshd[14906]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44534
auth.log:Oct  3 20:22:01 sshd[14911]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44536
auth.log:Oct  3 20:23:37 sshd[14936]: Did not receive identification string from XX.XX.XX.X port 44538
auth.log:Oct  3 20:23:40 sshd[14939]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44540
auth.log:Oct  3 20:23:56 sshd[14943]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44542

Here is what I am seeing on the sslh/web server logs: 

> Oct  3 20:20:26 XX.XX.XX.X sslh[1893]: accepted fd 5
Oct  3 20:20:28 XX.XX.XX.X sslh[1893]: timed out, connect to ssh
Oct  3 20:20:29 XX.XX.XX.X sslh[1893]: connecting to XX.XX.XX.X:222 family 2 len 16
Oct  3 20:20:29 XX.XX.XX.X sslh[1893]: ssh:connection from 49-228-243-0.24.nat.tls1a-cgn01.myaisfibre.com:7969 to XX.XX.XX.X:https forwarded from XX.XX.XX.X:44520 to pi.hole:222
Oct  3 20:20:29 XX.XX.XX.X sslh[1893]: flushing deferred data to fd 3
Oct  3 20:20:29 XX.XX.XX.X sslh[1893]: client socket closed

**Comment by SGNoc** [comment]
This may be related to timeout, as a config issue on my end. I did not see in the example.cfg that the default timeout points to SSH. I have changed my timeout to tls. This config change seems to have worked. I will continue to monitor, but over the last 12 hours I have not had any more logs on my ssh server as listed above.

`on_timeout: "tls";`

**Comment by yrutschle** [comment]
It would be more correct to change the timeout to 5s or more. Timeout works as:
- sslh receives a connection
- when data comes from the client, sslh probes on it
- if no data has arrived after `timeout`, sslh forwards the connection to the `on_timeout` protocol.
Thing is, by specification TLS is not supposed to timeout (a TLS client opens a connection, then starts a handshake) while SSH might (an SSH client opens a connection and may wait for the server to send its banner), which is why ssh is one of the rare protocols where timeout is correct.

What may happen on your setup is that a lot of your TLS clients are 'slow', either because of network congestion, or CPU overload: I remember some TLS clients open the TCP connection before they start computing the crypto parameters, which can take "some" time on a slow CPU.

**Comment by SGNoc** [comment]
I've changed the timeout form 2s to 5s and back from TLS to SSH. I'll see how to logs look in another 12 hours.

What you stated makes perfect sense. I am suspecting that the non-SSH traffic that is timing out is in fact TLS traffic, but from sources that are probing my web server. I'm not sure if the probing intentions are to detect open ports or active web servers, but I think they are intentionally opening a connection and then not continuing with the handshake or sending an invalid handshake.

That would explain the two cases I'm seeing in the logs:

```
Oct  3 20:23:37 sshd[14936]: Did not receive identification string from XX.XX.XX.X port 44538
Oct  3 20:23:40 sshd[14939]: Bad protocol version identification '\026\003\001' from XX.XX.XX.X port 44540
```

With the configuration set to timeout after 2s to TLS, I still had not received another error in the logs. I will see what 12 hours shows in the logs with the updated configuration. If what I suspect is true, I may need to revert back to a "less correct" configuration with the timeout to TLS, unless there is a simpler method to handle scenarios where there is no identification string or a bad protocol identification string, and still allow timeouts to go to SSH? That way I can handle the suspected "probing" and still allow for a proper timeout to SSH.

**Comment by SGNoc** [comment]
So after some more research, it looks like the “\026\003\001" bytes indicate an attempt to initiate a TLS connection, the beginning of the handshake? So it does seem like this is the start of a TLS session that is then abandoned without being closed, and I'm sure that this is probing activity.

So this has thinking it would be better to see if there is a way to handle the "no identification" string and the \026\003\001 being sent and then left hanging. Possibly with regex?

**Comment by SGNoc** [comment]
I've been monitoring the logs, and it appears you were correct on the timeout solving the issue. With the timeout set to 5 and pointing to SSH. I've had only 2 connections get logged, which is far better than the amount I was getting in a 12 hour period.

Here are the SSH server logs:
```
auth.log:Oct  5 10:32:52 sshd[16245]: Did not receive identification string from XX.XX.XX.X port 55374
auth.log:Oct  5 10:33:06 sshd[16256]: Did not receive identification string from XX.XX.XX.X port 55376
```

And the SSLH logs: 
```
Oct  5 10:32:41 sslh[4700]: ssh:connection from hn.kd.ny.adsl:29249 to XX:XX:XX:X:https forwarded from XX:XX:XX:X:55374 to XX:XX:XX:X:222
Oct  5 10:33:03 sslh[4700]: ssh:connection from hn.kd.ny.adsl:10442 to XX:XX:XX:X:https forwarded from XX:XX:XX:X:55376 to XX:XX:XX:X:222
```

Unless there is anything that can be done to solve these types of logs, I believe this will be solved with simple configuration changes.

**Comment by SGNoc** [comment]
> 
> 
> I've been monitoring the logs, and it appears you were correct on the timeout solving the issue. With the timeout set to 5 and pointing to SSH. I've had only 2 connections get logged, which is far better than the amount I was getting in a 12 hour period.
> 
> Here are the SSH server logs:
> 
> ```
> auth.log:Oct  5 10:32:52 sshd[16245]: Did not receive identification string from XX.XX.XX.X port 55374
> auth.log:Oct  5 10:33:06 sshd[16256]: Did not receive identification string from XX.XX.XX.X port 55376
> ```
> 
> And the SSLH logs:
> 
> ```
> Oct  5 10:32:41 sslh[4700]: ssh:connection from hn.kd.ny.adsl:29249 to XX:XX:XX:X:https forwarded from XX:XX:XX:X:55374 to XX:XX:XX:X:222
> Oct  5 10:33:03 sslh[4700]: ssh:connection from hn.kd.ny.adsl:10442 to XX:XX:XX:X:https forwarded from XX:XX:XX:X:55376 to XX:XX:XX:X:222
> ```
> 
> Unless there is anything that can be done to solve these types of logs, I believe this will be solved with simple configuration changes.

**Comment by SGNoc** [comment]
I've increased the timing slightly and still occasionally get a bad protocol error. I'm still getting a varying amount of the "did not receive identification string", which querying the IP addresses shows many reports of malicious activity. So I believe this to be more of a proper configuration on my end than an issue with SSLH.

Unless there is somehow a way to handle the "did not receive identification string" on the ssh forwarder in SSLH, which I don't know if that is even possible. If so, maybe some future feature request?

In any case, I'll close this out as just a mis-configuration instead of an SSLH issue. Thanks for the help.
