### ISSUE TITLE
What is sslh-ev?

### ISSUE THREAD

**Issue by iamdoubz** [yrutschle/sslh#312]
What is/are the main difference(s) between sslh-select and sslh-ev?

I am currently using `sslh-ev` and it wonderfully has enabled me to proxy UDP traffic as well as TCP traffic, all on port 443 🥇 

Thanks for an awesome piece of software.

**Comment by licaon-kter** [comment]
Read https://github.com/yrutschle/sslh/blob/master/ChangeLog and commits messages

**Comment by iamdoubz** [comment]
@licaon-kter Thank you!

https://github.com/yrutschle/sslh/blob/4e72800f2e7a6be83783faff25c672ec9d3bf614/ChangeLog#L1-L5

Now, _which_ protocols can be forked? Probably only TCP ones right?

**Comment by yrutschle** [comment]
I added some comments in adaf407b8ac2bafd8fbc9333e4026246a2864e82.

Yeah, UDP can't fork, I'm pretty sure it's impossible to do; the forking option should be silently ignored.

**Comment by iamdoubz** [comment]
This is a really dumb question, and I know I'm better than this, but if I want to `sudo make install` the sslh-ev version, how do I do that? Right now, it makes sslh-fork the default install candidate. Or, is it as simple as "copy and paste" the sslh-ev binary to `$(DESTDIR)/$(BINDIR)/sslh`?

**Comment by yrutschle** [comment]
Yes. All that matters is that it's in the path for whatever will start it. Or use absolute paths when starting it, which is good practice anyway.

**Comment by yrutschle** [comment]
I just thought: the 'profiling' message could come from libev, if it's compiled with gprof support for some reason...

**Comment by yrutschle** [comment]
either way, it's unrelated to the question, which I hope is fixed with the additional notes.
