### ISSUE TITLE
UDP (OpenVPN + Wireguard)

### ISSUE THREAD

**Issue by prismplex** [yrutschle/sslh#316]
Hi community,
this project is really great. I have been using it for about 5 years with pleasure. With the recently added UPD feature I would like to implement OpenVPN UDP and Wireguard, but I am struggling to get it to work.

I am using `sslh-select` with the following configuration file:
*`some-port`, `tcp-port`, `udp-port` are the corresponding service ports I can connect to directly without problems. With `sslh`I get `Waiting for server response`in the case of OpenVPN. Wireguard does not receive a response. 
```
timeout: 5;
transparent: true;

listen:
(
    { host: "hostname"; port: "443"; },
    { host: "hostname"; is_udp: true; port: "443"; }
);

protocols:
(
# Forward TCP
     { name: "ssh"; service: "ssh"; host: "localhost"; port: "some-port"; keepalive: true; fork: true; tfo_ok: true },
     { name: "openvpn"; host: "localhost"; port: "tcp-port"; tfo_ok: true },
     { name: "xmpp"; host: "localhost"; port: "some-port"; tfo_ok: true },
     #{ name: "http"; host: "localhost"; port: "80"; tfo_ok: true },
     { name: "tls"; host: "localhost"; port: "4443"; tfo_ok: true },
     #{ name: "anyprot"; host: "localhost"; port: "443"; tfo_ok: true },

# Forward UDP
     { name: "openvpn"; host: "localhost"; is_udp: true; port: "udp-port" }, #OpenVPN
     { name: "regex"; host: "localhost"; is_udp: true; port: "some-port"; regex_patterns: [ "\x01\x00\x00\x00" ] }, #Wireguard
);
```

Can somebody help me please?

**Comment by utoni** [comment]
Does:
```
{ name: "openvpn"; service: "openvpn"; host: "127.0.0.1"; port: "1194"; keepalive: true; fork: true; tfo_ok: false; }
```
work for you?

**Comment by coolwanglu** [comment]
I recent did [something similar](https://blog.wang-lu.com/2022/05/setting-up-sslh-as-transparent-proxy.html).

For WireGuard, maybe you need to set `AllowedIPs=0.0.0.0/0` in the conf file, since sslh in the transparent mode. 

If possible, please also share your config of WireGuard.

**Comment by prismplex** [comment]
> Does:
> 
> ```
> { name: "openvpn"; service: "openvpn"; host: "127.0.0.1"; port: "1194"; keepalive: true; fork: true; tfo_ok: false; }
> ```
> 
> work for you?

Did not have time to investigate it until now.
Unfortunately I am not getting any server response. OpenVPN via port 1194 works perfectly in UDP mode, but switching it to port 443 does not generate any connection/response.

**Comment by prismplex** [comment]
Turning off transparent mode does not make any difference, still no route to host. TCP is working fine with same settings just TCP and another port. Both ports 1194 and 1195 are open in my router and server firewall, proven by the possibility to connect from outside without problems.

This is my OpenVPN config, working perfectly by direct connection via port 1194.
```
server 192.168.255.0 255.255.255.0
verb 3
key /etc/openvpn/pki/private/vpn.prismplex.com.key
ca /etc/openvpn/pki/ca.crt
cert /etc/openvpn/pki/issued/vpn.prismplex.com.crt
dh /etc/openvpn/pki/dh.pem
tls-auth /etc/openvpn/pki/ta.key
key-direction 0
keepalive 10 60
persist-key
persist-tun

proto udp
# Rely on Docker to do port mapping, internally always 1194
port 1194
dev tun0
status /tmp/openvpn-status.log

user nobody
group nogroup
comp-lzo no

### Route Configurations Below
route 192.168.254.0 255.255.255.0

### Push Configurations Below
push "block-outside-dns"
push "dhcp-option DNS 192.168.120.1" #local dns
#push "dhcp-option DNS 84.200.69.80"
#push "dhcp-option DNS 84.200.70.40"
push "comp-lzo no"
```

**Comment by prismplex** [comment]
> I recent did [something similar](https://blog.wang-lu.com/2022/05/setting-up-sslh-as-transparent-proxy.html).
> 
> For WireGuard, maybe you need to set `AllowedIPs=0.0.0.0/0` in the conf file, since sslh in the transparent mode.
> 
> If possible, please also share your config of WireGuard.

Thank you, already did this. And as OpenVPN is also not working I think there is a UDP protocol (config) issue somewhere.

**Comment by utoni** [comment]
A quick research ended up with two major issues:

- `sslh-select` does not work with UDP, `sslh-ev` does
- `openvpn` UDP probe differs from TCP

**Comment by utoni** [comment]
@prismplex
PR #338 fixes openvpn udp detection (works fine with `sslh-ev`)

**Comment by AntonOfTheWoods** [comment]
Did anyone get this wireguard to work? It would be totally wonderful to have a working example for that!

**Comment by utoni** [comment]
Working on a WireGuard probe, because I need that as well.

**Comment by utoni** [comment]
@AntonOfTheWoods 

Can you verify if PR #345 works for you?
I was not able to test it yet due to time restrictions. =)

**Comment by AntonOfTheWoods** [comment]
@utoni it has turned into a huge mission trying to first get things compiled on Ubuntu 22.04 and the getting it to start without erroring out. The instructions seem to be old and incomplete, or maybe to just not work for Ubuntu

**Comment by prismplex** [comment]
> @prismplex PR #338 fixes openvpn udp detection (works fine with `sslh-ev`)

Thank you for working on this. I am using Arch Linux and unfortunately the current package does not provide `sslh-ev`. I haven't had time to manually install the latest version yet. Wanted to wait for an updated precompiled Arch Linux package.

**Comment by utoni** [comment]
@prismplex 
It should now also work with `sslh-select` since PR #340 fixed the bug that affected you.

**Comment by prismplex** [comment]
Alright, thank you!
Since the Arch Linux packages will only be upgraded after version release I will have to wait for an official release. If I have time I will try to compile the prelease/master by myself

27 Aug 2022 15:21:12 Toni ***@***.***>:

**Comment by iamdoubz** [comment]
I also want to add that in your .cfg file in your "UDP" section, you also need to include `is_udp: true;`.

**Comment by HolyMacarony** [comment]
Hello :)
did anyone get this running by now ? ubuntu 22.04 also does only provide sslh and sslh-select and cannot get OpenVPN running in UDP mode. Would love to use Wireguard as well.

**Comment by AntonOfTheWoods** [comment]
@HolyMacarony it seems to work ok but there were definitely some edge cases that crash still, particularly with bad config. I actually didn't end up being able to use it because they closed UDP on me...

**Comment by thanosz** [comment]
Hello, it seems that it is still not working. Is there any update?

**Comment by iamdoubz** [comment]
This is totally off topic, but similar, read how the GFW passively blocks Shadowsocks proxies. Would be best to implement the reverse of it into sslh though:

https://gfw.report/publications/usenixsecurity23/en/

**Comment by yrutschle** [comment]
Closing this and moving the Shadowsocks discussion in another issue
