### ISSUE TITLE
[Feature request] Is ist possible to disable the downstream check? 

### ISSUE THREAD

**Issue by milkpirate** [yrutschle/sslh#320]
I am having a setup with several downstream servers to handle the various protocols which are on seperate hosts/containers. Sadly when one server is, for whatever reason, dysfunctional and sslh starts, it chechks if all downstream server are available and if one of them is not, it refuses to start, rendering all other services unusable as well.

So an option to disable that check per service/protocol (or globally) would be nice to make the whole setup more resilient. Would that be possible? Or is it even already possible?

**Comment by yrutschle** [comment]
ok, that's not quite what's happening: sslh *resolves* the target names at startup: it doesn't care if the server is present or even reachable, but it needs to be able to resolve the name into an IP address.

I can think of two cases where that would be a problem:
- We're using servers that retrieve a dynamic IP through a DHCP that manages the DNS as well (I guess that's your case)
- The target is outside the local network and may legitimately change IP address (even during sslh life)

I suppose it would be possible to add a per-protocol setting to perform address resolution upon forwarding, but that means we inccur the cost of resolution for each connection.

This is not in my current roadmap, but probably achievable at some point in the future :-)

The simplest workaround is to ensure that your server name can be resolved, or use the IP address directly, if it's fixed.

**Comment by milkpirate** [comment]
Puhh... its a docker-compose setup. It uses the internal docker nameserver. I really have to look if there so much control over it brought out. Hm... I might find time to dig into your source and be able to prepare a PR. If you can give me hint to the relevant lines?

**Comment by yrutschle** [comment]
yes:
* in `sslhconf.cfg`, add a new config option boolean under `protocols`, e.g. "dyndns" (? something that indicates there will be a DNS lookup each time the connection is forwarded). This will add an int cfg.protocol.dyndns
* `sslh_main.c:config_protocols()`: don't call `resolve_split_name()` if dyndns is set
* `common.c:connect_addr()`: if dyndns, call `resolve_split_name()`, probably after `getpeername()`.

... that should be it.

**Comment by milkpirate** [comment]
@yrutschle please review: https://github.com/yrutschle/sslh/pull/323
