### ISSUE TITLE
no ipv6

### ISSUE THREAD

**Issue by Yamakaky** [yrutschle/sslh#33]
Hi

I have a problem to use ipv6 with your software. (let say my ipv6 is ::1 and my ipv4 is 1.1.1.1) When I configure it to listen to 1.1.1.1:443, all works fine. When it's localhost:443, I can't connect at all. If I add [::1]:443, it outputs an error saying that the argument is invalid. Any idea ?

Thanks for your awesome piece of software.

I use sslh v1.16

**Comment by yousefamar** [comment]
Apologies for necroposting, but I didn't want to create a new issue since I'm having the same problem. The only difference is that I'm running with inetd support, so I'm forced to listen to all addresses, so @Yamakaky's solution doesn't work. Is there a way to have both IPv4 and IPv6 work at the same time? I can't run a separate instance because I get the same error that @Yamakaky got when he tried that.

**Comment by yrutschle** [comment]
> The only difference is that I'm running with inetd support, so I'm forced to listen to all addresses

I don't think that can be the same issue: with inetd, it is
inetd that listens, then when there is an incoming
connection, it runs a new sslh and connects sslh's stdin to
the incoming socket; from sslh point of view, there isn't
even the notion of a network connection.

So you shouldn't need to specify any listening addresses;
sslh won't use them anyways.

**Comment by yousefamar** [comment]
Oh I see, thanks for the info. I was going by (presumably outdated) info in my build's `README.Debian`:

```
Inetd support
--------------------------

sslh have inetd support since 1.7a release.
If used, inetd bind 443/tcp on all addresses, so your https server must bind
an another unused port (444/tcp proposed).

 -- Guillaume Delacour <gui@iroqwa.org>  Mon, 26 Jul 2010 23:40:01 +0200
```

I'll investigate some more, thanks.

**Comment by yrutschle** [comment]
No, it's all correct. *inetd* binds (and listens) all addresses for 443 so *httpd* (e.g. Apache) must bind another port; *sslh* doesn't bind anywhere and is started by inetd.
