### ISSUE TITLE
common.c:803:chroot: No such file or directory

### ISSUE THREAD

**Issue by AntonOfTheWoods** [yrutschle/sslh#346]
I am trying to compile and run on Ubuntu 22.04. I have followed the instructions as best I could, and also tried adding /usr/sbin to the chroot directory. I keep getting this error when trying to run

```
Aug 27 18:27:01 sg3 systemd[1]: Starting LSB: sslh proxy ssl & ssh connections...
Aug 27 18:27:01 sg3 sslh[4825]: Start services: sslh
Aug 27 18:27:01 sg3 sslh[4826]: Unknown settings:
Aug 27 18:27:01 sg3 sslh[4826]: /verbose:0
Aug 27 18:27:01 sg3 sslh[4827]: common.c:803:chroot: No such file or directory
Aug 27 18:27:01 sg3 sslh[4827]: common.c:803:
Aug 27 18:27:01 sg3 sslh[4828]: Started sslh
Aug 27 18:27:01 sg3 systemd[1]: Started LSB: sslh proxy ssl & ssh connections.
```

There is no process after this.

**Comment by utoni** [comment]
How did you compile&run `sslh` ?

**Comment by AntonOfTheWoods** [comment]
```
sudo apt install build-essential libconfig-dev libwrap0-dev libsystemd-dev libcap-dev libbsd0 libbsd-dev libev-dev libpcre2-dev libudev-dev
```

I tried lots of things... Obviously starting with manual

```
sudo cp sslh-fork /usr/local/sbin/sslh
sudo cp basic.cfg /etc/sslh.cfg
sudo cp scripts/etc.init.d.sslh /etc/init.d/sslh
update-rc.d sslh defaults
```

Then
```
sudo make install
```

Then

```
export PREFIX=usr/local && sudo -E make install-debian
```

Then tried adding to `/etc/init.d/sslh` 

```
PATH="$PATH:/usr/sbin"
...
PREFIX=usr/local
```

**Comment by utoni** [comment]
Can post the contents of `/etc/sslh.cfg` ? Seems that the chroot directory does not exist.

**Comment by AntonOfTheWoods** [comment]
@utoni , as I am a beginner, I just followed the instructions, so I started with the `example.cfg`. The issue was present starting with that and I wasn't able to get rid of it.

What are you testing with? I have recently moved to mainland China so there are lots of downloads that can't be done using normal means (in normal amounts of time).

**Comment by AntonOfTheWoods** [comment]
The problem is that https://github.com/yrutschle/sslh/blob/master/example.cfg#L13 doesn't work. Commenting out that line at least gets the process to start.

The install and run instructions definitely need some love...
