### ISSUE TITLE
SSLH automatically exits (or does not start)

### ISSUE THREAD

**Issue by mxmvncnt** [yrutschle/sslh#347]
Hello,

 I am trying to set up SSLH on my Ubuntu 22.04.1 server to use port 443 and 80 with XMPP to bypass restrictive firewalls as well as a web server, but I am having a lot of trouble. Initially, nothing worked, the program started and the ports all looked good, SSLH was listening on the host's ip, and the rest were listening on 127.0.0.1 on their respective ports. I suspected that is because the version on the debian repos is, expectedly, 4 years out of date... So I checked the github tags and saw there was a much newer release, so I try that, compile it and the version is good, the configs seem to work as there are no errors.

Here are my configuration files (click to expand them)
<details>
  <summary markdown="span"><code>/etc/sslh.cfg</code> (expand)</summary>
This one is from the Debian.org page explaining how to use the Prosody XMPP server.
<pre><code>
ubuntu@ubuntu-24go:~$ cat /etc/sslh.cfg 
verbose: 1;
foreground: false;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
#pidfile: "/var/run/sslh/sslh.pid";

listen:
( 
	{ host: "<server external ip>"; port: "443"; } 
);

protocols:  
(
	{ name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 0;},
	{ name: "tls"; host: "localhost"; port: "443";},
	{ name: "xmpp";    host: "localhost"; port: "5222"; },
	{ name: "timeout"; host: "localhost"; port: "443";}
);
 
on-timeout: "timeout";
</pre></code>
</details>
<details>
  <summary markdown="span"><code>/etc/default/sslh</code> (expand)</summary>
<pre><code>
ubuntu@ubuntu-24go:~$ cat /etc/default/sslh 
RUN=yes
DAEMON=/usr/local/sbin/sslh
DAEMON_OPTS="-F /etc/sslh.cfg" 
</pre></code>
</details>
<details>
  <summary markdown="span"><code>/etc/nginx/sites-available/<my.cool.site.conf></code> (expand)</summary>
<pre><code>
ubuntu@ubuntu-24go:~$ cat /etc/nginx/sites-available/<my.cool.site.conf>
server {
	if ($host = <my.cool.site>) {
		return 301 https://$host$request_uri;
	} # managed by Certbot

	listen 80 ;
	listen [::]:80 ;

	root /var/www/html;

	index index.html;
	server_name <my.cool.site>; 

	location / {
		try_files $uri $uri/ =404;
	}
}

server {
	root /var/www/html;
	index index.html;
	server_name <my.cool.site>;

	location / {
		try_files $uri $uri/ =404;
	}
	
	listen [::1]:443 ssl;
	listen 127.0.0.1:443 ssl;

        (here would be the SSL certificates managed by certbot)
}
</pre></code>
</details>

So that is where I am at. For now, the only way to make my website work is by disabling SSLH and making Nginx listen to port 443 on the normal address. Would really love this setup to work as my school blocks the ports used by XMPP... 

p.s. sorry if this does not belong here, it may be an Nginx issue, but I cannot really diagnose stuff since everything is all in green and says it works.

**Comment by licaon-kter** [comment]
nginx should use a different port like 8443 in sites-available.

And in sslh.cfg modify to point to that port.

**Comment by licaon-kter** [comment]
What does `systemctl status sslh` output?

**Comment by utoni** [comment]
What's the output of `journalctl -u sslh.service` ?

**Comment by utoni** [comment]
Houston, we have a connection loop:

```syslog
Aug 28 15:46:35 ubuntu-24go sslh[68672]: tls:connection from localhost:55782 to localhost:https forwarded from localhost:56104 to localhost:https
Aug 28 15:46:35 ubuntu-24go sslh[68675]: tls:connection from localhost:56104 to localhost:https forwarded from localhost:56158 to localhost:https
Aug 28 15:46:35 ubuntu-24go sslh[68677]: tls:connection from localhost:56158 to localhost:https forwarded from localhost:56258 to localhost:https
```

**Comment by utoni** [comment]
Try:

```
listen:
(
{ host: ""; port: "443"; }
);
protocols:
(
{ name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 0;},
{ name: "tls"; host: "localhost"; port: "8443";},
{ name: "xmpp";    host: "localhost"; port: "5222"; },
{ name: "timeout"; host: "localhost"; port: "8443";}
);
on-timeout: "timeout";
```

Instead of:
> listen:
> (
> { host: ""; port: "443"; }
> );
> protocols:
> (
> { name: "tls"; host: "localhost"; port: "5223"; alpn_protocols: [ "xmpp-client" ]; log_level: 0;},
> { name: "tls"; host: "localhost"; port: "443";},
> { name: "xmpp";    host: "localhost"; port: "5222"; },
> { name: "timeout"; host: "localhost"; port: "443";}
> );
> on-timeout: "timeout";

**Comment by utoni** [comment]
> Tried your proposed config and changing my nginx/sites-available to these 4, but none worked:
> 
>     * `listen localhost:8443 ssl;` 
>     * `listen localhost:443 ssl;`
>     * `listen 8443 ssl;`
>     * `listen 443 ssl;` (this one expectedly has conflicts)

Yes, tcp port server_ip:443 is already used by sslh.
Did you try to manually run sslh in the foreground with: `/usr/local/sbin/sslh -F/etc/sslh.cfg -f` ?

**Comment by utoni** [comment]
Now we're talking. There are two issues here.
1. `bind()` fails
2. `check_res_dump()` should save errno before calling any other libc function

Please disable **alll** other tcp port 443 listeners and try again.

**Comment by utoni** [comment]
Did you try to run `sslh` as root since 443 is a privileged port?

**Comment by AntonOfTheWoods** [comment]
@Adaoh2 , would you mind letting us know how you compiled and what libraries you installed? I am also trying and failing to compile and run on Ubuntu 22.04.1, but with a different error message.

**Comment by AntonOfTheWoods** [comment]
> Maybe you could add your error message here?

https://github.com/yrutschle/sslh/issues/346

**Comment by AntonOfTheWoods** [comment]
@Adaoh2 , the docs definitely need some work. I will try and spend quite a bit of time in a couple of weeks when I get a moment. Please leave any suggestions on the ticket I opened! https://github.com/yrutschle/sslh/issues/350
