### ISSUE TITLE
I love this tool,  Is there any performance test result avaliable?

### ISSUE THREAD

**Issue by Neilpang** [yrutschle/sslh#357]
It seems to have 60-100ms delay in my test.

**Comment by Neilpang** [comment]
I have nginx listening on my 443 port. and then use sslh to linsten on my 10443 port.

**Comment by Neilpang** [comment]
```
connect from another server:

time curl  --insecure https://my.server.ip

real    0m0.186s
user    0m0.007s
sys     0m0.003s


-------------------------------------------------------
time curl  --insecure https://my.server.ip:10443

real    0m0.235s
user    0m0.009s
sys     0m0.003s


```

**Comment by Neilpang** [comment]
If connet without ssl,  it seems not big difference:

(the sslh is also accepting http request on the 10443 port)

```
time curl  http://my.server.ip

real    0m0.118s
user    0m0.000s
sys     0m0.005s

---------------------------------------------------

 time curl  http://my.server.ip:10443

real    0m0.120s
user    0m0.006s
sys     0m0.000s

```

**Comment by yrutschle** [comment]
I am not aware of any work in measure sslh performance. That'd be interesting to have, of course, although probably it will depend heavily on conditions (typically, we expect `sslh-ev` to be much better than `sslh-select` when there many concurrent connections, but we don't really know if that's  the case).

I would suggest going with a tool specialised in measuring network performance, e.g. iperf, rather than time.

**Comment by Neilpang** [comment]
I tested with `sslh-libev` and `sslh-fork`,  but they have the same result.

I was testing for the first time connection speed,   not the  transporting speed.  so I used the `time`, instead of `iperf3`.

would you mind giving it a try?

**Comment by Neilpang** [comment]
I just added timestamps to the log:

```
[Current time: 1663985611.910]tls addr: ::1:443. libwrap service: (null) log_level: 0 family 10 10 [] [] []

[Current time: 1663985611.910]ssh addr: ::1:22. libwrap service: ssh log_level: 1 family 10 10 [] [] []

[Current time: 1663985611.910]http addr: ::1:80. libwrap service: (null) log_level: 1 family 10 10 [] [] []

[Current time: 1663985611.910]anyprot addr: ::1:20001. libwrap service: (null) log_level: 1 family 10 10 [] [] []

[Current time: 1663985611.910]timeout: 1
on-timeout: ssh
UDP hash size: 1024

[Current time: 1663985611.910]Listening to:

[Current time: 1663985611.910]3:        0.0.0.0:20443   [] []

[Current time: 1663985611.910]turning into nobody

[Current time: 1663985611.910]sslh-fork head-2022-09-24 started

[Current time: 1663985637.731]accepted fd 4

[Current time: 1663985637.733]writing deferred on fd -1

[Current time: 1663985637.733]hexdump of incoming packet:

[Current time: 1663985637.733]0x000000: 16 03 01 02 00 01 00 01 fc 03 03 d7 ce bf 89 52 ...............R


.......


[Current time: 1663985637.733]0x0001f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ................

[Current time: 1663985637.733]0x000200: 00 00 00 00 00                                  .....

[Current time: 1663985637.733]probing for tls

[Current time: 1663985637.733]probed for tls: PROBE_MATCH

[Current time: 1663985637.733]trying to connect to ::1:443 family 10 len 28

[Current time: 1663985637.733]flushing deferred data to fd 3

[Current time: 1663985637.927]server socket closed

[Current time: 1663985637.927]connection closed down
```


It seems that most of time is spent before the socket is closed:

```
[Current time: 1663985637.733]flushing deferred data to fd 3

[Current time: 1663985637.927]server socket closed
```

what do you think?

**Comment by yrutschle** [comment]
I think I don't  understand what you are trying to measure.

Network performance is measured in bandwitdh, latency and jitter. So you could want to know the effect of crossing sslh on these as opposed to sslh being absent.
Process performance can be measured in CPU load and memory (per connection, for example).

For effect on network performance, I think you'd be better off using tcpdump or wireshark to measure the time between packets coming out of the physical interface into sslh, and out of sslh to the target process. Measuring from "inside" sslh means you lose the effect of copies between sslh and kernel memory, which is probably the main overhead sslh introduces.

**Comment by Neilpang** [comment]
>> I think I don't understand what you are trying to measure.

Sorry, I was just trying to figure out  how much time was spent by each steps inside sslh.

For now, I was trying to measure  the  "Connection latency"  for ssl connections.

As in my test,  there is about a 60ms-100ms difference between with sslh and without sslh.   I just want to know why and how to fix it.

BTW, did you ever get any chance to  reproduce this difference?

Thanks
