### ISSUE TITLE
Incorrect fail2ban regexp

### ISSUE THREAD

**Issue by JIVeer** [yrutschle/sslh#359]
Hi,
in file [sslh](https://github.com/yrutschle/sslh)/[scripts](https://github.com/yrutschle/sslh/tree/master/scripts)/[fail2ban](https://github.com/yrutschle/sslh/tree/master/scripts/fail2ban)/sslh-ssh.conf

is regexp wrong, its missing "ssh:" before "connection"
like
`failregex = ^.+ sslh\[.+\]: ssh:connection from <HOST>:.+ to .+ forwarded`

after that change, it works for me.

Regards,
JIV

**Comment by yrutschle** [comment]
indeed -- thanks for the report
