### ISSUE TITLE
Performance considerations

### ISSUE THREAD

**Issue by haarp** [yrutschle/sslh#363]
Hello,

sslh sounds like an excellent tool! I do however wonder a little about its impact on the connections it's proxying/demultiplexing.

- Is there a noticeable latency due to probing?
- Does the probing incur additional connection round-trips?
- Will this work with HTTPS/2's own connection multiplexing and [TLSv1.3 0-RTT](https://blog.cloudflare.com/introducing-0-rtt/)?

Thanks a lot!

**Comment by utoni** [comment]
I can not answer the first question accurately due to the lack of performance measurement. But I think that using "raw" probing e.g. w/o relatively slow regexes it should be pretty fast. The only performance impact could be  additional socket api calls (transparent mode should be faster though).

Second question: Nope.

Third question: This will most likely not work due to the nature of TLSv1.3 0-RTT's.

**Comment by haarp** [comment]
Thanks for your reply.

> This will most likely not work due to the nature of TLSv1.3 0-RTT's.

Hmm, why tho? I admit that I don't fully understand the technologies involved, but 0-RTT merely reduces the TLS handshake by one round trip. I do think should work.

**Comment by utoni** [comment]
AFAIK, 0-rtt TLS1v3 does not contain any SNI extension. But `sslh` requires those to do sni based multiplexing.

**Comment by haarp** [comment]
Cheers, this makes sense. But assuming I do not use `sni_hostnames`, I can distinguish between e.g. HTTPS and SSH while reaping the benefits of 0-RTT, correct?

**Comment by utoni** [comment]
Indeed. It should be possible in general to multiplex 0-RTTs. But while looking at the current `sslh` TLS probing code, I have my doubts that this will work w/o modification.

**Comment by yrutschle** [comment]
@utoni why do you think that?
My understanding of RFC8446, Figure 4, is that the 0-RTT first packet is a ClientHello with additional data, and I think it is the ClientHello that contains the SNI data, so I would expect it to work (from a cursory document analysis, so with all the caveat of difference between theory and practice :-) ).

**Comment by utoni** [comment]
It seems like it's a "common" CLHO. But why? I mean there is already a PSK available, so why not use it to encrypt some extensions? I will try to get my hands on a TLS1v3 0-RTT pcap.

**Comment by haarp** [comment]
Thanks for the info! :) That's good news. Going to give this a whirl once I've set everything up.
