### ISSUE TITLE
"Request did not begin with TLS handshake" spam on every non https connection

### ISSUE THREAD

**Issue by fdellwing** [yrutschle/sslh#367]
We run sslh-ev in testmode currently. We have http, https and openvpn enabled and everything but the https connections triggers that error message. That is a bit spammy.

**Comment by yrutschle** [comment]
ah, I think it's common unwritten practice to have the https probes after the other probes, so no one noticed that before. That's a fair concern though, I guess this particular message should be ` `msg_probe_info` rather than `msg_probe_error`

**Comment by yrutschle** [comment]
Hopefully this should help!
