### ISSUE TITLE
OpenVPN TLS-Crypt

### ISSUE THREAD

**Issue by r3a1d3a1** [yrutschle/sslh#369]
I wonder whether OpenVPN is detected when it's using TLS-Crypt, and if so, how?!

**Comment by utoni** [comment]
AFAIK it will be detected as generic TLS traffic, probably with a risk "SNI missing" set.

**Comment by yrutschle** [comment]
I assume the answer is satisfactory. Please reopen if needed.

**Comment by utoni** [comment]
I guess so.
