### ISSUE TITLE
sslh requires two attempts to forward tls

### ISSUE THREAD

**Issue by eiery** [yrutschle/sslh#372]
I'll preface this by saying that I'm getting this issue with the old 1.20-1 version of sslh (from Ubuntu 22 repository), so this may have been fixed with the latest build that I have not compiled and tried yet. I use sslh to split my port 443 input to a https web server and an openvpn server.

Basically I'm getting a "forward to tls failed:connect: Connection refused" error in my log when I make the initial connection through sslh, but sslh performs the connection again with a different "family" and "len" and then the connection works. As a user I cannot feel the two connection attempts and I can reach the web server through sslh just fine. Also I don't have any issues connecting directly to the 8006 web server without sslh. Here's how a connection attempt looks like with verbose mode turned on:

```
Dec 19 18:42:21 server-name sslh[802]: tls addr: localhost:8006. libwrap service: (null) log_level: 1 family 10 10 [] []
Dec 19 18:42:21 server-name sslh[802]: openvpn addr: REDACTED:https. libwrap service: (null) log_level: 1 family 2 2 [] [fork]
Dec 19 18:42:21 server-name sslh[802]: listening on:
Dec 19 18:42:21 server-name sslh[802]: #0110.0.0.0:https#011[]
Dec 19 18:42:21 server-name sslh[802]: timeout: 2
Dec 19 18:42:21 server-name sslh[802]: on-timeout: tls
Dec 19 18:42:21 server-name sslh[802]: listening to 1 addresses
Dec 19 18:42:21 server-name sslh[802]: sslh-fork 1.20-1 started
Dec 19 18:42:21 server-name sslh[802]: turning into sslh
Dec 19 18:42:21 server-name sslh[802]: capabilities: =
Dec 19 18:42:43 server-name sslh[803]: accepted fd 4
Dec 19 18:42:43 server-name sslh[812]: hexdump of incoming packet:
Dec 19 18:42:43 server-name sslh[812]: 0x000000: 16 03 01 02 00 01 00 01 fc 03 03 4a 74 99 a6 2c ...........Jt..,
--- REDACTED ---
Dec 19 18:42:43 server-name sslh[812]: 0x000200: 00 00 00 00 00                                  .....
Dec 19 18:42:43 server-name sslh[812]: **** writing deferred on fd -1
Dec 19 18:42:43 server-name sslh[812]: probing for tls: PROBE_MATCH
Dec 19 18:42:43 server-name sslh[812]: connecting to localhost:8006 family 10 len 28
Dec 19 18:42:43 server-name sslh[812]: forward to tls failed:connect: Connection refused
Dec 19 18:42:43 server-name sslh[812]: connecting to localhost:8006 family 2 len 16
Dec 19 18:42:43 server-name sslh[812]: tls:connection from REDACTED:39280 to server-name:https forwarded from localhost:58696 to localhost:8006
Dec 19 18:42:43 server-name sslh[812]: flushing deferred data to fd 3
Dec 19 18:42:44 server-name sslh[812]: server socket closed
Dec 19 18:42:44 server-name sslh[812]: connection closed down
```

My sslh options are as follows:

`--user sslh --listen 0.0.0.0:443 --tls localhost:8006 --openvpn REDACTED:443 --pidfile /var/run/sslh/sslh.pid`

I'm not sure what "family" and "len" are doing in this context but it looks like with the different "family" and "len" values on the retry sslh was able to make a successful connection. The "family" and "len" values remain consistent across different connections in that it always starts with 10,28 (which fails) and then goes to 2,16 (which works).

**Comment by yrutschle** [comment]
"family" is the type of transport protocol; 10 is IPv6, 2 is IPv4. What's happening is that "localhost:8006" resolves first as an IPv6 address, but no server listens there, so `sslh` moves to the next resolved address that's IPv4, where a server is listening.
This is all nominal behaviour.
