### ISSUE TITLE
Redirection for 2 OpenVPN server configs

### ISSUE THREAD

**Issue by srvh** [yrutschle/sslh#375]
Hello.

I have 2 OpenVPN server configs.
I want to use both on port 443.
I installed stunnel on 443 port.
My scheme of connection is:
openvpn client -> stunnel client -> stunnel server (port 443) -> sslh (port 445) -> openvpn (port 1194)
I am using SNI parameter for stunnel config.

My stunnel client config:
[openvpn]
sni = some.domain
client = yes
accept = 127.0.0.1:1194
connect = vpn_ip:443

My sslh config (not full, only paste protocols section)
protocols:
(
     { name: "openvpn"; host: "vpn_ip"; port: "1194"; sni_hostnames: [ "some.domain" ]; },
     { name: "http"; host: "localhost"; port: "80"; },
     { name: "tls"; host: "localhost"; port: "4433"; log_level: 0; },
     { name: "anyprot"; host: "localhost"; port: "22"; }
);

I understand that SNI is using only for HTTPS TLS connection.
So my scheme is working correctly for one openvpn config. But how can I manage 2 VPN server configs?

May be sslh can manage 2 openvpn connections ?

**Comment by yrutschle** [comment]
SNI is inteed a TLS extension; I don't remember that OpenVPN has a similar feature, however in your setup you could achieve the same by switching stunnel and sslh, and have the stunnel client set different SNI:
```
ovpn1  --> stunnel SNI="some.domain" ---+      __ stunnel --> ovpn1
                                        |     /
				        sslh <
					|     \
ovpn1 --> stunnel SNI="other.domain" ---+      --- stunnel -> ovpn2
```

with sslh config something like:
```
protocols: (
{ name: "tls"; host: "stunnel1.local"; sni_hostnames: ["some.domain"]; },
{ name: "tls"; host: "stunnel2.local"; sni_hostnames: ["other.domain"]; }
);
```

**Comment by yrutschle** [comment]
SNI is inteed a TLS extension; I don't remember that OpenVPN has a similar feature, however in your setup you could achieve the same by switching stunnel and sslh, and have the stunnel client set different SNI:
  ```
  ovpn1  --> stunnel SNI="some.domain" ---+      __ stunnel --> ovpn1
                                          |     /
				          sslh <
					  |     \
  ovpn1 --> stunnel SNI="other.domain" ---+      --- stunnel -> ovpn2
  ```
  
  with sslh config something like:
  ```
  protocols: (
  { name: "tls"; host: "stunnel1.local"; sni_hostnames: ["some.domain"]; },
  { name: "tls"; host: "stunnel2.local"; sni_hostnames: ["other.domain"]; }
  );
  ```
