### ISSUE TITLE
configuration for http3

### ISSUE THREAD

**Issue by JoshuaPettus** [yrutschle/sslh#376]
I've been looking into the nginx http3 branch and hoping to eventually give it a try.  One hurdle is accounting for the UDP quic protocol in sslh.  I was wondering if anyone had tried this yet and what would that configuration look like?

**Comment by yrutschle** [comment]
Yes -- there is an example in `example.cfg`.

**Comment by JoshuaPettus** [comment]
Dang, Really?  My apologies, completely missed that.  For the record this is it?   

> # Forward IETF QUIC-50 ("Q050" -> "\x51\x30\x35\x30")
> # Remember that the regex needs to be adjusted for every supported QUIC version.
>      { name: "regex"; host: "localhost"; is_udp: true; port: "4433"; regex_patterns: [ "\x51\x30\x35\x30" ]; },

**Comment by Kobaxidze256** [comment]
@JoshuaPettus Heads up, that example is already out of date: https://github.com/yrutschle/sslh/issues/466#issuecomment-4531098063
