### ISSUE TITLE
Transparent proxy with Windows client

### ISSUE THREAD

**Issue by guru431** [yrutschle/sslh#377]
I set up SSLH in transparent proxy mode with multiple hosts.
Everything is working fine.
But there is a need to add a Windows (IIS) host to this scheme.

How can I do something similar on Windows?
`iptables -t mangle -N SSLHSSL`
`iptables -t mangle -A OUTPUT -o eth0 -p tcp -m multiport --sport 1022,8000 -j SSLHSSL`
`iptables -t mangle -A SSLHSSL --jump MARK --set-mark 0x1`
`iptables -t mangle -A SSLHSSL --jump ACCEPT`
`ip rule add fwmark 0x1 lookup 100`
`ip route add default via 192.168.1.124 table 100`
`ip route flush cache`

**Comment by yrutschle** [comment]
The new way of configuring transparent proxying explained [here](https://github.com/yrutschle/sslh/discussions/454) should work with any host behind sslh. Please create a new discussion if needed.
