### ISSUE TITLE
Rewrite host header when proxying http

### ISSUE THREAD

**Issue by HandyHat** [yrutschle/sslh#397]
It would be great if sslh could rewrite the value in the host header to match the value that the http server that is being proxied to is expecting. Not doing so can cause unexpected behaviour. e.g. https://github.com/caddyserver/caddy/issues/5656

Thanks!

**Comment by yrutschle** [comment]
This would involve a lot of HTTP-specific code, and is probably best done by a proper reverse proxy. I'd much rather `sslh` stays away from touching the payloads and do not plan to implement this.
