### ISSUE TITLE
failover support?

### ISSUE THREAD

**Issue by poVoq** [yrutschle/sslh#422]
Is it possible to make sslh to failover to another internal server when it can not redirect to the primary one?

**Comment by yrutschle** [comment]
at the moment, I think it tries all IP addresses in the order the name resolution gives them until it finds one to connect to, so I'd expect if you have define several IPs for one service, it'll try them?
(I have never tried it)

Something like, in /etc/hosts:

192.168.10.1  ssh_target
192.168.10.2 ssh_target

and then use `ssh_target` in `sslh.cfg`.

**Comment by yrutschle** [comment]
closing for lack of response, please reopen if needed.
