### ISSUE TITLE
rutschle.net download: missing v1.23.1 archive

### ISSUE THREAD

**Issue by yurtpage** [yrutschle/sslh#433]
The last version present there is v1.23.0 
The OpenWrt builds a package by a downloading sources from the site. We can change it to download from GitHub but  generally official downloads are preferred.

**Comment by yrutschle** [comment]
I have never used Github's releases, and it's not clear on first sight what they bring over tags... I'll look into it, but generally I prefer to keep adherence to Github minimal.

Github, on the other hand, pretty much forced me to move to semantic versioning (vX.Y.Z with each digit having a meaning in terms of API), which was a good thing: there will be no more v1.22c; I used to use the last letter as bug fixes, which corresponds to Z in semantic versionning, so v1.22c would be better written as v1.22.3. v.1.23.Z is the bugfix branch for v1, which will receive no further features.
So short answer is: don't worry, future versions should be compatible with OpenWRT requirements :-)
