### ISSUE TITLE
Make the basic.cfg useful out of the box

### ISSUE THREAD

**Issue by stokito** [yrutschle/sslh#438]
The file https://github.com/yrutschle/sslh/blob/master/basic.cfg provides a sample.

But in the OpenWrt it's just slightly patched and used as a default config:

https://github.com/fett327/packages/blob/master/net/sslh/patches/002-configfile-fix.patch

So here the sample `thelonious` was replaced with "listen all interfaces" address.

    { host: "thelonious"; port: "443"; }
+    { host: "0.0.0.0"; port: "443"; },

Also was disabled the http and xmpp detection which is probably for security reasons not use use encrypted traffic.

So maybe you can grab the patch? It should be ok to be a default.

**Comment by yrutschle** [comment]
Does this actually work? `sslh` forwards TLS to localhost:443, so presumably `httpd` is already bound on 0.0.0.0, so... sslh can't also bind?
That was the original intent behind the name 'thelonious' (which used to be a server of mine): it resolves to the external IP address, which `sslh` binds, while `httpd` binds `localhost`, both on 443.

**Comment by stokito** [comment]
This works if the local webserver was first who started listening on the 127.0.0.1
