### ISSUE TITLE
enable discussions for this repo

### ISSUE THREAD

**Issue by ftasnetamot** [yrutschle/sslh#451]
After looking to several of the open issues, I would recommend, to enable discussions for this repo.
I see most of the issues more as discussions about extend network configuration and not as real issues with the software.
So I think, a majority of the open issues could be moved to discussions, as the outcome of the discussion of that issue will not lead to any change or will even not lead to any result.

In general the first impression for newcomers about code maturity would be more real. 59 open issues from the last **ten** years does not reflect the maintainers reputation.

**Comment by yrutschle** [comment]
I don't think I ever noticed this menu... I activated and added a post on transparent proxying, I will probably close all issues related to that topic and redirect to that post.

Thanks!
