### ISSUE TITLE
Please update FAQ regarding verbosity

### ISSUE THREAD

**Issue by MikhailRyazanov** [yrutschle/sslh#452]
doc/FAQ.md still says to use `-v` for debugging:
https://github.com/yrutschle/sslh/blob/eb84c6a55b5ce62b1268ae53da52769421a01593/doc/FAQ.md?plain=1#L15-L27
but this has stopped working completely since v2.0:
https://github.com/yrutschle/sslh/blob/eb84c6a55b5ce62b1268ae53da52769421a01593/ChangeLog#L29-L32
and results in an error:
```
sslhcfg: invalid option "-v"
```

Thus the FAQ must be updated accordingly.

And a question: is there now a simple way to increase verbosity ”in general”? Or for some kind of messages — for example, it is not clear whether setting `--verbose-connections` will have any effect on `--verbose-connections-try` and `--verbose-connections-error`, or each of them needs to be set explicitly to see all connection-related messages.

**Comment by MikhailRyazanov** [comment]
The man file also must be updated, as it still “documents” the `-v` option instead of all these `--verbose-...`:
https://github.com/yrutschle/sslh/blob/eb84c6a55b5ce62b1268ae53da52769421a01593/sslh.pod?plain=1#L9
and
https://github.com/yrutschle/sslh/blob/eb84c6a55b5ce62b1268ae53da52769421a01593/sslh.pod?plain=1#L167-L169

**Comment by yrutschle** [comment]
ok, I re-introduced a general `--verbose` option that overrides all the others, and hope I fixed the documentation appropriately.
Thanks for the report!
