### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by gedw99** [yrutschle/sslh#46]
Has this been used on embedded system with arm CPU ?

Looking at applying it and curious of the status

**Comment by sneerix** [comment]
I'm using sslh for some time on Odroid-XU (Exynos5 Octa Cortex-A15 1.6Ghz quad core and Cortex-A7 quad core CPUs) platform. Works OK for me.

**Comment by gedw99** [comment]
Thanks. Good to know. I will check our board spec.

**Comment by gedw99** [comment]
The CPU on the MityDSP module is an OMAP-L138 (http://www.ti.com/product/omap-l138
