### ISSUE TITLE
tag version 2.1.3

### ISSUE THREAD

**Issue by nono303** [yrutschle/sslh#477]
Hi @yrutschle 
to ensure `genver` producing a good `version.h` could you tag https://github.com/yrutschle/sslh/commit/a222ea2c9937f4c8785d087ef268a0d4346a96ef as v2.1.3?
Thx!

**Comment by yrutschle** [comment]
You should now find the appropriate tag, I also pushed the version to the Web site. Thanks for prodding me on the topic.
