### ISSUE TITLE
--openvpn conflicts with --ssh

### ISSUE THREAD

**Issue by vi** [yrutschle/sslh#48]
`--openvpn` + `--ssl` seems to work. But with `--openvpn` + `--ssh` I OpenVPN throws `WARNING: Bad encapsulated packet length from peer (21331), which must be > 0 and <= 1546 -- please en`

**Comment by Perdu** [comment]
Hi,
I had the exact opposite problem: `--openvpn` + `--ssh` worked, but `--openvpn` + `--ssl` did not (I got a connection reset for openvpn in the latter case).
Strangely, changing the order of the options in the config file fixed the problem.
i.e. this fails:
`DAEMON_OPTS="--user sslh --timeout 20 --listen 0.0.0.0:443 --ssh 127.0.0.1:22 --ssl 127.0.0.1:8080 --openvpn 127.0.0.1:1194 --pidfile /var/run/sslh/sslh.pid"`
but this works:
`DAEMON_OPTS="--user sslh --listen 0.0.0.0:443 --openvpn 127.0.0.1:1194 --ssh 127.0.0.1:22 --ssl 127.0.0.1:8080 --pidfile /var/run/sslh/sslh.pid"`
(the 3 services are reachable now).
Not sure if this is related.
Note: I'm running sslh 1.13b on raspbian, so this may have been fixed already (although I did not find any mention of it in the changelog)
Hope it helps.

**Comment by yrutschle** [comment]
The order of protocols on the command line is somewhat important: if sslh fails to recognise the protocol, it will forward the connection as specified by --anyprot, or to the first protocol if --anyprot is not present. So, in your first line it'll connect unrecognised protocols to ssh while the second will connect them to openvpn. So if for some reason the openvpn probe doesn't work, the second line will work.

**Comment by m3adow** [comment]
While this bug report is old, I encounter the same problem. Not sure if relevant, but I use a Docker container for sslh (https://github.com/m3adow/dockerfiles-arm/tree/master/sslh), it's compiling from the master branch, so newest release.

My config is very close to the basic.cfg:
```
verbose: true;
foreground: true;
inetd: false;
numeric: false;
transparent: false;
timeout: 2;
user: "nobody";
pidfile: "/var/run/sslh.pid";

protocols:
(
     { name: "openvpn"; host: "openvpn.local"; port: "1194"; },
     { name: "ssh"; service: "ssh"; host: "ssh.local"; port: "22"; },
     { name: "http"; host: "httpd.local"; port: "80"; },
     { name: "tls"; host: "httpd.local"; port: "443"; },
     { name: "anyprot"; host: "httpd.local"; port: "443"; }
);
```

As long as SSH is configured, every OpenVPN connection is directed to the configured SSH port. Without a configured ssh service, OpenVPN works as expected. The workaround I found for now is, to use the OpenVPN regex match from the example.cfg. This also works.  
Perhaps the inbuilt OpenVPN detection is somehow broken?

**Comment by m3adow** [comment]
Okay, after several tries, I'm pretty sure this is an application bug, not a configuration bug. If I restart sslh several times with the same configuration, sometimes every protocol is forwarded to its correct destination and sometimes OpenVPN is forwarded to SSH. Doesn't matter if done via config file or command line.

Therefore I assume it's either a race condition somewhere or protocol probing order is initialized in an unordered list/array which differs after every start. Sadly, I'm not accustomed to C, so I didn't really understand the source code.

**Comment by yrutschle** [comment]
I can't think of anything that's non-deterministic in the initialization... When you say "sometimes", do you mean it's consistent for every run? (meaning: once you run sslh, it always works, or never works)?

One thing that's non-deterministic and has been known to create problems is the timeout at 2 seconds which is on the short side for OpenVPN (the client takes a long time to initialize crypto things *after* opening the TCP connection): does it work better with a timeout of, say, 5s?

**Comment by yrutschle** [comment]
Right, the time has come to close this :)
