### ISSUE TITLE
v2.1.3 fails to build on macOS

### ISSUE THREAD

**Issue by amake** [yrutschle/sslh#481]
```
common.c:272:26: error: use of undeclared identifier 'SOL_IP'
  272 |     res = setsockopt(fd, SOL_IP, IP_TRANSPARENT, &enable, sizeof(enable));
      |                          ^
common.c:296:30: error: use of undeclared identifier 'SOL_IP'
  296 |         res = setsockopt(fd, SOL_IP, IP_BIND_ADDRESS_NO_PORT, &enable, sizeof(enable));
      |                              ^
2 errors generated.
make: *** [common.o] Error 1
```

I don't know much about any of this, but it seems like `SOL_IP` is Linux-specific:
https://www.man7.org/linux/man-pages/man7/ipv6.7.html#NOTES

**Comment by yrutschle** [comment]
One of us is confused: I feel like SOL_IP was introduced after v2.1.3 (and is not yet tagged). I fixed it on master, please re-open if I missed something.

**Comment by amake** [comment]
You are apparently serving 9243a6e36964ba7443f62be05abd19303109e95d as https://www.rutschle.net/tech/sslh/sslh-v2.1.3.tar.gz

**Comment by yrutschle** [comment]
Hence the confusion. I need to look at the build system to see how that happens, and will release the proper archive when I get around to it...

**Comment by yrutschle** [comment]
ok, `make release` would in fact take the head of `master`... Hopefully this won't happen in the future.
I created a tag v2.1.4 which is equivalent to v2.1.3, so there is no confusion between the archives.

**Comment by chenrui333** [comment]
@yrutschle I did not see the new tag somehow?

<img width="427" alt="image" src="https://github.com/user-attachments/assets/07b51c8f-a258-478d-947a-9ecef112af65">

but this artifact works for my brew build, `https://www.rutschle.net/tech/sslh/sslh-v2.1.4.tar.gz`

**Comment by yrutschle** [comment]
I forgot to push it to Github, sorry... it should be there now.

**Comment by chenrui333** [comment]
Thanks @yrutschle! we shipped in https://github.com/Homebrew/homebrew-core/pull/200411

**Comment by yrutschle** [comment]
:+1: 
Thanks for your work!
