### ISSUE TITLE
Support detection of DNS on 53/tcp

### ISSUE THREAD

**Issue by robbat2** [yrutschle/sslh#57]
Could you support detection of DNS on port 53/tcp?

**Comment by yrutschle** [comment]
On Thu, Jul 23, 2015 at 02:04:31PM -0700, Robin H. Johnson wrote:
> Could you support detection of DNS on port 53/tcp?

I don't think so. There is nothing in a DNS request that
makes it look like a DNS packet. You might get away with
using the regular expression probe to probe for requests for
your domains, but I would expect that to be rather
unreliable.
