### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [yrutschle/sslh#59]
I would like to point out that identifiers like "[`__COMMON_H_`](https://github.com/yrutschle/sslh/blob/6bcb5c83f24388866720e07caa0c4f871d5d1dda/common.h#L1)" and "[`__PROBE_H_`](https://github.com/yrutschle/sslh/blob/b9885401050ad27d9fa13ffa67d5e43441f495c0/probe.h#L3)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by yrutschle** [comment]
Fixed in 555005f455df706c6754c9407654c66ca1b4feb3

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/yrutschle/sslh/commit/555005f455df706c6754c9407654c66ca1b4feb3 "Deletion of a few underscores").
