### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [yrutschle/sslh#60]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/yrutschle/sslh/blob/b9885401050ad27d9fa13ffa67d5e43441f495c0/Makefile#L3 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](http://cmake.org/ "CMake build system")
* [Autotools](http://www.gnu.org/software/autoconf/#TOCintroduction "GNU build system")

**Comment by yrutschle** [comment]
Make is fine for the time being, and I try to resist including many libraries. If needs be, that'll change one day, but I think it's completely overkill at the moment to move to such systems just to save setting 3 compile options.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.4/manual/cmake-generators.7.html "Selection for build tool generators")?

**Comment by yrutschle** [comment]
On Tue, Jan 26, 2016 at 09:28:15AM -0800, Markus Elfring wrote:
> * Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?

Not really -- Autotools is great for big projects with many
different dependencies, but really sslh depends on 2 or 3
libraries, it's not worth the complexity IMO (I have worked
with Autotools before, I don't remember enjoying that!)

> * How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.4/manual/cmake-generators.7.html "Selection for build tool generators")?

It already compiles out of the box on Linux, FreeBSD, MacOS,
Cygwin/Windows... I think it's simple enough as it is, but
if someone submitted a Cmakefile, I might consider including
it.
