### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [yrutschle/sslh#61]
Would you like to add more error handling for return values from functions like the following?
- [calloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html) ⇒ [setup_regex_probe](https://github.com/yrutschle/sslh/blob/4cbaf447b5a634f703bc571bf0e12f3ae1514d8a/sslh-main.c#L176)
- [fprintf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fprintf.html) ⇒ [write_pid_file](https://github.com/yrutschle/sslh/blob/7c35ef8528d47b97894a6495275b57dc1ae3f8c7/common.c#L633)

**Comment by yrutschle** [comment]
Fixed for calloc().
Hard to know what to do in case of failure of fprintf(). PID just won't be written, I guess.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software? :thinking:

**Comment by yrutschle** [comment]
I have a vague idea to use Frama-C to prove the absence of vulnerabilities in the code that's exposed to untrusted code. It's not at all trivial, though.

Other than that, I'm not sure what you're suggesting? Use an analyser? Which one? :)

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by yrutschle** [comment]
If you're offering to list all occurences where return values are ignored, I'm in fact interested.

In this particular case, the file and the pid value is never used again by sslh, so it probably doesn't matter. I just checked in code to handle it anyway, it's really not enough code to justify arguing.

**Comment by elfring** [comment]
>In this particular case, the file and the pid value is never used again by sslh, …

Really? ‒ [Why is the function “write_pid_file” called then](https://github.com/yrutschle/sslh/blob/0e118a109c0407e47c8e43e37662df0f6c0367f2/sslh-main.c#L227 "Checking the need for write_pid_file()")?


>I just checked in code to handle it anyway, …

Thanks for [another source code adjustment](https://github.com/yrutschle/sslh/commit/0cde3d794a300f3a9fb2ea417d4c7f0e44bd4213 "check return values").

**Comment by yrutschle** [comment]
like it says, to write the PID outside. It may or may not be used by the system to stop the service later on, outside of sslh.

I accept that a service that starts without writing its PID may be a pain to admins.
