### ISSUE TITLE
transparent proxying in freebsd jail

### ISSUE THREAD

**Issue by ct16k** [yrutschle/sslh#65]
Hello,

I'm running sslh v1.17 on FreeBSD 10.2-RELEASE-p2 and I get an error when trying to enable transparent proxying. I have `security.jail.allow_raw_sockets: 1` but after setting `transparent` to `true` and restarting the service, if I start a request I receive

```
connect: Operation not permitted
```

at the console, and 

```
Sep 10 19:31:03 proxy sslh-fork[29529]: setsockopt IP_BINDANY:1:Operation not permitted
Sep 10 19:31:03 proxy sslh-fork[29529]: bind_peer:1:Operation not permitted
```

in the messages log. Chaning the user from `nobody` to `root` doesn't help.

My config is:

```
verbose: false;
foreground: false;
inetd: false;
numeric: true;
transparent: false;
timeout: "2";
user: "nobody";
pidfile: "/var/run/sslh.pid";

listen:
(
    { host: "192.168.24.28"; port: "444"; }
);

protocols:
(
    { name: "tls"; host: "192.168.24.28"; port: "443"; probe: "builtin"; },
    { name: "ssh"; service: "ssh"; host: "192.168.23.24"; port: "44"; probe: "builtin"; },
    { name: "xmpp"; host: "192.168.24.20"; port: "522"; probe: "builtin"; },

    { name: "anyprot"; host: "192.168.24.28"; port: "443"; probe: "builtin"; }
);
```

Any ideas what might be causing this?

Thank you!

**Comment by yrutschle** [comment]
I don't know much about FreeBSD's jails so it's a shot in the dark, but: sslh doesn't actually do raw sockets (raw sockets are straight Ethernet sockets where the applicative code can tinker with the entire IP header (and maybe even the Ethernet header, I don't recall)).
What it does need to do transparent proxying is the capability to bind to addresses that are outside of the network of the machine. That's "NET_ADMIN" in Linux, I guess there would be something similar in FreeBSD.

**Comment by zeroidle** [comment]
You have to change user, nobody to root

**Comment by yrutschle** [comment]
Closing due to lack of response
