### ISSUE TITLE
how to stop sslh spamming auth.log

### ISSUE THREAD

**Issue by kecksk0enig** [yrutschle/sslh#71]
Hi!
Sorry if this might be the wrong place to ask, but sslh is driving me nuts :)
I've setup sslh to handle ssl/hkp(s)/ and ssh and it works perfectly.
however every connect results in a log in auth.log which is realy spammy (~30k Visits over https, each resulting in a line in auth.log)
Is there any way to restrict sslh logging?

I have already tried to setup a rsyslogd filter like
http://william.shallum.net/random-notes/sslh-configuring-logging-logrotate-and-logwatch

but the messages STILL go to /var/log/auth.log AND /var/log/sslh.log. 
I only (if any) want them to go to the dedicated sslh.log file.
Also maybe only log SSH connection trys  since hkp(s) and https is already logged by webserver.

Thank you in advance

**Comment by yrutschle** [comment]
Hi,

Connection messages are logged with level LOG_INFO while
others (which presumably you want to keep) are all LOG_ERR.

Can't you ask rsyslog to drop LOG_INFO level logs coming from sslh?

(I honestly don't know but I expect syslog to be able filter
based on criticity levels and source names...)

Y.

**Comment by kecksk0enig** [comment]
hi!
thanks for the fast reply however:
>if $programname == 'sslh' then /var/log/sslh.log
if $programname == 'sslh' then ~

should send all to sslh.log and abort further logging (to auth log)
so the main problem is WHY it still logs to auth.log (and sslh.log).

So reducing the log level to Warn will STILL result in auth.log beeing filled.

**Comment by yrutschle** [comment]
On Tue, Dec 08, 2015 at 07:57:38AM -0800, kecksk0enig wrote:
> So reducing the log level to Warn will STILL result in auth.log beeing filled.

Ok, I'm proposing to add a configuration option:

http://rutschle.net/pipermail/sslh/2015-December/000590.html

I should have time to do this over the holidays.

Y.

**Comment by kecksk0enig** [comment]
Hi, since I am currently not on the mailinglist I will add my 2 cents here:
If you start working on the logging may be there is a way to specify different log files/facilities per protocol. So one don't have to search through ONE SSLH Log containing all protocolls but instead only one (the interested in service) log.

**Comment by yrutschle** [comment]
On Sat, Dec 12, 2015 at 06:49:49AM -0800, kecksk0enig wrote:
> If you start working on the logging may be there is a way to specify different log files/facilities per protocol. So one don't have to search through ONE SSLH Log containing all protocolls but instead only one (the interested in service) log.

That's not actually possible using syslog (you specify the
facility in openlog(2), which is global to the process).

The only way to achieve this in sslh would be to perform all
the logging directly by ourselves, and I really don't want
to go that way.

OTOH we can add a clear indication of the protocol in the
log so as to make it easier to grep through log files, or to
sort them in syslog.

**Comment by kecksk0enig** [comment]
I already expected this drawback in syslog. I also would not start logging by self, so the grepable indication sounds like the way to go.

**Comment by yrutschle** [comment]
The last two commits add the log_level option, and add the protocol name in the log message, respectively. Hope that helps!

**Comment by yrutschle** [comment]
Assuming this is now satisfactory :-)
