### ISSUE TITLE
Connection forwarded to SSL instead of SSH

### ISSUE THREAD

**Issue by mitobit** [yrutschle/sslh#73]
Hi,
we are using sslh since a lot of years ago. Sometimes from pc (e.g. using putty client) it doen't recognize the ssh traffic and it forwards the traffic to SSL. The result is that the server closed the connection

We are using the last relese available on Debian squeeze.

The log reports:
accepted fd 4
connected to something
Dec 14 17:39:37 localhost sslh[25768]: connection from XX.XX.XX.XX:24586 forwarded to SSL
server socket closed
connection closed down

sslh starts with the following opts:

DAEMON_OPTS="-u sslh -p 0.0.0.0:443 -s 127.0.0.1:22 -l 127.0.0.1:442 -P /var/run/sslh.pid -v"

**Comment by mitobit** [comment]
The https traffic work perfectly.

**Comment by yrutschle** [comment]
- Please provide traces from the ssh client (e.g. ssh -vvv)
- Traces from the ssh server (/var/log/auth.log)
- And choose between upgrading or taking this to Debian's maintainers: this version is absolutely ancient and I can't spend time supporting it! (I'll be happy to bughunt on the head version though).
