### ISSUE TITLE
Transparent proxying to another server

### ISSUE THREAD

**Issue by kaasszje** [yrutschle/sslh#76]
Hya all,

I'm trying to use sslh to push https traffic forward to my nas.
However it's just not connecting.
Ssh traffic does work however but that is on the same server.
So any idea why this does not work or what I am doing wrong ?

Direct connection to my nas on port 4443 does work.
As does the connection on 8022 on my ssh server.

So I've use the mangle example on my ssh server:
iptables -t mangle -N SSLH
iptables -t mangle -A  OUTPUT --protocol tcp --out-interface eth0 --sport 8022 --jump SSLH
iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 4443 --jump SSLH
iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
iptables -t mangle -A SSLH --jump ACCEPT
ip rule add fwmark 0x1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100

My sslh config looks like:
verbose: true;
foreground: true;
inetd: false;
numeric: false;
transparent: true;
timeout: "2";
user: "root";
pidfile: "/var/run/sslh.pid";

listen:
(
    { host: "192.168.178.32"; port: "443"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "192.168.178.32"; port: "8022"; probe: "builtin"; },
     { name: "ssl"; host: "192.168.178.6"; port: "4443"; probe: "builtin"; },
);

**Comment by martinorob** [comment]
what Nas do you use?

**Comment by kaasszje** [comment]
Synology DS213j

**Comment by msrv** [comment]
Similar issue here:

Ubuntu 14.04 VPS, compiled sslh with libcap.

Iptables (disabled any other rule for testing purpose) looks as following:

`Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination

Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
SSLH       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:1194
SSLH       tcp  --  0.0.0.0/0            0.0.0.0/0            tcp spt:4433

Chain POSTROUTING (policy ACCEPT)
target     prot opt source               destination

Chain SSLH (2 references)
target     prot opt source               destination
MARK       all  --  0.0.0.0/0            0.0.0.0/0            MARK set 0x1
ACCEPT     all  --  0.0.0.0/0            0.0.0.0/0
`

Routing looks this way:

`root@server:~# routel
         target            gateway          source    proto    scope    dev tbl
        default              local                              host     lo 100
        default     GATEWAY                                     eth0
      10.8.0.0/ 24        10.8.0.2                                     tun0
       10.8.0.2                           10.8.0.1   kernel     link   tun0
EXTERNAL.IP.ADDR./ 25                  EXTERNAL IP kernel     link   eth0
       10.8.0.1              local        10.8.0.1   kernel     host   tun0 local
      127.0.0.0          broadcast       127.0.0.1   kernel     link     lo local
     127.0.0.0/ 8            local       127.0.0.1   kernel     host     lo local
      127.0.0.1              local       127.0.0.1   kernel     host     lo local
127.255.255.255          broadcast       127.0.0.1   kernel     link     lo local
 EXTERNAL IP          broadcast  EXTERNAL IPkernel     link   eth0 local
 EXTERNAL IP              local  EXTERNAL IP   kernel     host   eth0 local
 BCAST          broadcast  EXTERNAL IP   kernel     link   eth0 local
        default        unreachable                   kernel              lo unspec
        default        unreachable                   kernel              lo unspec
`
Non - transparent mode works flawlessly.
I called sslh with the following arguments:
`sslh --listen 0.0.0.0:443 --ssl 127.0.0.1:4433 --openvpn 127.0.0.1:1194 --pidfile /var/run/sslh.pid --user root -n --transparent -f`

When i try to access something behind sslh (nginx or openvpn), no error is reported except "ssl timed out"...

**Comment by yrutschle** [comment]
This one is easy :-)

On Wed, Feb 03, 2016 at 03:29:12PM -0800, msrv wrote:
> I called sslh with the following arguments:
> `sslh --listen 0.0.0.0:443 --ssl 127.0.0.1:4433 --openvpn 127.0.0.1:1194 --pidfile /var/run/sslh.pid --user root -n --transparent -f`

As mentionned in the README, you can't use localhost address
when doing transparent proxying, so you need to replace the
127.0.0.1 by the IP of you actual interface (192.168.0.1 or
whatever).

Has to do with iptable processing that I don't really
understand.

**Comment by msrv** [comment]
yrtuschle, that did the trick, thank you very much! Allthough i do not understand why iptables behaves that way... :)

**Comment by rwis62** [comment]
I have the same problem, I can't use transparent proxying to another server ..

**Comment by xqin** [comment]
I have the same problem, I can't use transparent proxying to another server ..

sslh commandline:
```
/usr/sbin/sslh --foreground --transparent --listen 0.0.0.0:443 --ssl 192.168.1.222:4444 --pidfile /var/run/sslh/sslh.pid
```

iptables
```
iptables -t mangle -F
iptables -t mangle -N SSLH
iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 4444 --jump SSLH
iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
iptables -t mangle -A SSLH --jump ACCEPT

ip rule add fwmark 0x1 lookup 100
ip route add local 0.0.0.0/0 dev lo table 100
```

`netstat -nat | grep 4444` result:
```
tcp        0      1 180.116.194.127:2137    192.168.1.222:4444      SYN_SENT
tcp        0      1 180.116.194.127:2138    192.168.1.222:4444      SYN_SENT
tcp        0      1 122.194.197.252:56744   192.168.1.222:4444      SYN_SENT
tcp        0      1 122.194.197.252:56739   192.168.1.222:4444      SYN_SENT
tcp        0      1 180.116.194.127:2139    192.168.1.222:4444      SYN_SENT
tcp        0      1 117.35.60.46:4998       192.168.1.222:4444      SYN_SENT
tcp        0      1 112.84.194.19:4028      192.168.1.222:4444      SYN_SENT
tcp        0      1 117.86.92.28:1920       192.168.1.222:4444      SYN_SENT
tcp        0      1 180.102.148.96:2292     192.168.1.222:4444      SYN_SENT
tcp        0      1 180.102.148.96:2290     192.168.1.222:4444      SYN_SENT
tcp        0      1 180.116.194.127:2140    192.168.1.222:4444      SYN_SENT
tcp        0      1 122.194.197.252:56736   192.168.1.222:4444      SYN_SENT

```

on my web server `192.168.1.222` run  `netstat -nat | grep 4444` result:
```
tcp        0      0 192.168.1.222:4444      122.143.93.16:49177     SYN_RECV
tcp        0      0 192.168.1.222:4444      118.123.36.143:59118    SYN_RECV
tcp        0      0 192.168.1.222:4444      180.116.194.127:2138    SYN_RECV
tcp        0      0 192.168.1.222:4444      122.143.93.16:65533     SYN_RECV
tcp        0      0 192.168.1.222:4444      112.84.194.19:4027      SYN_RECV
tcp        0      0 192.168.1.222:4444      112.84.194.19:4028      SYN_RECV
tcp        0      0 192.168.1.222:4444      180.116.194.127:2136    SYN_RECV
tcp        0      0 192.168.1.222:4444      180.102.148.96:2290     SYN_RECV
tcp        0      0 192.168.1.222:4444      117.35.60.46:4931       SYN_RECV
tcp        0      0 192.168.1.222:4444      122.194.197.252:56729   SYN_RECV
tcp        0      0 192.168.1.222:4444      122.194.197.252:56736   SYN_RECV
tcp        0      0 192.168.1.222:4444      180.102.148.96:2292     SYN_RECV
```


sslh log
```
Aug  2 21:29:55 raspberrypi sslh[9877]: forward to ssl failed:connect: Connection timed out
Aug  2 21:29:55 raspberrypi sslh[9877]: connect: Connection timed out
Aug  2 21:29:55 raspberrypi sslh[9877]: forward to ssl failed:connect: Connection timed out
Aug  2 21:29:55 raspberrypi sslh[9877]: connect: Connection timed out
Aug  2 21:29:56 raspberrypi sslh[9877]: forward to ssl failed:connect: Connection timed out
Aug  2 21:29:56 raspberrypi sslh[9877]: connect: Connection timed out
Aug  2 21:29:56 raspberrypi sslh[9877]: forward to ssl failed:connect: Connection timed out
Aug  2 21:29:56 raspberrypi sslh[9877]: connect: Connection timed out
```

sslh version
```
root@raspberrypi:~# sslh -V
sslh-fork 1.16-2
```


Non - transparent mode works fine.

**Comment by yrutschle** [comment]
Hi,

On Tue, Aug 02, 2016 at 06:39:36AM -0700, 小秦 wrote:
> ```
> /usr/sbin/sslh --foreground --transparent --listen 0.0.0.0:443 --ssl 192.168.1.222:4444 --pidfile /var/run/sslh/sslh.pid
> ```

I don't think (but I'm not sure) you can bind to 0.0.0.0 for
transparent proxying to work -- can you try with the actual
IP of the interface?

Y.

**Comment by xqin** [comment]
Machine A(IP: 192.168.1.11) running `sslh` service.
Machine B(IP: 192.168.1.222) running `nginx` , provide `https` service.

use `--listen 192.168.1.11:443` still not woking.

**Comment by yozik04** [comment]
I am also trying to accomplish the same.
I need transparent proxy for `https` (to use fail2ban and log client IPs) but just a proxy for `openvpn`. `https` is on the same host where `sslh` but `openvpn` is on an another host.

`DAEMON_OPTS="--user sslh --transparent --listen 192.168.5.5:4443 --openvpn 192.168.5.1:1194 --ssl 192.168.5.5:443 --pidfile /var/run/sslh/sslh.pid"`

My `sslh` listens to 4443 on the server. I forward public 443 port on the router to 4443 on the server. I use router for OpenVPN.

Router: `192.168.5.1` (OpenVPN)
Server: `192.168.5.5` (HTTPS, SSLH)

Any idea how to accomplish this? Is it possible to have a transparent proxy only for one of the services?

**Comment by yozik04** [comment]
I have installed `rinetd` to host with `sslh` and now proxying local `openvpn` port to external machine with `openvpn` server. Works good enough for me. For some reason typical port redirection using iptables prerouting does not work. Rule is just ignored...

**Comment by yrutschle** [comment]
It's not currently possible to set transparent on a per-protocol basis, 
but that would make sense. I'll add that to my to-do list (it sounds 
like a small enough task :-) ).

**Comment by shujaaa** [comment]
Not to bump this but :

To my understanding, transparent doesn't work when targetting en external box.

On local machine, (router receiving packets, sslh target is the same router) if I capture on 'lo', I can see packets sent to the local IP (.254) using the original source IP.

If I setup the destination in sslh to my Web server (.1), the packets sent/received have the router IP (.254) as source IP instead of the original IP.

Could you confirm whether transparent proxying can work when targetting an external server ?
If not this would be a really nice feature, as it would allow to track original client's IP, while keeping processes on separate boxes.

Cheers,

**Comment by Infinality** [comment]
I'm posting a "me too".  I've checked my config multiple times and followed the instructions, but whenever I set transparent to "true" I get this when I try to connect from a remote system:

ssh: connect to host [www.domain.com] port 443: No route to host

It comes back immediately.  I did a tcpdump and confirmed that the packets are reaching sslh, but aren't forwarded to their respective services, probably due to some issue with the iptables stuff.  It works just fine with transparent set to "false".  Any help / thoughts are appreciated.

**Comment by gksalil** [comment]
I am new to sslh and trying to setup port multiplexing using sslh to redirect traffic to my https and turn servers. non transparent mode works fine but transparent doesn't work.

my sslh config file 
```
~ # cat etc/sslh.cfg 
verbose: true;
foreground: true;
inetd: false;
numeric: false;
transparent: true; ####### CHANGE THIS MODE
#transparent: false; ####### CHANGE THIS MODE
timeout: 2;
user: "_nobody";  # #### CHANGE THE USER
#user: "root";  # #### CHANGE THE USER
pidfile: "/var/run/sslh.pid";


# Change hostname with your external address name.
listen:
(
{ host: "10.50.157.194"; port: "443"; }
);

protocols:
(

{ name: "http"; host: "10.50.157.194"; port: "445"; },
{ name: "regex"; host: "10.50.157.194"; port: "3478"; regex_patterns: [ "\x21\x12\xa4\x42" ]; }
);
~ # 
```
The console of sslh program execution shows the following


> ~ # /sbin/sslh -F/tandberg/etc/sslh.cfg -v
> http addr: X194:microsoft-ds. libwrap service: (null) log_level: 1 family 2 2 []
> regex addr: X194:nat-stun-port. libwrap service: (null) log_level: 1 family 2 2 []
> listening on:
>     X194:https  []
> timeout: 2
> on-timeout: http
> listening to 1 addresses
> turning into _nobody
> sslh-fork tempo-boot-20-6-g271a27e-dirty started
> capabilities: = cap_net_admin+ep
> 
> 
> 
> accepted fd 4
> **** writing deferred on fd -1
> probing for http
> probing for regex
> all probes failed, connecting to first protocol: http
> connecting to X194:microsoft-ds family 2 len 16
> accepted fd 4
> **** writing deferred on fd -1
> probing for http
> probing for regex
> all probes failed, connecting to first protocol: http
> connecting to X194:microsoft-ds family 2 len 16
> accepted fd 4
> **** writing deferred on fd -1
> probing for http
> probing for regex
> all probes failed, connecting to first protocol: http
> connecting to X194:microsoft-ds family 2 len 16
> forward to http failed:connect: Connection timed out
> forward to http failed:connect: Connection timed out
> connect: Connection timed out
> connect: Connection timed out
> forward to http failed:connect: Connection timed out
> connect: Connection timed out

following is the iptable command I ran in the shell

> ~ # iptables -t mangle -N SSLH
> iptables: Chain already exists.
> ~ # iptables -t mangle -A OUTPUT --protocol tcp --out-interface eth0 --sport 445 --jump SSLH
> ~ # iptables -t mangle -A SSLH --jump MARK --set-mark 0x1
> ~ # iptables -t mangle -A SSLH --jump ACCEPT
> ~ # ip rule add fwmark 0x1 lookup 100
> RTNETLINK answers: Address family not supported by protocol
> ~ # ip route add local 0.0.0.0/0 dev lo table 100
> RTNETLINK answers: File exists
> 

Basically when I access this server using my browser, I am expecting the traffic to be routed to UI to port 445. Which doesn't happen

Could you please help me to set this.
PS: I am not sure I understand the iptables commands properly and did it correct.

~S

**Comment by yrutschle** [comment]
By the looks of it your sslh setup should be fine, however:

> ~ # ip rule add fwmark 0x1 lookup 100
> RTNETLINK answers: Address family not supported by protocol

this suggests something wrong in the iptables rules. Now, I think this works for most people, so it's something up with your kernel setup I'd say: missing iptable modules for example?

**Comment by gksalil** [comment]
Thanks for the pointer. I will check why this issue happens and how to resolve this.
But just curious to know, from sslh context, what is the relevance of this command and how it helps sslh to do the intended work ?

**Comment by yrutschle** [comment]
Assuming this is fixed. Transparent proxying documentation has been updated since, too, with a setup for when the target server is not on the same host.

**Comment by toquanghieu** [comment]
I get problem too, I cannot connect to TLS
`verbose: false;
foreground: true;
inetd: true;
numeric: false;
transparent: true;
timeout: 2;
user: "sslh";


# Change hostname with your external address name.
listen:
(
    { host: "localhost"; port: "1022"; }
);

protocols:
(
     { name: "ssh"; service: "ssh"; host: "127.0.0.1"; port: "22"; keepalive: true; fork: true; tfo_ok: true },
     { name: "tls"; host: "10.10.10.8"; port: "443"; log_level: 0; }
);`
