### ISSUE TITLE
Can't establish secure connection error in SSLH and Apache/SSL setup

### ISSUE THREAD

**Issue by avamk** [yrutschle/sslh#78]
Hello,

I am trying to integrate SSLH into my existing OpenSSH and Apache setup. I changed Apache to listen on port 1234, and set SSLH to direct HTTPS (i.e. with SSL) connections on port 443 to port 1234, and SSH connections to my OpenSSH port. SSH works, but HTTPS doesn't.

When I try to open my webpage on the Apache server, my browser tells me "Secure Connection Failed The connection to nycticebus.penonek.com was interrupted while the page was loading. The page you are trying to view cannot be shown because the authenticity of the received data could not be verified."

Is this a known issue, and if so how might I alleviate it? Thank you!

**Comment by yrutschle** [comment]
On Tue, Jan 26, 2016 at 07:04:09AM -0800, avamk wrote:
> I am trying to integrate SSLH into my existing OpenSSH and Apache setup I changed Apache to listen on port 1234, and set SSLH to direct HTTPS (ie with SSL) connections on port 443 to port 1234, and SSH connections to my OpenSSH port SSH works, but HTTPS doesn't
> 
> When I try to open my webpage on the Apache server, my browser tells me "Secure Connection Failed The connection to nycticebuspenonekcom was interrupted while the page was loading The page you are trying to view cannot be shown because the authenticity of the received data could not be verified"
> 
> Is this a known issue, and if so how might I alleviate it? Thank you!

Not a known issue, sslh + openssh + apache is probably the
most widely-used configuration, so I'm going to guess there
is something wrong in your configuration.

What I'd first advise is insure that it is in fact HTTPS on
1234 and not HTTP, e.g.:
w3m https://yourserver:1234

If that's not enough, please report information such as at
least your sslh configuration.

Y.

**Comment by avamk** [comment]
Hello,

I tried connecting to my Apache server (now set to listen on 4443 for
HTTPS) via https://[my domain]:4443 and it works normally.

However, I have SSLH listen on 443 to pass connections to 4443 for
Apache, and connecting to https://[my domain]:443 gives me that Secure
Connection Failed error.

Here is my SSLH configuration file:

http://pastebin.com/NVs03Gc4

I'd appreciate any help you can give!! Thank you.

**Comment by yrutschle** [comment]
> Here is my SSLH configuration file:
> 
> http://pastebin.com/NVs03Gc4

     { name: "http"; host: "localhost"; port: "4443"; probe: "builtin"; }

This is wrong, you want to forward HTTPS (so, SSL/TLS), not
HTTP. The HTTP probe actually checks it's HTTP (so that the
message starts with "GET" or something like that), but can't
see what's in the ciphered connection.

Try this instead:
     { name: "ssl"; host: "localhost"; port: "4443"; probe: "builtin"; }

Or "anyprot", should also work.

Y.

**Comment by avamk** [comment]
I tried your suggestion and it works now, thank you so much for your
help and for making such a brilliant piece of software!

**Comment by jc332** [comment]
Hello,

I am having the same issue however I cannot find the line you reference in my sslh config...
[sslh.txt](https://github.com/yrutschle/sslh/files/282246/sslh.txt)

Any help would be much appreciated.
Thanks

**Comment by yrutschle** [comment]
> [sslh.txt](https://github.com/yrutschle/sslh/files/282246/sslh.txt)

You need to uncomment the line that defines CONFIG, then
create a valid /etc/sslh.cfg file. There are two examples
with sslh: basic.cfg which shows the most common setup, and
example.cfg which hopefully documents everything that is
possible with the configuration file.

Y.

**Comment by jc332** [comment]
Thanks. But now I get the following when I try to start the service:

May 26 11:42:15 node systemd[1]: Starting SYSV: Sslh accepts connections on specified ports, and forwards...
May 26 11:42:15 node sslh[22357]: Starting sslh: [hostname]:https:bind: Address already in use
May 26 11:42:15 node sslh[22357]: [FAILED]
May 26 11:42:15 node systemd[1]: sslh.service: control process exited, code=exited status=1
May 26 11:42:15 node systemd[1]: Failed to start SYSV: Sslh accepts connections on specified ports, and forwards.
May 26 11:42:15 node systemd[1]: Unit sslh.service entered failed state.
May 26 11:42:15 node systemd[1]: sslh.service failed.

**Comment by yrutschle** [comment]
On Thu, May 26, 2016 at 04:01:13AM -0700, jc332 wrote:
> May 26 11:42:15 node sslh[22357]: Starting sslh: [hostname]:https:bind: Address already in use

You probably have a Web server already listening on port 443.

Please read the README, I think this is mentionned.

**Comment by jc332** [comment]
sorted - there was a second sslh process running (listening on 443). Killed that and I can now restart the service.
However, I am now experiencing the original issue again...
