### ISSUE TITLE
corkscrew + HTTP proxy + openvpn + ssh + https + sslh = no openvpn

### ISSUE THREAD

**Issue by hmage** [yrutschle/sslh#79]
Hello!

Server command:

```
/usr/local/sbin/sslh --user sslh --listen 0.0.0.0:443 --openvpn 127.0.0.1:1194 --ssh 127.0.0.1:22 --ssl 127.0.0.1:445 --pidfile /var/run/sslh/sslh.pid
```

Ports:

```
root@dhmd:/etc/openvpn# netstat -naptu | fgrep LISTEN
tcp        0      0 0.0.0.0:1194            0.0.0.0:*               LISTEN      23053/openvpn
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      18123/unbound
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      608/sshd
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      18123/unbound
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      22656/sslh
tcp        0      0 127.0.0.1:445           0.0.0.0:*               LISTEN      22726/apache2
tcp6       0      0 :::80                   :::*                    LISTEN      22726/apache2
tcp6       0      0 :::22                   :::*                    LISTEN      608/sshd
tcp6       0      0 ::1:8953                :::*                    LISTEN      18123/unbound
```

Client is behind HTTP proxy that allows HTTP CONNECT only to port 443.

machine -> non-transparent squid -> internet -> sslh -> https/ssh/openvpn

I am able to ssh to the machine using corkscrew, open https page on the browser, but not openvpn to it using proxy settings inside openvpn.

syslog when trying to connect to openvpn:

```
Feb 26 21:18:24 dhmd sslh[22656]: connection from firewall.example.com:45808 to dhmd:https forwarded from localhost:50936 to localhost:ssh
Feb 26 21:18:24 dhmd sshd[23088]: Did not receive identification string from 127.0.0.1
Feb 26 21:18:32 dhmd sslh[22656]: connection from firewall.example.com:58468 to dhmd:https forwarded from localhost:50938 to localhost:ssh
Feb 26 21:18:32 dhmd sshd[23090]: Did not receive identification string from 127.0.0.1
```

When I replace sslh with openvpn listening directly on port 443, it works fine.

For some reason sslh classifies the connection as ssh instead of openvpn, maybe the probe that detects openvpn needs updating?

sslh is latest release version -- v1.17.

**Comment by yrutschle** [comment]
ssh is the default in case of "timeout" (when no packet is received from the client within 2 seconds).
It happens that OpenVPN clients take longer to send their first packet: try to increase the timeout to 5s or so.

**Comment by yrutschle** [comment]
ssh is the default in case of "timeout" (when no packet is received from the client within 2 seconds).
It happens that OpenVPN clients take longer to send their first packet: try to increase the timeout to 5s or so.

**Comment by yrutschle** [comment]
ssh is the default in case of "timeout" (when no packet is received from the client within 2 seconds).
It happens that OpenVPN clients take longer to send their first packet: try to increase the timeout to 5s or so.

**Comment by yrutschle** [comment]
ssh is the default in case of "timeout" (when no packet is received from the client within 2 seconds).
It happens that OpenVPN clients take longer to send their first packet: try to increase the timeout to 5s or so.

**Comment by yrutschle** [comment]
ssh is the default in case of "timeout" (when no packet is received from the client within 2 seconds).
It happens that OpenVPN clients take longer to send their first packet: try to increase the timeout to 5s or so.

**Comment by hmage** [comment]
I'll try that and will let you know if it works.

**Comment by phonicmouse** [comment]
@hmage same problem here....have you solved this?

**Comment by hmage** [comment]
@phonicmouse no, unfortunately -- the environment changed, though, so I don't have to use HTTP proxy anymore, so I stopped trying to figure it out.

**Comment by phonicmouse** [comment]
I think i figured it out....in my setup I don't have ssh, so i added the following parameters to sslh: --t 5s and --on-timeout tls
And now it works.

**Comment by yrutschle** [comment]
I believe this is now fixed.
