### ISSUE TITLE
feature request: relay client certificate details

### ISSUE THREAD

**Issue by dpocock** [yrutschle/sslh#82]
Some connections do a two-way mutual TLS handshake where the client sends a certificate to the server.

It would be nice if sslh could do these two way handshakes and then pass the client certificate and other details such as source IP to the real server process out-of-band.

This would require each server process to have some sslh-aware socket library.

**Comment by yrutschle** [comment]
On Sun, Mar 06, 2016 at 05:18:26AM -0800, Daniel Pocock wrote:
> Some connections do a two-way mutual TLS handshake where the client sends a certificate to the server.
> 
> It would be nice if sslh could do these two way handshakes and then pass the client certificate and other details such as source IP to the real server process out-of-band.
> 
> This would require each server process to have some sslh-aware socket library.

I don't think I understand your need. 

TLS with mutual authentication should be forwarded just fine
by sslh, so the server would receive the client certificate,
and if using transparent proxying the server would also
receive the client's IP address.

Does that not cover what you're trying to do?

**Comment by dpocock** [comment]
What do you mean when you say it should be forwarded just fine?

Do you mean that sslh can somehow make a TLS connection to the real server process and create a client certificate on the fly to impersonate the TLS client?

Or are you saying that sslh can somehow relay the encrypted stream to the right server without being party to the handshake?  In that case, how is it able to send the connection to the right server process if there are several TLS servers behind sslh (HTTPS, SIP, WebSocket, ...)?

**Comment by yrutschle** [comment]
On Mon, Mar 07, 2016 at 03:45:02AM -0800, Daniel Pocock wrote:
> What do you mean when you say it should be forwarded just fine?

I mean it should work just fine :-)

> Do you mean that sslh can somehow make a TLS connection to the real server process and create a client certificate on the fly to impersonate the TLS client?

No.

> Or are you saying that sslh can somehow relay the encrypted stream to the right server without being party to the handshake?  In that case, how is it able to send the connection to the right server process if there are several TLS servers behind sslh (HTTPS, SIP, WebSocket, ...)?

Yes, provided that the client supports SNI (to support
several virtual HTTPS hosts) and/or ALPN (to support several
protocols carried over TLS).

SNI and ALPN are extensions to TLS to do just that.

I don't think the servers themselves need to support SNI or ALPN.

Y.

**Comment by dpocock** [comment]
OK, I'm aware of SNI.  This feature request is for those cases where SNI can not be used and where sslh needs to inspect the data from the client before deciding which server to send the connection to.

I can see two ways to do that:

a) sslh acts as a man-in-the-middle and uses a local CA to create a substitute client certificate on demand that the real server will trust.  Some corporate proxy servers do exactly the same thing in reverse to monitor outgoing HTTPS browsing by employees.  These substitute certificates, combined with the transparent proxying, should satisfy the server process, even without patching the server itself.

b) sslh provides some library for server processes to communicate over a UNIX socket and get access to information about the real client, including a copy of their certificate.

**Comment by yrutschle** [comment]
Actually, this may be doable with stunnel in front of sslh. Then sslh can look at the actual protocol, and forwards the unsecured protocol to the server (doesn't matter if the network between sslh and the final server is trusted). Or add another stunnel between sslh and the final server if it's really important to be on TLS after sslh.

Either way, I'm not at all keen on including anything as complex as you're suggesting.
