### ISSUE TITLE
Does --transparent option require 'probe: "builtin"' to work correctly?

### ISSUE THREAD

**Issue by tizot** [yrutschle/sslh#88]
I want to use sslh with the transparent option, and with 3 protocols : ssh, https and openvpn, on my dedicated server running on Ubuntu Server 15.10. The version of sslh used is from official repositories and is 1.17-2.

I followed the README insctructions but sslh would always fail to redirect my packets correctly. Only the first protocol in my config file would be used. When running `sslh -v -f`, I got : 
`all probes failed, connecting to first protocol: ssh`

It finally worked when I added `probe: "builtin"` to each protocol, which is not said in the documentation.

Here is my config file, which works as expected:

```
verbose: false;
foreground: false;
inetd: false;
numeric: false;
transparent: true;
timeout: 5;
user: "root";
pidfile: "/var/run/sslh/sslh.pid";


# Change hostname with your external address name.
listen:
(
    { host: "xxx.xxx.xxx.xxx"; port: "443"; }
);

protocols: 
(
     { name: "ssh"; service: "ssh"; host: "xxx.xxx.xxx.xxx"; port: "2424"; log_level: 1; probe: "builtin"; },
     { name: "ssl"; service: "https"; host: "xxx.xxx.xxx.xxx"; port: "444"; log_level: 1; probe: "builtin"; },
     { name: "openvpn"; host: "xxx.xxx.xxx.xxx"; port: "1194"; probe: "builtin"; }
);
```

I think you should either update the documentation, or maybe track a bug...

Thanks anyway for this very useful tool! 😄

**Comment by yrutschle** [comment]
Thank you for your feedback;

The documentation refers explicitly to 'example.cfg', which
I believe contained references to 'builtin'. Was that not
clear enough? (I'd prefer to avoid duplicating all the
explanations in example.cfg in the README, as it's a pain to
keep it all in sync...)

Also, the configuration file has changed rather drasticaly
and builtin no longer exists.

**Comment by yrutschle** [comment]
Closing because obsolete and no answer.
