### ISSUE TITLE
multiple ssh hosts

### ISSUE THREAD

**Issue by jmls** [yrutschle/sslh#89]
I have multiple hosts running ssh (host1.co.uk, host2.co.uk) and I'm wanting to run sslh, is it possible to configure it to send the connection to the correct host based on the hostname ?

**Comment by gbisheimer** [comment]
AFAIK, ssh clients doesn't send hostname information to the server as HTTP does. So there is no way to tell which host has received the connection request.

Can you configure DNS records to redirect the request to a different port?

**Comment by yrutschle** [comment]
On Sun, Jun 05, 2016 at 08:07:12AM -0700, Guillermo Bisheimer wrote:
> AFAIK, ssh clients doesn't send hostname information to the server as HTTP does.

Correct.

> So there is no way to tell which host has received the connection request.
> Can you configure DNS records to redirect the request to a different port?

You confused me. sslh works at IP level and has little
notion of host names (except at setup time), and I don't
understand what you need... The host receiving the
connection request is that on which sslh runs, right? :-)

Y.

**Comment by yrutschle** [comment]
Oops, sorry about my previous comment, I didn't realise you were in fact replying to someone else.

@jmls : No, that's not possible for the reason @gbisheimer says (ssh connect to an IP and has no notion of host names). You'll need two external IP, or the simplest is probably to have 2 different ports on the same host (you can configure your clients to connect to the appropriate port (see ssh_config(5), option Port)) and the appropriate sslh instances running behind that.
