### ISSUE TITLE
tls: no alpn_protocols specified

### ISSUE THREAD

**Issue by beansandmash** [yrutschle/sslh#90]
Get "tls: no alpn_protocols specified" when not specifying alpn_protocols while specifying sni_hostnames. example.cfg says this should be doable. Similarly if sni_hostnames not specified while specifying alpn_protocols, get "tls: no sni_hostnames specified".

I believe this is unintended behaviour?

# sslh -V
sslh-fork v1.18

**Comment by yrutschle** [comment]
Github came back: I pushed the patch.

**Comment by beansandmash** [comment]
Thanks, it works without specifying now, however specifying sni only does not work for me. Specifying alpn on its own does work.

These work:
{ name: "tls"; host: "localhost"; port: "442"; alpn_protocols: [ "h2", "http/1.1", "spdy/1", "spdy/2", "spdy/3" ]; sni_hostnames: [ "hostname.com", "*.hostname.com" ]; probe: "builtin"; log_level: 0; },
{ name: "tls"; host: "localhost"; port: "442"; alpn_protocols: [ "h2", "http/1.1", "spdy/1", "spdy/2", "spdy/3" ]; probe: "builtin"; log_level: 0; },

This does not:
{ name: "tls"; host: "localhost"; port: "442"; sni_hostnames: [ "hostname.com", "*.hostname.com" ]; probe: "builtin"; log_level: 0; },

Is it a configuration issue on my end or a bug?

**Comment by yrutschle** [comment]
Fix included in the mainline; thanks for the patch.
