### ISSUE TITLE
Reload sslh configuration without dropping active connections

### ISSUE THREAD

**Issue by gbisheimer** [yrutschle/sslh#94]
Is there a way to modify sslh configuration file and request to reload forwarding rules without dropping active connections?

**Comment by yrutschle** [comment]
On Sun, Jun 05, 2016 at 08:08:36AM -0700, Guillermo Bisheimer wrote:
> Is there a way to modify sslh configuration file and request to reload forwarding rules without dropping active connections?

I remember looking into that, and it's not really trivial.
If you need that feature, it's probably best to use the
sslh-fork version which behaves that way.

Y.

**Comment by gbisheimer** [comment]
I'm using sslh to forward tinc vpn packages. I need to use sslh-select
version because I will have a lot of active connections.

I will take a look at the code to see if I can patch it. Can I just reload
the config file, update internal config structures and  let new connections
to be forwarded as configured?

Ing. Guillermo Bisheimer
B&S Sistemas de Control y Equipamientos
Av. de los Constituyentes 1172
(E3116CIX) Crespo, Entre Ríos
Tel/Fax: (0343) 4078990
Cel: (0343) 154679052
WEB: www.bys-control.com.ar
e-mail: gbisheimer@bys-control.com.ar
skype: guillermo.bisheimer

**Comment by RadarNyan** [comment]
> If you need that feature, it's probably best to use the sslh-fork version which behaves that way.

@yrutschle can you please explain more about how do you accomplish that? I've tried to run sslh with -F switch (sslh-fork version) and edit /etc/sslh.cfg after sslh is started. I can see new process being created as new connections coming in but I can't seem to get them to use new settings - they always uses the config when I started sslh with.

**Comment by yrutschle** [comment]
On Wed, Nov 02, 2016 at 12:21:20AM -0700, RadarNyan wrote:
> > If you need that feature, it's probably best to use the sslh-fork version which behaves that way.
> @yrutschle can you please explain more about how do you accomplish that? I've tried to run sslh with -F switch (sslh-fork version) and edit /etc/sslh.cfg after sslh is started. I can see new process being created as new connections coming in but I can't seem to get them to use new settings - they always uses the config when I started sslh with.

Once you've edited your configuration, restart sslh
(/etc/init.d/sslh restart, presumably). The listening sslh
processes will restart and pick up the new settings, but all
the 'shoveling' processes that are working for established
connections will keep going until the end of their
respective connections.

**Comment by RadarNyan** [comment]
> Once you've edited your configuration, restart sslh (/etc/init.d/sslh restart, presumably)

I thought restart sslh will kill all instanses so didn't even try that, will try later. So if restart sslh won't terminate existing processes, how do I do a "real" restart? If I write a bash script like this:

```
pkill sslh
/etc/init.d/sslh start
```

It doesn't work. I don't know why, maybe the new sslh process is also killd by pkill I guess? I can't use kill -9 <pid> since sslh-fork creats a lot processes and only one pid is recorded to the given file.

**Comment by yrutschle** [comment]
On Fri, Nov 04, 2016 at 12:18:07AM -0700, RadarNyan wrote:
>  So if restart sslh won't terminate existing processes, how do I do a "real" restart?

What would be the purpose? Why not simply close all existing
connections?

Otherwise, I'd expect a simple killall sslh-fork to do the
trick.

Y.

**Comment by yrutschle** [comment]
Unclear there is still interest in this issue, and you can now set fork on a per-protocol basis, so I'm closing.

**Comment by dzhou3** [comment]
> Once you've edited your configuration, restart sslh (/etc/init.d/sslh restart, presumably). The listening sslh processes will restart and pick up the new settings, but all the 'shoveling' processes that are working for established connections will keep going until the end of their respective connections.

Hi @yrutschle, I tried the restart command above with `sslh-fork 1.20-1` on an Ubuntu 22.04 server. It turns out that it's not graceful reload -- all the sslh processes are re-created but all the existing active connections are terminated. If you are able to add this graceful reload feature in the latest release, it will be very helpful.
